// content/y7-science/U02_1b/plan.js
// One-page teacher lesson plan, rendered by src/pages/Plan.jsx.
export const plan = {
  duration: '50 minutes',
  objective:
    'Students can state the particle theory in one sentence; describe how particles are arranged and how they move in solids, liquids and gases; use that arrangement to explain why a liquid can be poured and a solid cannot, and why only a gas can be compressed; define a vacuum; and name at least one genuine weakness of the particle theory after resolving the sponge problem.',
  materials: [
    'Projector / TV for the lesson deck',
    'Student science notebooks and RULERS — the three-box Activity is ruled up in class',
    'Learner’s Book (Unit 2.1, pages 31–34)',
    'Their four-question table from 2.1a — this whole lesson explains it, so it must be open on the desk',
    'THE TWO SYRINGES from 2.1a, water and air, kept for the compression slide — the class re-does the prediction knowing the answer',
    'Optional but excellent: a kitchen sponge and a marshmallow, passed round at the p.34 task',
    'Optional: a clear glass of still water and a drop of ink or food colouring, set going at the start so it has spread by the end',
    'Floor space for the "you are the particles" task — the class needs room to stand and rearrange',
  ],
  vocab: [
    { term: 'Particle', def: 'a tiny piece of matter, far too small to see' },
    { term: 'Particle theory', def: 'all matter is made of particles, arranged differently in solids, liquids and gases' },
    { term: 'Vibrate', def: 'to make tiny movements on the spot without leaving your place' },
    { term: 'Attractive force', def: 'the pull between particles — strong in a solid, weak in a liquid, almost none in a gas' },
    { term: 'Flow', def: 'to move like a liquid; only possible if particles can move past one another' },
    { term: 'Compress', def: 'to squash into a smaller space; only possible if there are gaps to close' },
    { term: 'Vacuum', def: 'a space with no particles at all — not thin air, nothing' },
    { term: 'Diffuse / spread out', def: 'what the ink and the cooking smell do, entirely on their own' },
  ],
  timeline: [
    { time: '0–4 min', phase: 'Starter — recall, books closed', detail: 'Three things a gas can do that a solid cannot, from memory, then check against their own table from 2.1a. If you have the glass of water, drop the ink in NOW and put it on a windowsill where the class can see it; you will come back to it at the end and it will have spread.' },
    { time: '4–9 min', phase: 'The unpaid debt + the ink', detail: 'Slide 2 is Monday’s unanswered question, restated and still unanswered. Then the ink photograph: nobody stirred it, and it is going everywhere by itself. Ask what is moving. Do not accept "the ink" — push for "something the ink is made of". That is the door into the theory.' },
    { time: '9–15 min', phase: 'The theory, and the evidence', detail: 'One slide, one sentence, one copy-down: all matter is made of particles, arranged differently in the three states. Then the salt crystals — nobody cut those cubes. If the particles are stacked in a regular pattern, the pattern should sometimes show on the outside, and here it does. This is the slide that makes the theory feel like science instead of a story.' },
    { time: '15–24 min', phase: 'Three arrangements, one at a time', detail: 'Solid, liquid, gas — one slide and one copy-down panel each. All three are drawn in the SAME beaker on purpose, so point at the same three things every time: are they touching? is there a pattern? does it reach the walls? Keep these unhurried; everything after this depends on the three pictures being clear.' },
    { time: '24–29 min', phase: 'You are the particles (p.32)', detail: 'Everyone stands. Arrange as a solid — regular rows, touching, nobody moving. Then a liquid — still touching, but sliding and swapping. Then a gas — spread to the walls of the room. Call the changes yourself. Sit down, SAY the three sentences in pairs, and only then write them. The speaking has to come first or you get three copied sentences and no English.' },
    { time: '29–38 min', phase: 'Page 33 — explaining the properties', detail: 'Slide 10 asks why water pours and a brick does not, with no answer on it. Then the two rules (copy both). Then the compare slide: strong pull in a solid, weak pull in a liquid — copy ATTRACTIVE FORCES at the gas slide. Get the syringes back out for the compression slide and let a student do it again now that they know why. "The gaps got smaller" is the whole idea.' },
    { time: '38–42 min', phase: 'Vacuum', detail: 'A box of gas looks empty but is not; take every particle out and it is a vacuum. Copy VACUUM. Then the Blue Marble: the black is very nearly a perfect vacuum, which is why there is no sound in space. Sound needing particles is worth ten extra seconds — it is the fact they will repeat at home.' },
    { time: '42–47 min', phase: 'The sponge (p.34)', detail: 'THE BEST QUESTION IN THE SECTION. A solid cannot be compressed, but you can squash a sponge with one hand. Is the theory wrong? Three minutes in pairs, pass the sponge round if you brought one, take answers before revealing. Then the resolution and the strengths/weaknesses reveal. This is the first time this class judges a model rather than learning one — protect the time for it.' },
    { time: '47–50 min', phase: 'Draw This, recap, homework', detail: 'The three-box Activity: rule three big squares, draw the particles, write the properties in the space around them. It is eight minutes of work and there are three left, so start it here and finish it for homework — say so explicitly. Then the six-point checklist and the copy-count. Homework: read pp.31–34, tick the book’s checklist honestly, and explain the bottle-versus-balloon to somebody at home in English.' },
  ],
  answers: [
    { q: 'The smell from the kitchen / the ink in the glass', a: 'Particles of the food have spread through the air all the way to the bedroom, moving by themselves; the ink particles spread through still water the same way. The key word is BY THEMSELVES — nothing pushed them. If a student says "the air carried it", ask what was moving the air with the door shut.' },
    { q: 'Particle theory', a: 'All matter is made up of tiny particles, far too small to see. The particles are arranged differently in solids, liquids and gases. Same particles in all three — nothing added, nothing removed.' },
    { q: 'Why is every grain of salt a cube?', a: 'Because the particles inside are stacked in a fixed, regular, cubic pattern, and at the surface that pattern shows. It is indirect evidence, and it is worth naming as such: we cannot see the particles, but we can see what their arrangement does to the shape.' },
    { q: 'Particles in a solid', a: 'In a fixed pattern, tightly packed, held together strongly. They can vibrate but stay in the same place. The block in the diagram does not touch the beaker walls — a solid keeps its own shape.' },
    { q: 'Particles in a liquid', a: 'Still touching each other, but held together only weakly, so they can move past one another and change places. No pattern. The flat top surface is the container’s shape, not the liquid’s.' },
    { q: 'Particles in a gas', a: 'Not touching. Far apart, moving quickly in all directions, with almost nothing holding them together. They spread out by themselves to fill the whole space.' },
    { q: 'Q2 (p.32) — copy and complete', a: 'In solids, the particles are arranged in a fixed pattern, tightly packed and touching. In liquids, the particles are arranged with no pattern, still touching but able to slide past each other. In gases, the particles are arranged far apart, with large spaces between them. Accept any wording that gets the packing and the movement; mark it as English, in full sentences.' },
    { q: 'Why can you pour water but not a brick?', a: 'Matter can only flow if the particles can move past one another. In a solid the attractive forces are strong and hold every particle in place, so nothing can move past anything. In a liquid the forces are weak enough to let particles slide but strong enough to keep them touching.' },
    { q: 'The two rules (p.33)', a: 'Matter can only flow (be poured) if the particles can move past one another. Matter can only change volume if the particles can spread out or move closer together. A solid fails both; a liquid passes the first and fails the second; a gas passes both. That is the whole table from 2.1a in two sentences.' },
    { q: 'Why the air syringe moved and the water one did not', a: 'A gas has large gaps between its particles, so pushing simply moves them closer and the gas takes up less room — nothing is squashed and nothing escapes, the gaps just get smaller. In water the particles are already touching, so there is no gap left to close and the plunger will not move.' },
    { q: 'Vacuum', a: 'A space where there are no particles at all. A vacuum contains nothing. Watch for "a vacuum is empty air" — empty air is still air. Space is very nearly a perfect vacuum, which is why sound cannot travel there: sound needs particles to pass the movement along.' },
    { q: 'Q1 (p.34) — the sponge', a: 'The sponge is not solid all the way through: it is a thin solid skeleton with AIR in every hole. Squeezing it compresses the air, not the solid. The solid part just folds around the smaller gaps, and the air pushes it back when you let go. The theory is not broken — the sponge simply is not the thing being compressed. A marshmallow is the same trick.' },
    { q: 'Q2 (p.34) — how well does particle theory explain the properties?', a: 'Very well. Every property in the 2.1a table comes out of the arrangement, with no extra assumptions: shape, volume, pouring, compressing. It also explains things that were not in the table at all, like the smell and the ink.' },
    { q: 'Q3 (p.34) — strengths', a: 'One simple idea explains a great many separate observations. It makes predictions that can be TESTED — the two syringes were a prediction before they were a demonstration. It works for substances nobody has tried it on yet.' },
    { q: 'Q4 (p.34) — weaknesses', a: 'Nobody has ever seen a particle directly, so it asks you to believe in something invisible. The diagrams make particles look like hard little balls with clear edges, which they are not. It says nothing about WHY the attractive forces are strong or weak, or why some solids melt easily and others do not. Accept anything that identifies the model as a simplification.' },
    { q: 'Exit question — a full bottle of air or a full bottle of water?', a: 'The air. Both bottles are "full", but a gas is mostly empty space between its particles, while a liquid’s particles are touching. That is why you can squash one and not the other — the same answer as the syringes, arrived at from the other direction.' },
  ],
  notes:
    'THIS DECK ASSUMES 2.1A HAS BEEN TAUGHT. It refers to the syringes, the four-question table and the smell-from-the-kitchen question by name, and the table has to be open on the desk. If a student was absent on Monday, sit them next to somebody with the table. ' +
    'THE SHAPE OF THE HOUR is the same journey three times, and the repetition IS the argument: here is how the particles are arranged (p.31), here is the property that follows from it (p.33), here is the thing you watched happen on Monday. Say that out loud at the two-rules slide. Nothing in this lesson is a new fact about the world; it is one idea being used over and over on facts they already own. ' +
    'ALL THREE PARTICLE DIAGRAMS USE THE SAME BEAKER on purpose. The Learner\'s Book draws three free-floating clumps, which shows the packing but hides the payoff. In one container you can point at the same three things every time — are they touching? is there a pattern? does it reach the walls? — and pages 31 and 33 become the same picture. Use that phrasing; it is the fastest route through the whole lesson. ' +
    'WHAT GETS COPIED, and nothing else: particle theory, the three arrangements (one panel each), the two rules from p.33, attractive forces, vacuum, three sentences of their own English for Q2, and the three-box drawing. Seven written items and one drawing. The p.32 "copy and complete" is done as SPEAKING FIRST — say the sentence in pairs, then write it — because copying three sentences off a screen teaches nothing and this class needs the speaking more than the copying. ' +
    'TWO SLIDES HAVE NO ANSWER ON THEM ON PURPOSE: the restated smell question at the start, and "why can you pour water but not a brick". Both are paid off within ten minutes. ' +
    'THE SPONGE IS THE BEST THING IN THE SECTION AND MUST NOT BE CUT. It is the first time this class is asked to judge a scientific model rather than learn one: the theory says a solid cannot be compressed, the sponge plainly can be, so either the theory is wrong or something has been missed. Let them sit in that for a full three minutes before the resolution. Bring a real sponge and a marshmallow if you can; passing them round is worth more than the photograph. If you are running late, start the Draw This in class and finish it at home — cut THAT, not this. ' +
    'THE INK DEMONSTRATION, if you have a glass and a drop of food colouring, should be started at minute zero and left where the class can see it. Coming back to it at the end, visibly spread, is the strongest single piece of evidence in the lesson and it costs no lesson time at all. ' +
    'GET THE SYRINGES OUT AGAIN. They were a prediction on Monday; today they are an explanation. Letting one student push the air plunger while another says "the gaps are getting smaller" is thirty seconds and it welds the two lessons together. ' +
    'THE ENGLISH BEAT is "vibrate" — it means small movements on the spot, NOT travelling. Students who half-hear it will say the particles in a solid move around slowly. Ask them to vibrate in their chair without leaving it; that settles it in five seconds. ' +
    'AFTER THIS, section 2.1 is finished and 2.2 Changes of State is next. The three-box page is deliberately drawn with wide margins because 2.2 adds the arrows between the boxes. Tell them not to fill the page. ' +
    'Image sources and licences are in content/y7-science/U02_1b/images/CREDITS.json — all openly licensed (CC BY-SA / public domain). No Learner\'s Book scans are used; every figure is redrawn in diagrams.js.',
}
