// content/freshman-math/U01_3/plan.js
// One-page teacher lesson plan, rendered by src/pages/Plan.jsx.
export const plan = {
  duration:
    'About 80 minutes of material — two periods, or one long block. The natural split is after slide 12 ("Three in a Straight Line"): period 1 is the map, the activity and the three-point rule, period 2 is the compass work and the payoff. Do NOT split between slides 4 and 23; the conspiracy has to be opened and closed in the same room, or the punchline is lost.',
  objective:
    'Students can define a circle as the set of points a fixed distance from a centre, and name the centre and radius on a drawing; explain why a pair of compasses can only ever ' +
    'draw a circle; state that any three points that are not collinear lie on exactly one circle, and that three collinear points lie on none, justifying the exception by the fact ' +
    'that a straight line meets a circle at most twice; construct the perpendicular bisector of a segment with compass and straight edge, and explain why two equal-radius arcs are ' +
    'sufficient to determine it; and construct the circle through three given points by intersecting two perpendicular bisectors. They also leave able to say why a pattern that ' +
    'must always occur is not evidence of anything — which is the point of the map the lesson opens with.',
  materials: [
    'Projector / TV for the lesson deck',
    'A PAIR OF COMPASSES PER STUDENT — check them the day before; a loose hinge makes the whole lesson impossible',
    'Spare compasses (expect two or three failures in a class)',
    'Rulers, one each, marked in cm',
    'Sharp pencils, and a sharpener — a blunt compass pencil loses 2 mm of accuracy immediately',
    'THE PRINTED MAP HANDOUT, one per student — homework/alg13/alg13.pdf, on the site under Homework as "A1.3"',
    'Coloured pencils, two or three colours per student, so the three circles on the map stay apart',
    'Student notebooks — plain paper is better than squared for this lesson',
  ],
  vocab: [
    { term: 'Circle', def: 'all the points that are a fixed distance from one point. NOT "a round shape" — an egg is round. Insist on the distance wording, because every construction in the lesson comes straight out of it' },
    { term: 'Centre', def: 'the one point everything is measured from. Where the compass needle goes' },
    { term: 'Radius', def: 'the fixed distance from the centre to the circle. What the compass is set to. Plural: radii' },
    { term: 'Arc', def: 'a piece of a circle. What you actually draw in a construction — students want to draw whole circles, and the arcs are cleaner' },
    { term: 'Chord', def: 'a straight segment joining two points on a circle. Not needed to do the construction, but it is what the grey lines are in the last diagram, so name it if asked' },
    { term: 'Collinear', def: 'lying on one straight line. The exception to the three-point rule, and the word is worth having: "in a line" gets confused with "in a queue"' },
    { term: 'Equidistant', def: 'the same distance from two or more things. The perpendicular bisector is the set of points equidistant from A and B, and that sentence IS the reason the construction works' },
    { term: 'Perpendicular bisector', def: 'the line that cuts a segment in half at a right angle. Both halves of the name do work: bisector = halves it, perpendicular = squarely. Met in 1.2 on the mirrors, built here with no numbers' },
    { term: 'Construction', def: 'a drawing made with compass and straight edge only — no measuring, no protractor. The arcs are the evidence, which is why they are never rubbed out' },
    { term: 'Circumcentre', def: 'the centre of the circle through three points; where their perpendicular bisectors meet. Name it at slide 21 for students who will meet it again in a triangle-geometry course' },
  ],
  timeline: [
    { time: '0–4 min', phase: 'Starter and the hook', detail: 'Title slide: three well-spread dots on a clean page, compass and ruler out. Then slide 2 — show London, Rome and Warsaw, let the class look at three unremarkable dots, and only then press the button. The circle DRAWS ITSELF around through all three; that sweep is the hook, so do not press it while anyone is still finding a pencil. Slide 3 does it again with Paris, Berlin and Rome. Say "Rome is on both" out loud.' },
    { time: '4–10 min', phase: 'The conspiracy', detail: 'Slide 4 asks why, in pairs, with nothing on the board. Take every answer seriously — rivers, ports, a day\'s ride, empires, deliberate planning — and write them up. Then push once: WHICH of these could be tested? Slide 5 makes them commit in writing, in a box, with a confidence score out of 10. That written answer is the whole reason the lesson closes the way it does, so do not let anyone skip it.' },
    { time: '10–24 min', phase: 'The map activity', detail: 'Hand out the printed map. Slides 6–7. Students pick any three cities and draw the circle through them BY EYE, guessing the centre and swinging until it fits, three times in three colours. They have no method yet and that is deliberate — resist every urge to teach the construction here. Circulate and ask "how do you know where the centre goes?" and let the answer be a shrug. Slide 8 counts the room: everybody succeeded roughly, nobody exactly, and the real question arrives — was that luck?' },
    { time: '24–32 min', phase: 'Three points determine a circle', detail: 'Slide 9 counts circles as dots go in: one dot, endless; two dots, still endless; three, exactly one. Copy the rule. Slide 10 sets it beside 1.2 — two points determine a LINE, three determine a CIRCLE — and names the shape of the argument: this many is exactly enough to leave you no choice. That parallel is worth thirty seconds; it is the same idea twice.' },
    { time: '32–40 min', phase: 'The exception', detail: 'Slide 11 is a question slide: find three points with NO circle through them. Give it a full two minutes and let them fail first — most classes get there by drawing sillier and sillier flat circles. Slide 12 gives the proof rather than the assertion: lay a ruler across any circle and it cuts in two places, never three. Copy the word COLLINEAR. The reveal ties it back to the sheet on their desk — Madrid, Paris and Amsterdam are very nearly in a line, and their circle is enormous.' },
    { time: '40–52 min', phase: 'What a circle is, and the compass', detail: 'Slide 13: define it properly, and refuse "round" — an egg is round. Copy circle / centre / radius (Draw This). Slide 14 is the one that makes the compass make sense: the needle holds the centre, the hinge locks the radius, so the pencil has no other path available. The tool IS the definition. Slide 15 is practical and matters more than it looks — set the radius against a ruler, hold the HEAD not the legs, turn the PAPER not the compass. Then the reveal: five points measured back to the needle hole should all read 4 cm.' },
    { time: '52–66 min', phase: 'The perpendicular bisector, with no numbers', detail: 'Slide 16 calls back to the mirror task in 1.2, where they built one with a tape measure and a slope multiplying to −1; today it is two arcs and a ruler, and it is exact rather than careful. Slide 17 is the idea — the line of places equally far from A and from B (copy, Draw This). Slide 18 is the construction, done live on their own pages: the compass setting must be WIDER than half of AB and must not be touched between the two arcs. Slide 19 is the proof and it is short: same setting, so PA = PB and QA = QB, and two points determine a line.' },
    { time: '66–76 min', phase: 'The payoff', detail: 'Slide 20 poses it as a question before the method: you can find every point equally far from TWO points — how do you get one that is equally far from three? Let them say "do it twice". Slide 21 is the construction and the copy-down method, with the reveal explaining what goes wrong for collinear points: the two bisectors come out parallel. That is the same exception arriving from a completely different direction, and it is worth pointing at. Slide 22 sends them back to the map to do one properly and compare it with their eyeball circle.' },
    { time: '76–80 min', phase: 'Closing the conspiracy', detail: 'Slide 23. Everyone reads out the answer they boxed at slide 5 and marks it themselves. The answer is that cities do not sit on circles for any reason: ANY three places that are not in a line do. The copy-down is the transferable bit — a pattern that always happens tells you nothing about the thing you found it in. Then the recap checklist and the homework. If time is short, cut slide 22 (they can do it for homework) — do NOT cut slide 23.' },
  ],
  answers: [
    { q: 'Slide 4: why do cities keep landing on circles?', a: 'There is no right answer at this point and that is the design. Collect everything: rivers, ports, defensible ground, a day\'s travel apart, empire borders, deliberate planning. The one follow-up worth making is which of these could be TESTED — most cannot, which is a useful thing to notice before slide 23 shows that the question itself was faulty.' },
    { q: 'Slide 8: did anybody fail to find a circle?', a: 'No team will have failed, and no team will have been exact. Both halves matter: the universal success is the clue that something is forced rather than lucky, and the universal inexactness is what makes the compass construction worth learning.' },
    { q: 'Slide 11: which three points have no circle?', a: 'Three points on one straight line. Expect students to describe it before they can name it — "when they are all in a row" is the right answer and COLLINEAR is just the word for it.' },
    { q: 'Slide 12: why can\'t collinear points work?', a: 'A straight line meets a circle at most twice. It can cross twice, touch once (a tangent), or miss entirely — but there is no way to get three crossings. So three points on a line can never all be on one circle.' },
    { q: 'Slide 12 reveal: is that on the map?', a: 'Madrid, Paris and Amsterdam are very nearly collinear on this projection. A circle does exist through them, but its centre is far off the sheet and the arc across Europe looks straight. The nearer to collinear three places are, the further the centre runs and the flatter the arc — which is exactly what "no circle at all" looks like as you approach it.' },
    { q: 'Slide 15 reveal: checking your own circle', a: 'Five points marked anywhere on a 4 cm circle should each measure 4 cm back to the needle hole. Any reading that is out means the hinge moved part-way round — which is the definition failing, not the student failing.' },
    { q: 'Slide 18: why must the compass be wider than half of AB?', a: 'If it is set to less than half of AB, the two arcs never reach each other and there is nothing to cross. Exactly half gives one touching point, which is not enough to draw a line through. Anything more gives the two crossings the construction needs.' },
    { q: 'Slide 19: why are two arcs enough?', a: 'The setting did not change between them, so P is the same distance from A as from B, and so is Q. Both are therefore on the line of points equidistant from A and B. Two points determine a line (1.2), so PQ IS that line. No measuring is involved anywhere, which is why the result is exact rather than careful.' },
    { q: 'Slide 20: how do you find a point equally far from three?', a: 'Do the two-point version twice and intersect. Equally far from A and B is one line; equally far from B and C is another; a point on both is equally far from all three. Accept "do it twice and see where they cross" — that is the whole construction.' },
    { q: 'Slide 21 reveal: what if the points are collinear?', a: 'The two perpendicular bisectors come out parallel — both are perpendicular to the same line — so they never cross and there is no centre. The construction fails in exactly the case the geometry said it must.' },
    { q: 'Homework 1: perpendicular bisector of a 12 cm segment', a: 'Both halves measure 6 cm and the crossing is square. The mark here is for the arcs still being on the page: a bisector drawn by measuring 6 cm with a ruler is the right line obtained the wrong way, and should be sent back.' },
    { q: 'Homework 2: circle through A(1, 1), B(7, 3), C(3, 7)', a: 'Centre (3.5, 3.5); radius = √12.5 = 2.5√2 ≈ 3.54 units. Check all three: A is √(2.5² + 2.5²), B is √(3.5² + 0.5²), C is √(0.5² + 3.5²) — all √12.5. A construction that lands within about 2 mm of (3.5, 3.5) is a good one.' },
    { q: 'Homework 3: D(0, 2), E(2, 3), F(6, 5)', a: 'They are COLLINEAR — every step is 1 up for 2 across, so the slope from D to E and from E to F is 1/2 both times. The two perpendicular bisectors come out parallel, never cross, and there is no circle. Students who quietly force a circle anyway have not read their own drawing; the parallel bisectors are the evidence.' },
    { q: 'Homework 4: centre outside the triangle', a: 'Any obtuse triangle does it — the circumcentre falls outside, on the far side of the longest side. E.g. (0, 0), (10, 0), (9, 2). A right triangle is the boundary case: the centre lands exactly ON the longest side, at its midpoint, which is the fact the mirror task in 1.2 finished with.' },
    { q: 'Exit question: where are the centres of all the circles through A and B?', a: 'On the perpendicular bisector of AB — three words, and they already had it at slide 17. Every such centre must be the same distance from A and from B, and that set of points is exactly the perpendicular bisector. It also re-explains slide 9: two points leave endless circles because the centre is free to slide anywhere along that line, and the third point is what nails it down to one place.' },
  ],
  notes:
    'THE DECK IS ONE JOKE, TOLD SLOWLY, AND THE JOKE IS THE LESSON. It opens with a conspiracy — three major cities on a perfect circle, then three more — and closes forty minutes later ' +
    'with the reason: any three places that are not in a straight line do that. The pattern was real and meant nothing. Slide 5 (write your explanation in a box, score your confidence) and ' +
    'slide 23 (read it back and mark yourself) are the two ends of that arc. If you cut either one, the rest of the deck is still a competent geometry lesson and stops being a good one. ' +
    'THE ACTIVITY COMES BEFORE THE METHOD, ON PURPOSE. Slides 6–7 have students drawing circles through cities by eye, with no construction available. Every instinct will say to teach the ' +
    'compass first. Do not: the point is that everybody succeeds roughly and nobody succeeds exactly, so when the construction arrives at slide 18 it is the answer to a question the class ' +
    'has already asked out loud. Slide 22 sends them back to the same sheet to do one properly, and the comparison between the two circles is the assessment. ' +
    'THE MAP IS HONEST. It is a public-domain equirectangular crop at a uniform 30 pixels per degree in both directions, which is why a circumcircle drawn on it is an actual circle rather ' +
    'than an ellipse. The overlaid circles are the exact circumcircles of the plotted cities, computed rather than eyeballed (see images/CREDITS.json for the coordinates). If a student asks ' +
    'whether the circle would still be a circle on a globe: no, and that is a genuinely good question — on a sphere the shortest path between the cities is not what the map shows either. The ' +
    'honest answer is that we are doing plane geometry on a picture, and the picture is the plane. ' +
    'CHECK THE COMPASSES THE DAY BEFORE. A loose hinge does not just make the construction inaccurate, it makes the lesson\'s central claim false in front of the class — the whole argument on ' +
    'slide 14 is that the gap CANNOT change. Have spares. Sharpen the pencils; 2 mm of blunt point is more error than the eyeball method they are supposed to be improving on. ' +
    'THE ERROR TO WATCH FOR IN THE CONSTRUCTION is changing the compass setting between the arc from A and the arc from B. It produces two crossings and a perfectly straight line that is not ' +
    'the bisector, and it looks completely convincing. If a bisector does not cut AB in half, that is what happened. Second error: opening the compass to less than half of AB, so the arcs never ' +
    'meet — students then draw the line "where they would have met", which is guessing again. ' +
    'DERIVE, DON\'T ASSERT (the standing rule for this course). Every rule in this deck is argued for: three points determine a circle is reached by counting circles as dots go in; the collinear ' +
    'exception is proved from a line meeting a circle at most twice, and then AGAIN from the bisectors coming out parallel; the compass is shown to be the definition rather than a gadget; and ' +
    'the two-arc construction is justified in one line from the fixed setting plus "two points determine a line" from 1.2. If time runs short, cut a practice slide, not a derivation. ' +
    'CONTINUITY WITH 1.2. The mirror task at the end of 1.2 had students construct a perpendicular bisector using slopes and a multiplication that came to −1. This lesson builds the same object ' +
    'with no arithmetic at all, and that contrast is worth naming out loud at slide 16 — the numerical method needed measurements and was therefore only as good as the tape measure, while the ' +
    'construction is exact. The exit question here also answers a loose end from 1.2: the centres of all circles through two points lie on their perpendicular bisector. ' +
    'ON LAYOUT, FOR ANYONE EDITING THIS DECK: showcase, steps, compare and gallery silently DROP a slide-level notes array — nothing errors, the panel just never renders. Every copy-down item ' +
    'here is therefore on a split, statement, callout or stack, or is an orange ">" bumper inside a steps slide\'s content. Check that before moving a note between slides. ' +
    'The course is flagged bilingual:false in content/courses.js, so this deck is English-only and the EN/VN toggle is hidden. The English is written short for a class whose first language is ' +
    'Vietnamese, but the vocabulary is not softened — collinear, equidistant, perpendicular bisector and construction all get named properly, because a nickname now is a debt later. ' +
    'WHAT COMES NEXT: this lesson gives the circle a definition, a centre and a radius, and a construction — but no equation. The natural follow-on is the circle in coordinates, ' +
    '(x − h)² + (y − k)² = r², which is nothing more than the distance formula from 1.1 with the distance held fixed at r. Slide 13 is the hinge for that: "all the points a fixed distance ' +
    'from one point" is already the equation, written in English.',
}
