// content/y7-science/U01_4/plan.js
// One-page teacher lesson plan, rendered by src/pages/Plan.jsx.
export const plan = {
  duration: '50 minutes',
  objective:
    'Students can define tissue, organ, organ system and organism; give an animal and a plant example of a tissue (ciliated epithelium, onion epidermis) and of an organ (heart, leaf); name five human organs and locate them on their own body; name the organs of the breathing and digestive systems and state the job each system shares; and put a single real example on all five rungs of the ladder from cell to organism.',
  materials: [
    'Projector / TV for the lesson deck',
    'Student science notebooks',
    'Rulers — the five-level ladder is ruled up in class, so everyone needs one',
    'Learner’s Book (Unit 1.4, pages 22–25)',
    'Mini whiteboards + markers for the X-ray spot and the fingers-up drill',
    'Optional but worth it: one real onion, cut in half, so they can peel the epidermis off with their fingers',
  ],
  vocab: [
    { term: 'Tissue', def: 'a group of similar cells, all working together to carry out one particular function' },
    { term: 'Organ', def: 'a structure made of several different tissues, working together' },
    { term: 'Organ system', def: 'a set of organs that all work together to carry out the same function' },
    { term: 'Organism', def: 'a living thing; it may contain many organ systems, organs and tissues' },
    { term: 'Ciliated epithelium', def: 'the animal tissue lining the tubes to the lungs; its cilia sweep mucus, dust and germs away from the lungs' },
    { term: 'Epithelium', def: 'a tissue that covers a surface — worth saying out loud, it demystifies the long word' },
    { term: 'Onion epidermis', def: 'the plant tissue, one cell thick, covering the surface of each layer inside an onion' },
    { term: 'Upper / lower epidermis', def: 'the flat protective tissues on the top and bottom of a leaf' },
    { term: 'Palisade layer', def: 'the tall chloroplast-packed tissue near the top of a leaf, where photosynthesis happens' },
    { term: 'Spongy layer', def: 'the loose tissue below it, with air gaps that let gases move through the leaf' },
    { term: 'Gullet / windpipe', def: 'oesophagus (food, to the stomach) / trachea (air, to the lungs) — two tubes students routinely confuse' },
  ],
  timeline: [
    { time: '0–5 min', phase: 'Starter — Getting started, p.22', detail: 'Title slide. They draw a body outline and sketch and label brain, heart, stomach, intestine and lungs. Four minutes, rough drawing is fine — do not let this become an art lesson. Circulate and look at where they put the stomach.' },
    { time: '5–8 min', phase: 'Check it, then stand up', detail: 'Slide 2 shows a good version. The two common errors are the stomach drawn far too low and the intestines drawn far too small. Then everyone stands and points to each organ ON THEMSELVES as you name it. Sixty seconds, and it wakes the room up.' },
    { time: '8–13 min', phase: 'The hook — ask, do not tell', detail: 'Slide 3 is ONE ciliated cell, alone in a big white field, with no answer anywhere on the slide. They drew this cell last lesson. Could one of them keep your lungs clean? Two minutes in pairs, take two answers. Slide 4 pays it off — millions, joined edge to edge, all beating together. Copy the definition of TISSUE.' },
    { time: '13–19 min', phase: 'Two tissues, one animal one plant', detail: 'The trachea micrograph (the real ciliated epithelium) with Question 1 behind the reveal. Then the onion epidermis, drawn, and the compare slide: a cut onion beside the same skin magnified. If you brought an onion, this is the moment — let two students peel the epidermis off. The point being made three times: same kind of cell, joined edge to edge, one job.' },
    { time: '19–23 min', phase: 'The English — Question 2', detail: 'The everyday "a tissue" (a paper handkerchief, countable) against the scientific "tissue" (a group of cells, uncountable). They write TWO SENTENCES OF THEIR OWN, one for each meaning. The reveal has examples — show it only if they are stuck, and tell them not to copy it. This is the biggest English moment in the unit; give it the full four minutes.' },
    { time: '23–31 min', phase: 'Up a rung — the organ', detail: 'Slide 9 asks how many kinds of tissue are in ONE leaf, with no answer on it — take numbers, hands up. Slide 10 answers: four. Copy the definition of ORGAN. Then the real leaf section (match the four layers to the drawing), then the chest X-ray: find the lungs, the heart shadow, and the stomach gas bubble. Whiteboards: which starter organ can you NOT see? (The brain — it is outside the picture.)' },
    { time: '31–38 min', phase: 'The last two rungs + the relay', detail: 'Slide 13 asks how oxygen gets from the lungs to a big toe — no answer on the slide. Then the compare: breathing system and digestive system, each a SET of organs with one shared job. Copy ORGAN SYSTEM and ORGANISM together (two lines, one panel). Then the organ relay in groups of four: one organ each, out loud, in English, no repeats. Ninety seconds. The reveal has the ones they miss — including skin.' },
    { time: '38–43 min', phase: 'Draw This — the five levels', detail: 'The ladder: ciliated cell → ciliated epithelium → a lung → the breathing system → you. Rulers out. It is placed here, at the end, on purpose: by now all four words exist, so ruling it up is recall rather than dictation. Five boxes, four arrows, the orange word and the example in each.' },
    { time: '43–47 min', phase: 'The fingers-up drill', detail: 'The Level Drill widget. One item at a time; the whole class holds up 1 to 5 fingers; you press the button only when every hand is up. Twelve items. Watch for the two deliberate traps — a leaf (organ, not tissue) and the palisade layer (tissue, not organ). Skip the last few if you are short of time; it is designed to be cut.' },
    { time: '47–50 min', phase: 'Q3, recap + homework', detail: 'Question 3 is run as a hunt, not a copy: say each answer aloud and point to where you wrote it today. Then the six-point checklist and the copy-count. Set homework: read pp.22–25 and Activity 1.4.1 (one organ system, large labelled drawing, names in English). Exit question: a jellyfish has no heart, lungs or brain — which level can a living thing manage without?' },
  ],
  answers: [
    { q: 'Starter — where the five organs actually go', a: 'Brain: filling the skull. Lungs: either side of the chest, from about the collarbone to the bottom of the ribs. Heart: BETWEEN the lungs, slightly left of centre — not on the far left, which is the usual drawing. Stomach: just under the left ribs, higher than nearly everyone draws it. Intestines: filling almost the whole abdomen below the stomach.' },
    { q: 'Slide 3 — could one ciliated cell keep your lungs clean?', a: 'No. One cell sweeps one tiny spot; the airway is a tube many centimetres long. It takes millions of them, joined edge to edge, beating in the same direction at the same time. Do not give this away — take guesses and move to slide 4.' },
    { q: 'Tissue', a: 'A group of SIMILAR cells, all working together to carry out one particular function. The word doing the work is "similar" — if the cells are different kinds, it is an organ, not a tissue.' },
    { q: 'Q1 (p.23) — the function of ciliated epithelium', a: 'To keep the airways clean: the cilia sweep mucus, with the dust and germs trapped in it, up and away from the lungs. Accept anything that gets "sweeps mucus / dirt away from the lungs".' },
    { q: 'Q2 (p.23) — the two meanings of "tissue"', a: 'Everyday: a paper handkerchief — countable ("a tissue", "two tissues"). Scientific: a group of similar cells — usually uncountable ("muscle tissue", not "a muscle tissue"). Sample sentences: "Mr Bowen sneezed, so he took a tissue out of the box." / "The wall of the stomach contains muscle tissue." Mark the SENTENCE, not just the word — full sentence, capital letter, full stop.' },
    { q: 'Slide 9 — how many kinds of tissue in one leaf?', a: 'Four: upper epidermis, palisade layer, spongy layer, lower epidermis. Most classes guess one or two. That gap is the whole point of the organ definition.' },
    { q: 'Organ', a: 'A structure made of several DIFFERENT tissues, working together. Human examples: brain, heart, stomach, lungs, skin. Plant examples: leaves, roots, flowers.' },
    { q: 'The four leaf tissues and their jobs', a: 'Upper epidermis — a flat protective skin on top. Palisade layer — tall cells packed with chloroplasts, where most photosynthesis happens. Spongy layer — loose round cells with air gaps, letting gases move about. Lower epidermis — the protective skin underneath.' },
    { q: 'X-ray — which starter organ can you not see?', a: 'The brain: this is a chest X-ray, so the head is not in the picture. If a student says "the stomach", point out the black gas bubble at the bottom left — that IS the top of the stomach. Accept "the intestines" too; they are below the frame.' },
    { q: 'Slide 13 — how does oxygen reach your big toe?', a: 'It passes from the lungs into the BLOOD, and the HEART pumps that blood through blood vessels to the toe. That is a second organ system (the circulatory system) — worth naming, and it is one of the four they can choose for homework.' },
    { q: 'Organ system / organism', a: 'Organ system: a set of organs that all work together to carry out the same function. Organism: a living thing, which may contain many organ systems, organs and tissues.' },
    { q: 'The two systems on the compare slide', a: 'Breathing (respiratory): nose and mouth, windpipe, lungs — shared job, getting oxygen into the body. Digestive: mouth, gullet, stomach, intestines — shared job, breaking food down and taking it into the body.' },
    { q: 'Organ relay — organs groups usually miss', a: 'liver, kidneys, skin, eyes, ears, tongue, bones, muscles, bladder, pancreas. Skin is the one worth stopping on: it is an organ, and it is the largest one they have.' },
    { q: 'Q3 (p.24) — copy and complete', a: 'a. tissue · b. organ · c. organ system · d. organism. Run it as a hunt — all four are already in their notebooks from today. Anyone who cannot point to one has found their own homework.' },
    { q: 'Widget — the twelve items', a: 'a red blood cell = cell · ciliated epithelium = tissue · the heart = organ · a leaf = ORGAN (trap) · the digestive system = organ system · a cat = organism · the palisade layer = TISSUE (trap) · a root hair cell = cell · the stomach = organ · onion epidermis = tissue · the breathing system = organ system · Mr Bowen = organism.' },
    { q: 'Exit question — the jellyfish', a: 'The ORGAN SYSTEM level, and arguably the organ level too: a jellyfish has cells and tissues, but no heart, lungs or brain, and no organ systems in the way we do. So the ladder is not a rule every organism obeys — the bottom two rungs are, and the top rungs are how COMPLEX organisms are built. Accept any answer that spots a living thing can exist without organ systems.' },
  ],
  notes:
    'The spine is ONE LADDER climbed ONCE, with the same example on every rung: ciliated cell → ciliated epithelium → a lung → the breathing system → you. That cell is not new — they drew it in 1.3 — so this lesson is not five new ideas, it is one familiar cell walked upwards. Say that out loud at the ladder slide; it is what makes the whole thing feel small. ' +
    'WHAT GETS COPIED, and nothing else: four definitions (tissue; organ; organ system + organism together), two sentences of their own for Question 2, and the five-level ladder. That is it. Question 3 in the book says "copy and complete", but those four sentences ARE the four definitions — copying them again would be writing every fact twice, so it is run as a hunt through their own notes instead. If you find yourself dictating the same fact twice, stop. ' +
    'THIS DECK IS DELIBERATELY MORE ACTIVE THAN 1.3. Seven times the class stops writing and does something: the starter drawing, standing up and pointing to five organs on themselves, the paired argument at the hook, writing two sentences of their own English, spotting organs on the X-ray, the round-the-group organ relay, and the fingers-up drill. The longest unbroken stretch of copying is a single definition. If you are running late, the things to cut are widget items (it is built to stop anywhere) and the organ relay — NOT the Question 2 writing, which is the lesson\'s real English work. ' +
    'THREE SLIDES HAVE NO ANSWER ON THEM ON PURPOSE: slide 3 (could one cell keep your lungs clean?), slide 9 (how many tissues in one leaf?) and slide 13 (how does oxygen reach your toe?). Let them guess wrong. The gap between the guess and the next slide is where the lesson happens. ' +
    'THE TRAP WORTH PLANNING FOR is "similar" versus "different". A tissue is similar cells; an organ is different tissues. Students who have half-learned it will call a leaf a tissue and the palisade layer an organ — both of those are in the widget on purpose. When it comes up, go back to the leaf diagram and count the four layers. ' +
    'THE ENGLISH BEAT is Question 2, and it is the best thing in this section of the book for this class: "a tissue" for your nose versus "muscle tissue" in your stomach wall. Countable versus uncountable is the real grammar point, and it is worth writing "a tissue / two tissues" but "muscle tissue" on the board. Mark full sentences. ' +
    'BRING AN ONION if you can. The onion epidermis is the one tissue in this lesson they can hold between their fingers, and peeling it off a cut onion takes ten seconds and lands the idea better than either picture. ' +
    'Homework is Activity 1.4.1 from the book (one organ system, researched, as a large labelled drawing). It cannot be done in class — it is a research task — so it is set as homework and their drawings are the way into 1.5. Ask for organ names in English. ' +
    'The p.25 "Cells discovery timeline" group project is a separate multi-lesson piece of work, NOT part of this lesson, and is deliberately not in the deck. ' +
    'Image sources and licences are in content/y7-science/U01_4/images/CREDITS.json — all openly licensed (PD / CC0 / CC BY / CC BY-SA). trachea.jpg and leaf.jpg are the same files used in 1.3, reused here at the tissue and organ level rather than the cell level.',
}
