// content/banks/y7-math/U01_6.js
// Maths 1.6 · Square roots and cube roots. Schema and house rules: bank.js.
//
// The traps are the deck's: 5² is 25, not 5 × 2; a root question can have a
// negative answer (∛125 − √49 = −2); and consecutive square numbers are next to
// each other in the list of squares, not one apart. The lists are the deck's
// too: squares up to 12², cubes up to 6³ and 10³, plus the deck's own 225 and
// 576. Roots are never negative, and the deck says "whole number", not
// "integer". Mr Bowen's square number between 100 and 200 is 144, but the deck
// and the Jeopardy board give the wrong reason: 169 and 196 are squares too.
export const QUESTIONS = [
  {
    id: 'm1.6-01',
    unit: '1.6',
    level: 1,
    kind: 'words',
    q: 'What is 9², and how do you say it out loud in English?',
    qVn: '9² bằng bao nhiêu, và đọc bằng tiếng Anh như thế nào?',
    a: '81, "nine squared"',
    aVn: '81, đọc là "nine squared"',
    why: '9² means 9 × 9.',
    whyVn: '9² nghĩa là 9 × 9.',
    source: 'jeopardy unit1-finale · Squares & Roots 100',
    check: '9 ** 2',
  },
  {
    id: 'm1.6-02',
    unit: '1.6',
    level: 1,
    kind: 'words',
    q: 'How do you say 2³ out loud in English? Then work it out.',
    qVn: 'Đọc 2³ bằng tiếng Anh như thế nào? Rồi tính nó.',
    a: '"two cubed". It is 8.',
    aVn: '"two cubed". Bằng 8.',
    why: '2³ = 2 × 2 × 2. The small 3 means three 2s multiplied together.',
    whyVn: '2³ = 2 × 2 × 2. Số 3 nhỏ nghĩa là ba số 2 nhân với nhau.',
    source: 'deck 1.6 s11',
    check: '2 ** 3',
  },
  {
    id: 'm1.6-03',
    unit: '1.6',
    level: 1,
    kind: 'words',
    q: 'What is the cube root of 125?',
    qVn: 'Căn bậc ba của 125 là bao nhiêu?',
    a: '5',
    aVn: '5',
    why: '5 × 5 × 5 = 125.',
    whyVn: '5 × 5 × 5 = 125.',
    source: 'deck 1.6 s13',
    check: 'cbrt(125)',
  },
  {
    id: 'm1.6-04',
    unit: '1.6',
    level: 1,
    kind: 'words',
    q: 'Square 11.',
    qVn: 'Làm theo yêu cầu: "Square 11."',
    a: '121',
    aVn: '121',
    why: '"Square" here means multiply it by itself: 11 × 11.',
    whyVn: '"Square" ở đây nghĩa là nhân số đó với chính nó: 11 × 11.',
    source: 'hw04 A3.1',
    check: '11 ** 2',
  },
  {
    id: 'm1.6-05',
    unit: '1.6',
    level: 1,
    kind: 'calc',
    q: 'Work out ∛1000.',
    qVn: 'Tính ∛1000.',
    a: '10',
    aVn: '10',
    why: '10 × 10 × 10 = 1000.',
    whyVn: '10 × 10 × 10 = 1000.',
    source: 'q1rev A7d',
    check: 'cbrt(1000)',
  },
  {
    id: 'm1.6-06',
    unit: '1.6',
    level: 1,
    kind: 'words',
    q: 'Which of these is a square number: 24, 36 or 48?',
    qVn: 'Số nào là số chính phương: 24, 36 hay 48?',
    a: '36',
    aVn: '36',
    why: '6 × 6 = 36. 24 and 48 are not on the list of squares.',
    whyVn: '6 × 6 = 36. 24 và 48 không có trong bảng số chính phương.',
    source: 'deck 1.6 s5 (adapted)',
    check: '[24, 36, 48].filter((n) => Number.isInteger(sqrt(n)))',
  },
  {
    id: 'm1.6-07',
    unit: '1.6',
    level: 2,
    kind: 'calc',
    q: 'Which is bigger, 5² or 5 × 2? Work out both.',
    qVn: 'Số nào lớn hơn, 5² hay 5 × 2? Hãy tính cả hai.',
    a: '5² = 25 is bigger',
    aVn: '5² = 25 lớn hơn',
    why: '5 × 2 = 10. The small 2 counts how many 5s. It does not double.',
    whyVn: '5 × 2 = 10. Số 2 nhỏ cho biết có bao nhiêu số 5. Nó không nhân đôi.',
    source: 'jeopardy unit1-finale · Squares & Roots 200',
    check: '5 ** 2',
  },
  {
    id: 'm1.6-08',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: '64 is a square number and a cube number. What is its square root, and what is its cube root?',
    qVn: '64 vừa là số chính phương vừa là số lập phương. Căn bậc hai của nó là bao nhiêu, và căn bậc ba của nó là bao nhiêu?',
    a: 'Square root 8, cube root 4',
    aVn: 'Căn bậc hai là 8, căn bậc ba là 4',
    why: '8 × 8 = 64 and 4 × 4 × 4 = 64.',
    whyVn: '8 × 8 = 64 và 4 × 4 × 4 = 64.',
    source: 'jeopardy unit1-finale · Squares & Roots 300',
    check: '[sqrt(64), cbrt(64)]',
  },
  {
    id: 'm1.6-09',
    unit: '1.6',
    level: 2,
    kind: 'calc',
    q: 'Work out √81 + ∛8.',
    qVn: 'Tính √81 + ∛8.',
    a: '11',
    aVn: '11',
    why: '9 + 2 = 11.',
    whyVn: '9 + 2 = 11.',
    source: 'deck 1.6 s23',
    check: 'sqrt(81) + cbrt(8)',
  },
  {
    id: 'm1.6-10',
    unit: '1.6',
    level: 2,
    kind: 'calc',
    q: 'Work out 4² + 7².',
    qVn: 'Tính 4² + 7².',
    a: '65',
    aVn: '65',
    why: '16 + 49 = 65.',
    whyVn: '16 + 49 = 65.',
    source: 'WB 1.6 ex 1 (adapted)',
    check: '4 ** 2 + 7 ** 2',
  },
  {
    id: 'm1.6-11',
    unit: '1.6',
    level: 2,
    kind: 'calc',
    q: 'Work out 2³ + 4³.',
    qVn: 'Tính 2³ + 4³.',
    a: '72',
    aVn: '72',
    why: '8 + 64 = 72.',
    whyVn: '8 + 64 = 72.',
    source: 'WB 1.6 ex 3 (adapted)',
    check: '2 ** 3 + 4 ** 3',
  },
  {
    id: 'm1.6-12',
    unit: '1.6',
    level: 2,
    kind: 'calc',
    q: '√▢ = 7. What number goes in the box?',
    qVn: '√▢ = 7. Số nào điền vào ô trống?',
    a: '49',
    aVn: '49',
    why: 'Go back the other way: 7 × 7 = 49.',
    whyVn: 'Đi ngược lại: 7 × 7 = 49.',
    source: 'WB 1.6 ex 6 (adapted)',
    check: '7 ** 2',
  },
  {
    id: 'm1.6-13',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: '49 and 64 are consecutive square numbers. What is the next square number after 64?',
    qVn: '49 và 64 là hai "consecutive square numbers". Số chính phương tiếp theo sau 64 là số nào?',
    a: '81',
    aVn: '81',
    why: '7², 8², 9². Not 65: consecutive squares are next to each other in the list.',
    whyVn: '7², 8², 9². Không phải 65: số chính phương liên tiếp đứng cạnh nhau trong bảng.',
    source: 'WB 1.6 ex 14 (adapted)',
    check: '9 ** 2',
  },
  {
    id: 'm1.6-14',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: '27 and 64 are consecutive cube numbers. What is the next cube number after 64?',
    qVn: '27 và 64 là hai "consecutive cube numbers". Số lập phương tiếp theo sau 64 là số nào?',
    a: '125',
    aVn: '125',
    why: '3³, 4³, 5³. 5 × 5 × 5 = 125.',
    whyVn: '3³, 4³, 5³. 5 × 5 × 5 = 125.',
    source: 'WB 1.6 ex 15 (adapted)',
    check: '5 ** 3',
  },
  {
    id: 'm1.6-15',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: 'Is 25 a cube number?',
    qVn: '25 có phải là số lập phương không?',
    a: 'No',
    aVn: 'Không',
    why: '2³ = 8 and 3³ = 27, so no whole number cubed makes 25. It is a square number.',
    whyVn: '2³ = 8 và 3³ = 27, nên không có số nguyên nào lập phương lên bằng 25. Nó là số chính phương.',
    source: 'q1rev A7g (adapted)',
    check: 'yes(Number.isInteger(cbrt(25)))',
  },
  {
    id: 'm1.6-16',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen grows cube watermelons. They stack better. A crate holds 3 along, 3 across and 3 high. How many watermelons fit in one crate?',
    qVn: 'Thầy Bowen trồng dưa hấu hình lập phương. Xếp chồng dễ hơn. Một thùng chứa 3 quả chiều dài, 3 quả chiều rộng và 3 quả chiều cao. Một thùng chứa được bao nhiêu quả dưa?',
    a: '27 watermelons',
    aVn: '27 quả dưa',
    why: '3 × 3 × 3 = 27. They are real: farmers in Japan grow them in glass boxes.',
    whyVn: '3 × 3 × 3 = 27. Loại dưa này có thật: nông dân Nhật Bản trồng chúng trong hộp kính.',
    source: 'deck 1.6 s19',
    check: '3 ** 3',
  },
  {
    id: 'm1.6-17',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen lays 225 stones in a perfect square. How many stones run along one side?',
    qVn: 'Thầy Bowen lát 225 viên gạch thành một hình vuông hoàn hảo. Mỗi cạnh có bao nhiêu viên gạch?',
    a: '15 stones',
    aVn: '15 viên',
    why: '15 × 15 = 225, so √225 = 15.',
    whyVn: '15 × 15 = 225, nên √225 = 15.',
    source: 'deck 1.6 s2',
    check: 'sqrt(225)',
  },
  {
    id: 'm1.6-18',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: 'A large cube is built from 216 small cubes. How many small cubes are there along one edge?',
    qVn: 'Một khối lập phương lớn được xếp từ 216 khối lập phương nhỏ. Mỗi cạnh có bao nhiêu khối nhỏ?',
    a: '6',
    aVn: '6',
    why: '6 × 6 × 6 = 216, so ∛216 = 6.',
    whyVn: '6 × 6 × 6 = 216, nên ∛216 = 6.',
    source: 'hw05 D1.4b',
    check: 'cbrt(216)',
  },
  {
    id: 'm1.6-19',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: 'Find all the square numbers between 20 and 50.',
    qVn: 'Tìm tất cả các số chính phương nằm giữa 20 và 50.',
    a: '25, 36 and 49',
    aVn: '25, 36 và 49',
    why: '5², 6² and 7². 4² = 16 is too small, and 8² = 64 is too big.',
    whyVn: '5², 6² và 7². 4² = 16 quá nhỏ, còn 8² = 64 quá lớn.',
    source: 'WB 1.6 ex 11a (adapted)',
    check: 'ints(20, 50).filter((n) => Number.isInteger(sqrt(n)))',
  },
  {
    id: 'm1.6-20',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: 'True or false: the square root of 36 is 18.',
    qVn: 'Đúng hay sai: căn bậc hai của 36 là 18.',
    a: 'False',
    aVn: 'Sai',
    why: '√36 = 6, because 6 × 6 = 36. A square root is not half.',
    whyVn: '√36 = 6, vì 6 × 6 = 36. Căn bậc hai không phải là chia đôi.',
    source: 'deck 1.6 s8 (adapted)',
    check: 'tf(sqrt(36) === 18)',
  },
  {
    id: 'm1.6-21',
    unit: '1.6',
    level: 2,
    kind: 'words',
    q: 'Which of these is a cube number: 9, 16, 27 or 36?',
    qVn: 'Số nào là số lập phương: 9, 16, 27 hay 36?',
    a: '27',
    aVn: '27',
    why: '3 × 3 × 3 = 27. The others are square numbers.',
    whyVn: '3 × 3 × 3 = 27. Các số còn lại là số chính phương.',
    source: 'deck 1.6 s12 (adapted)',
    check: '[9, 16, 27, 36].filter((n) => Number.isInteger(cbrt(n)))',
  },
  {
    id: 'm1.6-22',
    unit: '1.6',
    level: 3,
    kind: 'words',
    q: 'The square root of 45 lies between which two consecutive whole numbers?',
    qVn: 'Căn bậc hai của 45 nằm giữa hai số nguyên liên tiếp (consecutive) nào?',
    a: '6 and 7',
    aVn: '6 và 7',
    why: '36 < 45 < 49, and √36 = 6, √49 = 7.',
    whyVn: '36 < 45 < 49, và √36 = 6, √49 = 7.',
    source: 'jeopardy unit1-finale · Squares & Roots 400',
    check: 'between(sqrt(45))',
  },
  {
    id: 'm1.6-23',
    unit: '1.6',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen is thinking of a square number between 100 and 200. Its square root is a multiple of 3. What is his number?',
    qVn: 'Thầy Bowen đang nghĩ đến một số chính phương nằm giữa 100 và 200. Căn bậc hai của nó là bội số của 3. Con số đó là bao nhiêu?',
    a: '144',
    aVn: '144',
    why: '121, 144, 169 and 196 are squares; only 144 has a root (12) that is a multiple of 3.',
    whyVn: '121, 144, 169 và 196 là số chính phương; chỉ có 144 có căn (12) là bội số của 3.',
    source: 'jeopardy unit1-finale · Squares & Roots 500',
    check: 'ints(100, 200).filter((n) => Number.isInteger(sqrt(n)) && sqrt(n) % 3 === 0)',
  },
  {
    id: 'm1.6-24',
    unit: '1.6',
    level: 3,
    kind: 'calc',
    q: 'Work out 6² + 3³.',
    qVn: 'Tính 6² + 3³.',
    a: '63',
    aVn: '63',
    why: '36 + 27 = 63. 3³ is 3 × 3 × 3, not 3 × 3.',
    whyVn: '36 + 27 = 63. 3³ là 3 × 3 × 3, không phải 3 × 3.',
    source: 'hw05 C4i',
    check: '6 ** 2 + 3 ** 3',
  },
  {
    id: 'm1.6-25',
    unit: '1.6',
    level: 3,
    kind: 'calc',
    q: 'Work out ∛125 − √49.',
    qVn: 'Tính ∛125 − √49.',
    a: '−2',
    aVn: '−2',
    why: '5 − 7 = −2. The answer to a root question can be negative.',
    whyVn: '5 − 7 = −2. Đáp án của một bài về căn vẫn có thể là số âm.',
    source: 'deck 1.6 s14',
    check: 'cbrt(125) - sqrt(49)',
  },
  {
    id: 'm1.6-26',
    unit: '1.6',
    level: 3,
    kind: 'words',
    q: '∛50 lies between which two consecutive whole numbers?',
    qVn: '∛50 nằm giữa hai số nguyên liên tiếp (consecutive) nào?',
    a: '3 and 4',
    aVn: '3 và 4',
    why: '27 < 50 < 64, so use the list of cubes. Not 7 and 8.',
    whyVn: '27 < 50 < 64, nên dùng bảng số lập phương. Không phải 7 và 8.',
    source: 'hw04 A4d',
    check: 'between(cbrt(50))',
  },
  {
    id: 'm1.6-27',
    unit: '1.6',
    level: 3,
    kind: 'words',
    q: 'Two consecutive square numbers add up to 61. Which two?',
    qVn: 'Hai "consecutive square numbers" cộng lại bằng 61. Đó là hai số nào?',
    a: '25 and 36',
    aVn: '25 và 36',
    why: '5² + 6² = 25 + 36 = 61. Consecutive squares are next to each other in the list.',
    whyVn: '5² + 6² = 25 + 36 = 61. Số chính phương liên tiếp đứng cạnh nhau trong bảng.',
    source: 'hw04 A4e (adapted)',
    check: 'ints(0, 12).filter((k) => k * k + (k + 1) * (k + 1) === 61).map((k) => [k * k, (k + 1) * (k + 1)]).flat()',
  },
  {
    id: 'm1.6-28',
    unit: '1.6',
    level: 3,
    kind: 'words',
    q: 'Subtract the cube root of 27 from the square of 8.',
    qVn: 'Làm theo yêu cầu: "Subtract the cube root of 27 from the square of 8."',
    a: '61',
    aVn: '61',
    why: '8² − ∛27 = 64 − 3 = 61. Not 3 − 64.',
    whyVn: '8² − ∛27 = 64 − 3 = 61. Không phải 3 − 64.',
    source: 'hw04 A3.3',
    check: '8 ** 2 - cbrt(27)',
  },
  {
    id: 'm1.6-29',
    unit: '1.6',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen tiles one bathroom wall with 576 square tiles, in a perfect square. How many tiles run along the bottom?',
    qVn: 'Thầy Bowen lát một bức tường phòng tắm bằng 576 viên gạch vuông, thành một hình vuông hoàn hảo. Cạnh dưới có bao nhiêu viên gạch?',
    a: '24 tiles',
    aVn: '24 viên',
    why: '20² = 400 and 25² = 625, and 24 × 24 = 576. Mr Bowen has three walls still to do.',
    whyVn: '20² = 400 và 25² = 625, và 24 × 24 = 576. Thầy Bowen vẫn còn ba bức tường nữa phải lát.',
    source: 'deck 1.6 s20',
    check: 'sqrt(576)',
  },
  {
    id: 'm1.6-30',
    unit: '1.6',
    level: 3,
    kind: 'words',
    q: 'True or false: 16 and 17 are consecutive square numbers.',
    qVn: 'Đúng hay sai: 16 và 17 là hai "consecutive square numbers".',
    a: 'False',
    aVn: 'Sai',
    why: '17 is not a square number. The next square after 16 is 25.',
    whyVn: '17 không phải số chính phương. Số chính phương tiếp theo sau 16 là 25.',
    source: 'deck 1.6 s15 (adapted)',
    check: 'tf(Number.isInteger(sqrt(17)))',
  },
]
