// content/banks/y7-math/U01_5.js
// Maths 1.5 · Tests for divisibility. Schema and house rules: bank.js.
//
// The nine tests are the deck's (2, 3, 4, 5, 6, 8, 9, 10, 11), and 7 has none:
// you divide. The test for 11 is two groups and a difference, never an
// alternating sum, and a difference of 0 counts. The traps are the deck's: even
// is not enough for 6, divisible by 4 does not mean divisible by 8, and no
// shuffle of the digits changes the digit sum. Every why is the TEST, because
// "yes" on its own does not get the mark. "Divisible by", "factor of" and
// "multiple of" are one fact in three sentences, and the Vietnamese says
// "chia hết cho", "ước số" and "bội số" throughout, as the 1.5 deck does.
export const QUESTIONS = [
  {
    id: 'm1.5-01',
    unit: '1.5',
    level: 1,
    kind: 'words',
    q: 'What does "divisible by" mean?',
    qVn: 'Cụm từ "divisible by" nghĩa là gì?',
    a: 'It divides exactly, nothing left over',
    aVn: 'Chia hết: chia ra đúng, không dư gì',
    why: '42 is divisible by 6: 42 ÷ 6 = 7, with no remainder.',
    whyVn: '42 chia hết cho 6: 42 ÷ 6 = 7, không có số dư.',
    source: 'deck 1.5 s3',
  },
  {
    id: 'm1.5-02',
    unit: '1.5',
    level: 1,
    kind: 'calc',
    q: 'Which of 24, 35, 90 and 91 are divisible by 5?',
    qVn: 'Trong 24, 35, 90 và 91, số nào chia hết cho 5?',
    a: '35 and 90',
    aVn: '35 và 90',
    why: 'They end in 5 or 0.',
    whyVn: 'Chúng tận cùng bằng 5 hoặc 0.',
    source: 'deck 1.5 s1',
    check: '[24, 35, 90, 91].filter((n) => n % 5 === 0)',
  },
  {
    id: 'm1.5-03',
    unit: '1.5',
    level: 1,
    kind: 'words',
    q: 'Which number between 2 and 11 has no quick test for divisibility?',
    qVn: 'Số nào từ 2 đến 11 không có dấu hiệu chia hết nhanh?',
    a: '7',
    aVn: '7',
    why: 'Tests for 7 take longer than dividing. Divide, and look at the remainder.',
    whyVn: 'Dấu hiệu cho 7 còn lâu hơn phép chia. Hãy chia rồi xem số dư.',
    source: 'jeopardy unit1-finale · Divisible By 100',
  },
  {
    id: 'm1.5-04',
    unit: '1.5',
    level: 1,
    kind: 'calc',
    q: 'Is 4735 divisible by 10?',
    qVn: '4735 có chia hết cho 10 không?',
    a: 'No',
    aVn: 'Không',
    why: 'It ends in 5, not 0. It is divisible by 5, but not by 10.',
    whyVn: 'Số này tận cùng bằng 5, không phải 0. Nó chia hết cho 5, nhưng không chia hết cho 10.',
    source: 'deck 1.5 s5 (adapted)',
    check: 'divisible(4735, 10)',
  },
  {
    id: 'm1.5-05',
    unit: '1.5',
    level: 1,
    kind: 'words',
    q: 'To test for 8, how many digits at the end of the number do you look at?',
    qVn: 'Để kiểm tra chia hết cho 8, em nhìn vào mấy chữ số ở cuối số?',
    a: 'Three: the last three digits',
    aVn: 'Ba: ba chữ số cuối',
    why: 'For 4, the last two digits. For 8, the last three.',
    whyVn: 'Với 4, xét hai chữ số cuối. Với 8, xét ba chữ số cuối.',
    source: 'deck 1.5 s7',
  },
  {
    id: 'm1.5-06',
    unit: '1.5',
    level: 1,
    kind: 'calc',
    q: 'The digits of 4725 add up to 18. Is 4725 divisible by 9?',
    qVn: 'Tổng các chữ số của 4725 bằng 18. 4725 có chia hết cho 9 không?',
    a: 'Yes',
    aVn: 'Có',
    why: '18 is a multiple of 9, so 4725 is too.',
    whyVn: '18 là bội số của 9, nên 4725 cũng vậy.',
    source: 'deck 1.5 s6',
    check: 'divisible(4725, 9)',
  },
  {
    id: 'm1.5-07',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'Is 4113 divisible by 3? Say the TEST, not just the answer.',
    qVn: '4113 có chia hết cho 3 không? Hãy nói ra CÁCH KIỂM TRA, đừng chỉ nói đáp án.',
    a: 'Yes',
    aVn: 'Có',
    why: '4 + 1 + 1 + 3 = 9, and 9 is a multiple of 3.',
    whyVn: '4 + 1 + 1 + 3 = 9, mà 9 là bội số của 3.',
    source: 'jeopardy unit1-finale · Divisible By 200',
    check: 'divisible(4113, 3)',
  },
  {
    id: 'm1.5-08',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: '10 is an even number. Is 10 divisible by 6?',
    qVn: '10 là số chẵn. Vậy 10 có chia hết cho 6 không?',
    a: 'No',
    aVn: 'Không',
    why: 'Even is not enough. 6 needs the tests for 2 AND 3, and 1 + 0 = 1.',
    whyVn: 'Chẵn thôi chưa đủ. Chia hết cho 6 phải thoả dấu hiệu của 2 VÀ 3, mà 1 + 0 = 1.',
    source: 'jeopardy unit1-finale · Divisible By 300',
    check: 'divisible(10, 6)',
  },
  {
    id: 'm1.5-09',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'Fill the gap: 48 ÷ 6 = 8, so 48 is ___ by 6.',
    qVn: 'Điền vào chỗ trống: 48 ÷ 6 = 8, so 48 is ___ by 6.',
    a: 'divisible',
    aVn: 'divisible (chia hết)',
    why: 'Same fact: 6 is a factor of 48, and 48 is a multiple of 6.',
    whyVn: 'Cùng một điều: 6 là ước số của 48, và 48 là bội số của 6.',
    source: 'hw05 C3b',
  },
  {
    id: 'm1.5-10',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'Fill the gap with "factor" or "multiple": 56 is divisible by 8, so 8 is a ___ of 56.',
    qVn: 'Điền "factor" hoặc "multiple" vào chỗ trống: 56 is divisible by 8, so 8 is a ___ of 56.',
    a: 'factor',
    aVn: 'factor (ước số)',
    why: 'The smaller number divides in. 56 is a multiple of 8.',
    whyVn: 'Số nhỏ hơn chia vào số lớn. 56 là bội số của 8.',
    source: 'deck 1.5 s4 (adapted)',
  },
  {
    id: 'm1.5-11',
    unit: '1.5',
    level: 2,
    kind: 'calc',
    q: 'Is 6132 divisible by 4?',
    qVn: '6132 có chia hết cho 4 không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'The last two digits, 32, make a multiple of 4.',
    whyVn: 'Hai chữ số cuối là 32, là bội số của 4.',
    source: 'WB 1.5 ex 1 (adapted)',
    check: 'divisible(6132, 4)',
  },
  {
    id: 'm1.5-12',
    unit: '1.5',
    level: 2,
    kind: 'calc',
    q: 'Is 3942 divisible by 6?',
    qVn: '3942 có chia hết cho 6 không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'It is even, and its digits add to 18. It passes the tests for 2 and 3.',
    whyVn: 'Số này chẵn, và tổng các chữ số bằng 18. Nó thoả cả dấu hiệu của 2 và 3.',
    source: 'hw05 C3a',
    check: 'divisible(3942, 6)',
  },
  {
    id: 'm1.5-13',
    unit: '1.5',
    level: 2,
    kind: 'calc',
    q: 'Is 5181 divisible by 11?',
    qVn: '5181 có chia hết cho 11 không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'Groups: 5 + 8 = 13 and 1 + 1 = 2. The difference is 11.',
    whyVn: 'Hai nhóm: 5 + 8 = 13 và 1 + 1 = 2. Hiệu bằng 11.',
    source: 'WB 1.5 ex 2a (adapted)',
    check: 'divisible(5181, 11)',
  },
  {
    id: 'm1.5-14',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'Is 9 a factor of 6372?',
    qVn: '9 có phải là ước số của 6372 không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'The digits add to 18, a multiple of 9. So 6372 is divisible by 9.',
    whyVn: 'Tổng các chữ số bằng 18, là bội số của 9. Vậy 6372 chia hết cho 9.',
    source: 'deck 1.5 s4 (adapted)',
    check: 'divisible(6372, 9)',
  },
  {
    id: 'm1.5-15',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'Is 7128 a multiple of 8?',
    qVn: '7128 có phải là bội số của 8 không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'The last three digits are 128, and 128 ÷ 8 = 16.',
    whyVn: 'Ba chữ số cuối là 128, và 128 ÷ 8 = 16.',
    source: 'deck 1.5 s12',
    check: 'divisible(7128, 8)',
  },
  {
    id: 'm1.5-16',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen\'s number is 3960. Which number from 2 to 11 does NOT divide into it exactly?',
    qVn: 'Con số của thầy Bowen là 3960. Trong các số từ 2 đến 11, nó KHÔNG chia hết cho số nào?',
    a: '7',
    aVn: '7',
    why: '3960 ÷ 7 = 565 remainder 5. Every other number divides exactly.',
    whyVn: '3960 ÷ 7 = 565 dư 5. Mọi số còn lại đều chia hết.',
    source: 'deck 1.5 s2',
    check: 'ints(1, 12).filter((d) => 3960 % d !== 0)',
  },
  {
    id: 'm1.5-17',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen bakes 5304 biscuits. He puts them in bags of 8. Will every bag be full, with no biscuits left over?',
    qVn: 'Thầy Bowen nướng 5304 cái bánh quy. Thầy cho vào các túi, mỗi túi 8 cái. Mọi túi có đầy không, và không thừa cái bánh nào?',
    a: 'Yes',
    aVn: 'Có',
    why: 'The last three digits are 304, and 304 ÷ 8 = 38. That makes 663 bags.',
    whyVn: 'Ba chữ số cuối là 304, và 304 ÷ 8 = 38. Có tất cả 663 túi.',
    source: 'deck 1.5 s16',
    check: 'divisible(5304, 8)',
  },
  {
    id: 'm1.5-18',
    unit: '1.5',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen has 2916 chairs. He puts them out in rows of 9, with no chairs left over. Can he do it? How many rows will there be?',
    qVn: 'Thầy Bowen có 2916 cái ghế. Thầy xếp thành các hàng, mỗi hàng 9 cái, không thừa cái ghế nào. Thầy làm được không? Sẽ có bao nhiêu hàng?',
    a: 'Yes: 324 rows',
    aVn: 'Được: 324 hàng',
    why: 'The digits add to 18, a multiple of 9. There are 24 students in the class.',
    whyVn: 'Tổng các chữ số bằng 18, là bội số của 9. Lớp có 24 học sinh.',
    source: 'deck 1.5 s17',
    check: '2916 / 9',
  },
  {
    id: 'm1.5-19',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen has 3164 stickers to share equally between 8 classes. Can he do it with none left over?',
    qVn: 'Thầy Bowen có 3164 cái sticker để chia đều cho 8 lớp. Thầy có chia được mà không thừa cái nào không?',
    a: 'No',
    aVn: 'Không',
    why: 'The last three digits are 164, and 164 is not a multiple of 8.',
    whyVn: 'Ba chữ số cuối là 164, mà 164 không phải bội số của 8.',
    source: 'hw03 B4.1 (adapted)',
    check: 'divisible(3164, 8)',
  },
  {
    id: 'm1.5-20',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'Show that 62 417 is not divisible by 3. Do not divide.',
    qVn: 'Hãy chứng tỏ 62 417 không chia hết cho 3. Không được chia.',
    a: 'The digits add to 20',
    aVn: 'Tổng các chữ số bằng 20',
    why: '6 + 2 + 4 + 1 + 7 = 20, and 20 is not a multiple of 3.',
    whyVn: '6 + 2 + 4 + 1 + 7 = 20, mà 20 không phải bội số của 3.',
    source: 'q1rev A6c',
    check: '6 + 2 + 4 + 1 + 7',
  },
  {
    id: 'm1.5-21',
    unit: '1.5',
    level: 2,
    kind: 'words',
    q: 'To test for 11, you add every other digit into two groups. What do you do with the two totals?',
    qVn: 'Để kiểm tra chia hết cho 11, em cộng các chữ số cách nhau một ô thành hai nhóm. Em làm gì với hai tổng đó?',
    a: 'Find the difference',
    aVn: 'Tìm hiệu của chúng',
    why: 'If the difference is 0 or a multiple of 11, the number divides by 11.',
    whyVn: 'Nếu hiệu bằng 0 hoặc là bội số của 11, số đó chia hết cho 11.',
    source: 'deck 1.5 s9',
  },
  {
    id: 'm1.5-22',
    unit: '1.5',
    level: 3,
    kind: 'words',
    q: '24 ÷ 6 = 4. Say that ONE fact in three different English sentences.',
    qVn: '24 ÷ 6 = 4. Hãy nói MỘT sự thật đó bằng ba câu tiếng Anh khác nhau.',
    a: 'Factor of, divisible by, multiple of',
    aVn: 'factor of, divisible by, multiple of',
    why: '6 is a factor of 24. 24 is divisible by 6. 24 is a multiple of 6.',
    whyVn: 'Ba câu, một phép chia: 6 is a factor of 24. 24 is divisible by 6. 24 is a multiple of 6.',
    source: 'jeopardy unit1-finale · Divisible By 400',
  },
  {
    id: 'm1.5-23',
    unit: '1.5',
    level: 3,
    kind: 'words',
    q: 'Find the missing digit: 274▢ is divisible by 9. Why is there only one answer?',
    qVn: 'Tìm chữ số bị thiếu: 274▢ chia hết cho 9. Vì sao chỉ có một đáp án?',
    a: '5, making 2745',
    aVn: '5, được số 2745',
    why: '2 + 7 + 4 = 13, and 18 − 13 = 5. A total of 27 would need a digit of 14.',
    whyVn: '2 + 7 + 4 = 13, và 18 − 13 = 5. Tổng bằng 27 thì cần chữ số 14 — không có.',
    source: 'jeopardy unit1-finale · Divisible By 500',
    check: 'ints(-1, 10).find((d) => (2740 + d) % 9 === 0)',
  },
  {
    id: 'm1.5-24',
    unit: '1.5',
    level: 3,
    kind: 'calc',
    q: '4▢8 is divisible by 3. Find all the possible missing digits.',
    qVn: '4▢8 chia hết cho 3. Tìm tất cả các chữ số có thể bị thiếu.',
    a: '0, 3, 6 or 9',
    aVn: '0, 3, 6 hoặc 9',
    why: '4 + 8 = 12. The digits must add to 12, 15, 18 or 21.',
    whyVn: '4 + 8 = 12. Tổng các chữ số phải bằng 12, 15, 18 hoặc 21.',
    source: 'q1rev A6b',
    check: 'ints(-1, 10).filter((d) => (408 + 10 * d) % 3 === 0)',
  },
  {
    id: 'm1.5-25',
    unit: '1.5',
    level: 3,
    kind: 'words',
    q: 'The last two digits of 3716 make 16, so 3716 is divisible by 4. Is it divisible by 8?',
    qVn: 'Hai chữ số cuối của 3716 là 16, nên 3716 chia hết cho 4. Vậy nó có chia hết cho 8 không?',
    a: 'No',
    aVn: 'Không',
    why: 'For 8, test the last three digits: 716 is not a multiple of 8.',
    whyVn: 'Với 8, xét ba chữ số cuối: 716 không phải bội số của 8.',
    source: 'WB 1.5 ex 3b (adapted)',
    check: 'divisible(3716, 8)',
  },
  {
    id: 'm1.5-26',
    unit: '1.5',
    level: 3,
    kind: 'calc',
    q: 'Is 4510 divisible by 11?',
    qVn: '4510 có chia hết cho 11 không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'Groups: 4 + 1 = 5 and 5 + 0 = 5. A difference of 0 counts.',
    whyVn: 'Hai nhóm: 4 + 1 = 5 và 5 + 0 = 5. Hiệu bằng 0 vẫn tính.',
    source: 'hw03 B1',
    check: 'divisible(4510, 11)',
  },
  {
    id: 'm1.5-27',
    unit: '1.5',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen has 2464 socks. He puts them into pairs, then puts the pairs into drawers of 11 pairs, with none left over. How many drawers does he need?',
    qVn: 'Thầy Bowen có 2464 chiếc tất. Thầy xếp thành từng đôi, rồi cho các đôi vào ngăn kéo, mỗi ngăn 11 đôi, không thừa đôi nào. Thầy cần bao nhiêu ngăn kéo?',
    a: '112 drawers',
    aVn: '112 ngăn kéo',
    why: '2464 ÷ 2 = 1232 pairs, and 1232 ÷ 11 = 112. Mr Bowen has two feet.',
    whyVn: '2464 ÷ 2 = 1232 đôi, và 1232 ÷ 11 = 112. Thầy Bowen có hai bàn chân.',
    source: 'hw03 B4.2',
    check: '2464 / 2 / 11',
  },
  {
    id: 'm1.5-28',
    unit: '1.5',
    level: 3,
    kind: 'words',
    q: 'Use the digits 8, 3, 6 and 1, once each, to make a four-digit number. Can you make one that is NOT divisible by 9?',
    qVn: 'Dùng các chữ số 8, 3, 6 và 1, mỗi chữ số một lần, để tạo một số có bốn chữ số. Em có tạo được số nào KHÔNG chia hết cho 9 không?',
    a: 'No',
    aVn: 'Không',
    why: 'The digits add to 18 in every order. Shuffling never changes the digit sum.',
    whyVn: 'Theo thứ tự nào thì tổng các chữ số cũng bằng 18. Xáo trộn không làm thay đổi tổng.',
    source: 'deck 1.5 s14',
    check: 'yes((8 + 3 + 6 + 1) % 9 !== 0)',
  },
  {
    id: 'm1.5-29',
    unit: '1.5',
    level: 3,
    kind: 'words',
    q: 'Count up from 1. What is the first number that is not a factor of 840?',
    qVn: 'Đếm từ 1 trở lên. Số đầu tiên không phải là ước số của 840 là số nào?',
    a: '9',
    aVn: '9',
    why: '1 to 8 all divide 840. Its digits add to 12, not a multiple of 9.',
    whyVn: 'Các số từ 1 đến 8 đều là ước số của 840. Tổng các chữ số bằng 12, không phải bội số của 9.',
    source: 'WB 1.5 ex 8 (adapted)',
    check: 'ints(0, 20).find((d) => 840 % d !== 0)',
  },
  {
    id: 'm1.5-30',
    unit: '1.5',
    level: 3,
    kind: 'calc',
    q: 'Which of 2, 3, 5, 9 and 11 divide exactly into 5555?',
    qVn: 'Trong các số 2, 3, 5, 9 và 11, 5555 chia hết cho những số nào?',
    a: '5 and 11',
    aVn: '5 và 11',
    why: 'It ends in 5. Its digits add to 20. Groups 5 + 5 and 5 + 5 have a difference of 0.',
    whyVn: 'Số này tận cùng bằng 5. Tổng các chữ số bằng 20. Hai nhóm 5 + 5 và 5 + 5 có hiệu bằng 0.',
    source: 'WB 1.5 ex 5 (adapted)',
    check: '[2, 3, 5, 9, 11].filter((d) => 5555 % d === 0)',
  },
]
