// content/banks/y7-math/U01_1.js
// Maths 1.1 · Adding & subtracting integers. Schema and house rules: bank.js.
//
// The traps are the deck's: "subtract 5 from 8" is 8 − 5, never 5 − 8; a
// difference is a gap, so it is never negative; only − (−) becomes +, and a
// single + (−) still moves left; taking away a debt adds. Two long problems
// change nothing at all. The Vietnamese keeps "subtract … from", "take … away
// from", "less than" and "more than" in English, because translating them would
// answer the question. A negative after + or − always sits in brackets.
export const QUESTIONS = [
  {
    id: 'm1.1-01',
    unit: '1.1',
    level: 1,
    kind: 'calc',
    q: 'What is −3 + 5?',
    qVn: '−3 + 5 bằng bao nhiêu?',
    a: '2',
    aVn: '2',
    why: 'Start at −3, then move 5 to the right.',
    whyVn: 'Bắt đầu ở −3, rồi đi sang phải 5 bước.',
    source: 'jeopardy maths · Adding & Subtracting 100',
    check: '-3 + 5',
  },
  {
    id: 'm1.1-02',
    unit: '1.1',
    level: 1,
    kind: 'words',
    q: 'In maths, what is an integer?',
    qVn: 'Trong toán, từ "integer" nghĩa là gì?',
    a: 'A whole number, never a fraction',
    aVn: 'Số nguyên: không bao giờ là phân số',
    why: 'It can be positive, negative or zero.',
    whyVn: 'Nó có thể dương, âm hoặc bằng 0.',
    source: 'jeopardy revision · Maths 1.1 100',
  },
  {
    id: 'm1.1-03',
    unit: '1.1',
    level: 1,
    kind: 'words',
    q: 'In maths, do you read −5 as "minus five" or "negative five"?',
    qVn: 'Trong toán, em đọc −5 là "minus five" hay "negative five"?',
    a: 'Negative five',
    aVn: 'Negative five (âm năm)',
    why: '"Minus" is the operation, as in 8 − 5.',
    whyVn: '"Minus" là phép tính, như trong 8 − 5.',
    source: 'deck 1.1 s5',
  },
  {
    id: 'm1.1-04',
    unit: '1.1',
    level: 1,
    kind: 'words',
    q: 'Which is lower, −8 or −4?',
    qVn: '−8 và −4, số nào thấp hơn?',
    a: '−8',
    aVn: '−8',
    why: 'It is further from zero, on the cold side.',
    whyVn: 'Nó xa số 0 hơn, về phía lạnh.',
    source: 'deck 1.1 s4',
    check: 'Math.min(-8, -4)',
  },
  {
    id: 'm1.1-05',
    unit: '1.1',
    level: 1,
    kind: 'words',
    q: 'On the number line, which way do you move to add a negative number?',
    qVn: 'Trên trục số, cộng một số âm thì em đi về phía nào?',
    a: 'Left',
    aVn: 'Sang trái',
    why: 'Add a positive: move right. Add a negative: move left.',
    whyVn: 'Cộng số dương: đi sang phải. Cộng số âm: đi sang trái.',
    source: 'deck 1.1 s6',
  },
  {
    id: 'm1.1-06',
    unit: '1.1',
    level: 1,
    kind: 'words',
    q: 'Name three English words that tell you a number is going down.',
    qVn: 'Nêu ba từ tiếng Anh cho biết một số đang đi xuống.',
    a: 'For example: fall, drop, owe',
    aVn: 'Ví dụ: fall, drop, owe',
    why: 'Also decrease, loss, withdraw, colder, lower, below, less than.',
    whyVn: 'Còn có decrease, loss, withdraw, colder, lower, below, less than.',
    source: 'jeopardy maths · Every Class Is an English Class 200',
  },
  {
    id: 'm1.1-07',
    unit: '1.1',
    level: 2,
    kind: 'calc',
    q: 'What is −7 + 10?',
    qVn: '−7 + 10 bằng bao nhiêu?',
    a: '3',
    aVn: '3',
    source: 'jeopardy revision · Maths 1.1 200',
    check: '-7 + 10',
  },
  {
    id: 'm1.1-08',
    unit: '1.1',
    level: 2,
    kind: 'calc',
    q: 'What is −6 − 4?',
    qVn: '−6 − 4 bằng bao nhiêu?',
    a: '−10',
    aVn: '−10',
    why: 'Subtract a positive: move left.',
    whyVn: 'Trừ số dương: đi sang trái.',
    source: 'jeopardy maths · Adding & Subtracting 200',
    check: '-6 - 4',
  },
  {
    id: 'm1.1-09',
    unit: '1.1',
    level: 2,
    kind: 'calc',
    q: 'What is 2 − (−5)?',
    qVn: '2 − (−5) bằng bao nhiêu?',
    a: '7',
    aVn: '7',
    why: 'Minus a negative = plus: 2 + 5 = 7.',
    whyVn: 'Trừ số âm = cộng: 2 + 5 = 7.',
    source: 'jeopardy maths · Adding & Subtracting 300',
    check: '2 - (-5)',
  },
  {
    id: 'm1.1-10',
    unit: '1.1',
    level: 2,
    kind: 'calc',
    q: 'What is 5 − (−3)?',
    qVn: '5 − (−3) bằng bao nhiêu?',
    a: '8',
    aVn: '8',
    why: 'Add the inverse of −3 instead: 5 + 3 = 8.',
    whyVn: 'Hãy cộng số đối của −3: 5 + 3 = 8.',
    source: 'jeopardy revision · Maths 1.1 300',
    check: '5 - (-3)',
  },
  {
    id: 'm1.1-11',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: 'What is the inverse of −9? Use it to work out 3 − (−9).',
    qVn: 'Số đối của −9 là gì? Dùng nó để tính 3 − (−9).',
    a: '9, so 3 − (−9) = 12',
    aVn: '9, nên 3 − (−9) = 12',
    why: 'To subtract −9, add its inverse: 3 + 9 = 12.',
    whyVn: 'Muốn trừ −9, hãy cộng số đối của nó: 3 + 9 = 12.',
    source: 'jeopardy revision · Maths 1.1 500',
    check: '3 - (-9)',
  },
  {
    id: 'm1.1-12',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: '"Subtract 5 from 8." Write the calculation, then the answer.',
    qVn: '"Subtract 5 from 8." Hãy viết phép tính, rồi viết đáp án.',
    a: '8 − 5 = 3',
    aVn: '8 − 5 = 3',
    why: 'Not 5 − 8. The word "from" marks the number you start at.',
    whyVn: 'Không phải 5 − 8. Từ "from" chỉ ra số em bắt đầu.',
    source: 'jeopardy maths · Every Class Is an English Class 100',
    check: '8 - 5',
  },
  {
    id: 'm1.1-13',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: '"Subtract 9 from 4." Write the calculation, then the answer.',
    qVn: '"Subtract 9 from 4." Hãy viết phép tính, rồi viết đáp án.',
    a: '4 − 9 = −5',
    aVn: '4 − 9 = −5',
    why: 'Not 9 − 4. Start at 4, the number after "from".',
    whyVn: 'Không phải 9 − 4. Bắt đầu ở 4, số đứng sau "from".',
    source: 'hw01 A3.1',
    check: '4 - 9',
  },
  {
    id: 'm1.1-14',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: '"Take 8 away from −3." Write the calculation, then the answer.',
    qVn: '"Take 8 away from −3." Hãy viết phép tính, rồi viết đáp án.',
    a: '−3 − 8 = −11',
    aVn: '−3 − 8 = −11',
    why: 'Not 8 − (−3). The English gives the numbers in the opposite order.',
    whyVn: 'Không phải 8 − (−3). Tiếng Anh nói hai số theo thứ tự ngược lại.',
    source: 'hw05 B3.2',
    check: '-3 - 8',
  },
  {
    id: 'm1.1-15',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: 'Write "ten more than negative six" as a calculation, then work it out.',
    qVn: 'Viết "ten more than negative six" thành phép tính, rồi tính ra.',
    a: '−6 + 10 = 4',
    aVn: '−6 + 10 = 4',
    why: 'Start at −6 and increase by 10.',
    whyVn: 'Bắt đầu ở −6 và tăng thêm 10.',
    source: 'deck 1.1 s13 (adapted)',
    check: '-6 + 10',
  },
  {
    id: 'm1.1-16',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: 'The temperature is −4 °C. It falls by 10 degrees. What is the new temperature?',
    qVn: 'Nhiệt độ là −4 °C. Nhiệt độ giảm 10 độ. Nhiệt độ mới là bao nhiêu?',
    a: '−14 °C',
    aVn: '−14 °C',
    why: '−4 − 10 = −14. "Falls by" is a down-word.',
    whyVn: '−4 − 10 = −14. "Falls by" là từ đi xuống.',
    source: 'jeopardy maths · Adding & Subtracting 400',
    check: '-4 - 10',
  },
  {
    id: 'm1.1-17',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: '"The temperature rose by 6 degrees from −2 °C." Write the calculation and the new temperature.',
    qVn: '"The temperature rose by 6 degrees from −2 °C." Hãy viết phép tính và nhiệt độ mới.',
    a: '−2 + 6 = 4 °C',
    aVn: '−2 + 6 = 4 °C',
    why: '"Rose" is an up-word, so it is an addition.',
    whyVn: '"Rose" là từ đi lên, nên đây là phép cộng.',
    source: 'jeopardy revision · Maths 1.1 400',
    check: '-2 + 6',
  },
  {
    id: 'm1.1-18',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen parks on floor −4. He takes the lift up 9 floors. Which floor is he on now?',
    qVn: 'Thầy Bowen đỗ xe ở tầng −4. Thầy đi thang máy lên 9 tầng. Bây giờ thầy đang ở tầng nào?',
    a: 'Floor 5',
    aVn: 'Tầng 5',
    why: '−4 + 9 = 5.',
    whyVn: '−4 + 9 = 5.',
    source: 'jeopardy maths · Word Problems 100',
    check: '-4 + 9',
  },
  {
    id: 'm1.1-19',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen gets into the lift on floor 7. He goes down 11 floors, then up 2 floors. Which floor is he on now?',
    qVn: 'Thầy Bowen bước vào thang máy ở tầng 7. Thầy đi xuống 11 tầng, rồi lên 2 tầng. Bây giờ thầy đang ở tầng nào?',
    a: 'Floor −2',
    aVn: 'Tầng −2',
    why: '7 − 11 + 2 = −2. That is level B2, below the ground.',
    whyVn: '7 − 11 + 2 = −2. Đó là tầng B2, dưới mặt đất.',
    source: 'hw01 A5.1',
    check: '7 - 11 + 2',
  },
  {
    id: 'm1.1-20',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: 'A submarine is 30 m below sea level. It rises 12 m. Where is it now?',
    qVn: 'Một tàu ngầm ở 30 m dưới mực nước biển. Nó nổi lên 12 m. Bây giờ nó ở đâu?',
    a: '−18 m, 18 m below sea level',
    aVn: '−18 m, tức 18 m dưới mực nước biển',
    why: '"Below" makes it negative. "Rises" means add: −30 + 12.',
    whyVn: '"Below" là số âm. "Rises" là cộng: −30 + 12.',
    source: 'deck 1.1 s13',
    check: '-30 + 12',
  },
  {
    id: 'm1.1-21',
    unit: '1.1',
    level: 2,
    kind: 'words',
    q: 'A freezer is at −15 °C. The room is at 20 °C. How much warmer is the room?',
    qVn: 'Tủ đông ở −15 °C. Căn phòng ở 20 °C. Căn phòng ấm hơn bao nhiêu độ?',
    a: '35 degrees',
    aVn: '35 độ',
    why: 'Bigger − smaller: 20 − (−15) = 20 + 15 = 35.',
    whyVn: 'Số lớn − số bé: 20 − (−15) = 20 + 15 = 35.',
    source: 'deck 1.1 s15',
    check: '20 - (-15)',
  },
  {
    id: 'm1.1-22',
    unit: '1.1',
    level: 3,
    kind: 'words',
    q: 'What is "6 less than −3"? Write the calculation, then the answer.',
    qVn: '"6 less than −3" là bao nhiêu? Hãy viết phép tính, rồi viết đáp án.',
    a: '−3 − 6 = −9',
    aVn: '−3 − 6 = −9',
    why: 'Not 6 − (−3). Start at −3, then move 6 to the left.',
    whyVn: 'Không phải 6 − (−3). Bắt đầu ở −3, rồi đi sang trái 6 bước.',
    source: 'q1rev A2.2',
    check: '-3 - 6',
  },
  {
    id: 'm1.1-23',
    unit: '1.1',
    level: 3,
    kind: 'calc',
    q: 'What is 7 + (−2)? Careful.',
    qVn: '7 + (−2) bằng bao nhiêu? Cẩn thận nhé.',
    a: '5',
    aVn: '5',
    why: 'Not 9. Only − (−) turns into +. A single + (−) still moves left.',
    whyVn: 'Không phải 9. Chỉ có − (−) mới thành +. Một dấu + (−) vẫn đi sang trái.',
    source: 'deck 1.1 s8 (adapted)',
    check: '7 + (-2)',
  },
  {
    id: 'm1.1-24',
    unit: '1.1',
    level: 3,
    kind: 'words',
    q: 'What is the difference between −3 and 4?',
    qVn: '"The difference between −3 and 4" bằng bao nhiêu?',
    a: '7',
    aVn: '7',
    why: 'The gap between them. But −3 − 4 = −7: a different question.',
    whyVn: 'Khoảng cách giữa hai số. Còn −3 − 4 = −7: đó là câu hỏi khác.',
    source: 'jeopardy maths · Every Class Is an English Class 300',
    check: '4 - (-3)',
  },
  {
    id: 'm1.1-25',
    unit: '1.1',
    level: 3,
    kind: 'words',
    q: 'At midnight in Moscow it is −11 °C. At noon it is 2 °C. By how many degrees has the temperature risen?',
    qVn: 'Lúc nửa đêm ở Moscow là −11 °C. Đến trưa là 2 °C. Nhiệt độ đã tăng bao nhiêu độ?',
    a: '13 degrees',
    aVn: '13 độ',
    why: '2 − (−11) = 13. Not −9: it asks for the change, the gap.',
    whyVn: '2 − (−11) = 13. Không phải −9: đề hỏi mức thay đổi, tức khoảng cách.',
    source: 'q1rev A2.3',
    check: '2 - (-11)',
  },
  {
    id: 'm1.1-26',
    unit: '1.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen has −6 dollars in the bank. He deposits 20 dollars and withdraws 9 dollars. Then the bank takes away a 4-dollar debt. How much has he got?',
    qVn: 'Thầy Bowen có −6 đô trong ngân hàng. Thầy gửi vào 20 đô và rút ra 9 đô. Sau đó ngân hàng xoá một khoản nợ 4 đô. Thầy còn bao nhiêu tiền?',
    a: '9 dollars',
    aVn: '9 đô',
    why: '−6 + 20 − 9 − (−4) = 9. Taking away a debt adds.',
    whyVn: '−6 + 20 − 9 − (−4) = 9. Xoá một khoản nợ thì cộng thêm.',
    source: 'jeopardy maths · Adding & Subtracting 500',
    check: '-6 + 20 - 9 - (-4)',
  },
  {
    id: 'm1.1-27',
    unit: '1.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen owes 45 dollars. He pays back 20 dollars. Write the calculation and how much he has now.',
    qVn: 'Thầy Bowen nợ 45 đô. Thầy trả lại 20 đô. Hãy viết phép tính và số tiền thầy có bây giờ.',
    a: '−45 + 20 = −25',
    aVn: '−45 + 20 = −25',
    why: 'Paying back makes the debt smaller. It is not −45 − 20.',
    whyVn: 'Trả nợ làm khoản nợ nhỏ đi. Không phải −45 − 20.',
    source: 'hw05 B3.4',
    check: '-45 + 20',
  },
  {
    id: 'm1.1-28',
    unit: '1.1',
    level: 3,
    kind: 'words',
    q: 'At 5 a.m. in Sa Pa it is −5 °C. By 1 p.m. it has risen by 12 degrees. By 9 p.m. it has fallen by 7 degrees. What is the temperature at 9 p.m.?',
    qVn: 'Lúc 5 giờ sáng ở Sa Pa là −5 °C. Đến 1 giờ chiều, nhiệt độ đã tăng 12 độ. Đến 9 giờ tối, nhiệt độ đã giảm 7 độ. Lúc 9 giờ tối là bao nhiêu độ?',
    a: '0 °C',
    aVn: '0 °C',
    why: '−5 + 12 − 7 = 0. Zero is a real answer: do not change it.',
    whyVn: '−5 + 12 − 7 = 0. Số 0 cũng là đáp án thật: đừng sửa nó.',
    source: 'hw05 D1.1a (adapted)',
    check: '-5 + 12 - 7',
  },
  {
    id: 'm1.1-29',
    unit: '1.1',
    level: 3,
    kind: 'words',
    q: 'A snail is 12 m down a well, at −12 m. Every day it climbs up 3 m and slides back down 3 m. Where is it after 9 days?',
    qVn: 'Một con ốc sên ở sâu 12 m dưới giếng, tại −12 m. Mỗi ngày nó bò lên 3 m rồi tụt xuống 3 m. Sau 9 ngày nó ở đâu?',
    a: 'Still at −12 m',
    aVn: 'Vẫn ở −12 m',
    why: 'Each day +3 − 3 = 0, so 9 days change nothing.',
    whyVn: 'Mỗi ngày +3 − 3 = 0, nên 9 ngày chẳng thay đổi gì.',
    source: 'jeopardy maths · Word Problems 500',
    check: '-12 + 9 * (3 - 3)',
  },
  {
    id: 'm1.1-30',
    unit: '1.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen\'s account is at −40 dollars. Every Monday he deposits 25 dollars. Every Friday he withdraws 25 dollars. How much is in it after 6 weeks?',
    qVn: 'Tài khoản của thầy Bowen đang là −40 đô. Mỗi thứ Hai thầy gửi vào 25 đô. Mỗi thứ Sáu thầy rút ra 25 đô. Sau 6 tuần, trong tài khoản có bao nhiêu?',
    a: '−40 dollars',
    aVn: '−40 đô',
    why: 'Each week +25 − 25 = 0, so 6 weeks change nothing.',
    whyVn: 'Mỗi tuần +25 − 25 = 0, nên 6 tuần chẳng thay đổi gì.',
    source: 'hw01 A5.3',
    check: '-40 + 6 * (25 - 25)',
  },
]
