// content/banks/y7-math/U01_4.js
// Maths 1.4 · Highest common factors. Schema and house rules: bank.js.
//
// The traps are the deck's: the HCF is never "none" (8 and 9 share 1), and
// when one number divides into the other the HCF is the smaller one (6 and
// 18). Factor against multiple is the most-confused pair in the unit, so two
// questions ask only that. The Vietnamese says "ước số" throughout, as the 1.4
// deck does, and "X chia hết cho Y" always means X ÷ Y comes out exactly.
export const QUESTIONS = [
  {
    id: 'm1.4-01',
    unit: '1.4',
    level: 1,
    kind: 'calc',
    q: 'List all the factors of 12.',
    qVn: 'Liệt kê tất cả các ước số của 12.',
    a: '1, 2, 3, 4, 6, 12',
    aVn: '1, 2, 3, 4, 6, 12',
    why: 'Hunt in pairs: 1 × 12, 2 × 6, 3 × 4.',
    whyVn: 'Tìm theo cặp: 1 × 12, 2 × 6, 3 × 4.',
    source: 'jeopardy unit1-finale · Factors & the HCF 100',
    check: 'factors(12)',
  },
  {
    id: 'm1.4-02',
    unit: '1.4',
    level: 1,
    kind: 'words',
    q: 'What do the letters HCF stand for?',
    qVn: 'Ba chữ HCF là viết tắt của cụm từ nào?',
    a: 'Highest common factor',
    aVn: 'Highest common factor (ƯCLN)',
    source: 'jeopardy unit1-finale · Factors & the HCF 200',
  },
  {
    id: 'm1.4-03',
    unit: '1.4',
    level: 1,
    kind: 'calc',
    q: 'Is 5 a factor of 12?',
    qVn: '5 có phải là ước số của 12 không?',
    a: 'No',
    aVn: 'Không',
    why: '12 ÷ 5 = 2 remainder 2.',
    whyVn: '12 ÷ 5 = 2 dư 2.',
    source: 'deck 1.4 s3',
    check: 'divisible(12, 5)',
  },
  {
    id: 'm1.4-04',
    unit: '1.4',
    level: 1,
    kind: 'calc',
    q: 'List all the factors of 18.',
    qVn: 'Liệt kê tất cả các ước số của 18.',
    a: '1, 2, 3, 6, 9, 18',
    aVn: '1, 2, 3, 6, 9, 18',
    source: 'deck 1.4 s1',
    check: 'factors(18)',
  },
  {
    id: 'm1.4-05',
    unit: '1.4',
    level: 2,
    kind: 'calc',
    q: 'List all the factors of 36.',
    qVn: 'Liệt kê tất cả các ước số của 36.',
    a: '1, 2, 3, 4, 6, 9, 12, 18, 36',
    aVn: '1, 2, 3, 4, 6, 9, 12, 18, 36',
    why: '6 × 6 is the pair people miss.',
    whyVn: '6 × 6 là cặp hay bị bỏ sót.',
    source: 'hw03 A1a',
    check: 'factors(36)',
  },
  {
    id: 'm1.4-06',
    unit: '1.4',
    level: 2,
    kind: 'words',
    q: 'Fill the gap with "factor" or "multiple": 4 is a ___ of 12.',
    qVn: 'Điền "factor" hoặc "multiple" vào chỗ trống: 4 is a ___ of 12.',
    a: 'factor',
    aVn: 'factor (ước số)',
    why: 'A factor divides in. A multiple is what you land on.',
    whyVn: 'Ước số thì chia vào. Bội số là số em đáp xuống.',
    source: 'deck 1.4 s4',
  },
  {
    id: 'm1.4-07',
    unit: '1.4',
    level: 2,
    kind: 'words',
    q: 'Fill the gap with "factor" or "multiple": 36 is a ___ of 12.',
    qVn: 'Điền "factor" hoặc "multiple" vào chỗ trống: 36 is a ___ of 12.',
    a: 'multiple',
    aVn: 'multiple (bội số)',
    why: '12, 24, 36: you land on 36.',
    whyVn: '12, 24, 36: em đáp xuống 36.',
    source: 'deck 1.4 s4',
  },
  {
    id: 'm1.4-08',
    unit: '1.4',
    level: 2,
    kind: 'calc',
    q: 'List the common factors of 16 and 24.',
    qVn: 'Liệt kê các ước số chung của 16 và 24.',
    a: '1, 2, 4, 8',
    aVn: '1, 2, 4, 8',
    source: 'WB 1.4 ex 3 (adapted)',
    check: 'common(factors(16), factors(24))',
  },
  {
    id: 'm1.4-09',
    unit: '1.4',
    level: 1,
    kind: 'calc',
    q: 'Find the HCF of 12 and 18.',
    qVn: 'Tìm ƯCLN của 12 và 18.',
    a: '6',
    aVn: '6',
    source: 'deck 1.4 s6',
    check: 'hcf(12, 18)',
  },
  {
    id: 'm1.4-10',
    unit: '1.4',
    level: 2,
    kind: 'calc',
    q: 'Find the HCF of 24 and 80.',
    qVn: 'Tìm ƯCLN của 24 và 80.',
    a: '8',
    aVn: '8',
    source: 'deck 1.4 s8',
    check: 'hcf(24, 80)',
  },
  {
    id: 'm1.4-11',
    unit: '1.4',
    level: 2,
    kind: 'calc',
    q: 'Find the HCF of 20 and 30.',
    qVn: 'Tìm ƯCLN của 20 và 30.',
    a: '10',
    aVn: '10',
    source: 'hw03 A3.3',
    check: 'hcf(20, 30)',
  },
  {
    id: 'm1.4-12',
    unit: '1.4',
    level: 2,
    kind: 'calc',
    q: 'Find the HCF of 27 and 36.',
    qVn: 'Tìm ƯCLN của 27 và 36.',
    a: '9',
    aVn: '9',
    source: 'WB 1.4 ex 6 (adapted)',
    check: 'hcf(27, 36)',
  },
  {
    id: 'm1.4-13',
    unit: '1.4',
    level: 2,
    kind: 'calc',
    q: 'Find the HCF of 28 and 42.',
    qVn: 'Tìm ƯCLN của 28 và 42.',
    a: '14',
    aVn: '14',
    source: 'q1rev A4d',
    check: 'hcf(28, 42)',
  },
  {
    id: 'm1.4-14',
    unit: '1.4',
    level: 2,
    kind: 'calc',
    q: 'Find the HCF of 60 and 84.',
    qVn: 'Tìm ƯCLN của 60 và 84.',
    a: '12',
    aVn: '12',
    source: 'WB 1.4 ex 7 (adapted)',
    check: 'hcf(60, 84)',
  },
  {
    id: 'm1.4-15',
    unit: '1.4',
    level: 3,
    kind: 'calc',
    q: 'What is the HCF of 8 and 9? Careful.',
    qVn: 'ƯCLN của 8 và 9 là bao nhiêu? Cẩn thận nhé.',
    a: '1',
    aVn: '1',
    why: 'Never "none". 1 is a factor of every number.',
    whyVn: 'Không bao giờ là "không có". 1 là ước số của mọi số.',
    source: 'jeopardy unit1-finale · Factors & the HCF 300',
    check: 'hcf(8, 9)',
  },
  {
    id: 'm1.4-16',
    unit: '1.4',
    level: 3,
    kind: 'calc',
    q: 'What is the HCF of 6 and 18?',
    qVn: 'ƯCLN của 6 và 18 là bao nhiêu?',
    a: '6',
    aVn: '6',
    why: 'Not 1. 6 divides into 18, so the HCF is the smaller number.',
    whyVn: 'Không phải 1. 18 chia hết cho 6, nên ƯCLN là số nhỏ hơn.',
    source: 'jeopardy unit1-finale · Factors & the HCF 400',
    check: 'hcf(6, 18)',
  },
  {
    id: 'm1.4-17',
    unit: '1.4',
    level: 3,
    kind: 'calc',
    q: 'Find the HCF of 7 and 42.',
    qVn: 'Tìm ƯCLN của 7 và 42.',
    a: '7',
    aVn: '7',
    why: 'Not 1. 7 divides into 42.',
    whyVn: 'Không phải 1. 42 chia hết cho 7.',
    source: 'hw03 A5b',
    check: 'hcf(7, 42)',
  },
  {
    id: 'm1.4-18',
    unit: '1.4',
    level: 3,
    kind: 'calc',
    q: 'Find the HCF of 25 and 36.',
    qVn: 'Tìm ƯCLN của 25 và 36.',
    a: '1',
    aVn: '1',
    why: 'The only common factor is 1.',
    whyVn: 'Ước số chung duy nhất là 1.',
    source: 'WB 1.4 ex 6 (adapted)',
    check: 'hcf(25, 36)',
  },
  {
    id: 'm1.4-19',
    unit: '1.4',
    level: 3,
    kind: 'calc',
    q: 'What is the HCF of 99 and 100?',
    qVn: 'ƯCLN của 99 và 100 là bao nhiêu?',
    a: '1',
    aVn: '1',
    why: 'They are consecutive. The HCF of consecutive numbers is always 1.',
    whyVn: 'Hai số liên tiếp. ƯCLN của hai số liên tiếp luôn là 1.',
    source: 'deck 1.4 s16',
    check: 'hcf(99, 100)',
  },
  {
    id: 'm1.4-20',
    unit: '1.4',
    level: 1,
    kind: 'words',
    q: 'What does "consecutive" mean?',
    qVn: 'Từ "consecutive" nghĩa là gì?',
    a: 'One straight after the other',
    aVn: 'Liên tiếp: số này ngay sau số kia',
    why: '6 and 7 are consecutive. 6 and 8 are not.',
    whyVn: '6 và 7 là liên tiếp. 6 và 8 thì không.',
    source: 'deck 1.4 s15',
  },
  {
    id: 'm1.4-21',
    unit: '1.4',
    level: 3,
    kind: 'words',
    q: 'Why does the book ask for the LOWEST common multiple, but the HIGHEST common factor?',
    qVn: 'Vì sao sách hỏi bội số chung NHỎ NHẤT, nhưng lại hỏi ước số chung LỚN NHẤT?',
    a: 'Multiples never stop. Factors do.',
    aVn: 'Bội số không bao giờ dừng. Ước số thì có.',
    why: 'So there is no highest multiple. And the lowest common factor is always 1.',
    whyVn: 'Nên không có bội số lớn nhất. Còn ước số chung nhỏ nhất thì luôn là 1.',
    source: 'jeopardy unit1-finale · Factors & the HCF 500',
  },
  {
    id: 'm1.4-22',
    unit: '1.4',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen has 24 pencils and 40 stickers. He makes identical packs, with nothing left over. What is the greatest number of packs he can make?',
    qVn: 'Thầy Bowen có 24 cây bút chì và 40 cái sticker. Thầy chia thành các gói giống hệt nhau, không thừa thứ gì. Số gói nhiều nhất thầy có thể làm là bao nhiêu?',
    a: '8 packs',
    aVn: '8 gói',
    why: 'The HCF of 24 and 40 is 8: 3 pencils and 5 stickers in each.',
    whyVn: 'ƯCLN của 24 và 40 là 8: mỗi gói 3 bút chì và 5 sticker.',
    source: 'deck 1.4 s2',
    check: 'hcf(24, 40)',
  },
  {
    id: 'm1.4-23',
    unit: '1.4',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen has two ribbons, 36 cm and 48 cm long. He cuts both into equal pieces, as long as possible, with nothing left over. How long is each piece?',
    qVn: 'Thầy Bowen có hai dải ruy băng, dài 36 cm và 48 cm. Thầy cắt cả hai thành các đoạn bằng nhau, dài nhất có thể, không thừa mẩu nào. Mỗi đoạn dài bao nhiêu?',
    a: '12 cm',
    aVn: '12 cm',
    why: 'The HCF of 36 and 48 is 12.',
    whyVn: 'ƯCLN của 36 và 48 là 12.',
    source: 'deck 1.4 s13',
    check: 'hcf(36, 48)',
  },
  {
    id: 'm1.4-24',
    unit: '1.4',
    level: 3,
    kind: 'words',
    q: 'There are 24 books on Mr Bowen\'s shelf. 18 are maths books. Write the fraction that are maths books, in its simplest form.',
    qVn: 'Trên kệ của thầy Bowen có 24 cuốn sách. 18 cuốn là sách toán. Viết phân số chỉ phần sách toán, ở dạng tối giản.',
    a: '3/4',
    aVn: '3/4',
    why: 'Divide 18 and 24 by their HCF, 6.',
    whyVn: 'Chia cả 18 và 24 cho ƯCLN của chúng là 6.',
    source: 'deck 1.4 s14',
    check: '[18 / hcf(18, 24), 24 / hcf(18, 24)]',
  },
  {
    id: 'm1.4-25',
    unit: '1.4',
    level: 2,
    kind: 'calc',
    q: 'Write 48/60 in its simplest form.',
    qVn: 'Viết 48/60 ở dạng tối giản.',
    a: '4/5',
    aVn: '4/5',
    why: 'The HCF of 48 and 60 is 12.',
    whyVn: 'ƯCLN của 48 và 60 là 12.',
    source: 'hw03 A4',
    check: '[48 / hcf(48, 60), 60 / hcf(48, 60)]',
  },
  {
    id: 'm1.4-26',
    unit: '1.4',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen buys 30 bananas and 45 oranges. He makes identical fruit baskets with nothing left over, as many as possible. How many baskets does he make?',
    qVn: 'Thầy Bowen mua 30 quả chuối và 45 quả cam. Thầy làm các giỏ trái cây giống hệt nhau, không thừa quả nào, càng nhiều giỏ càng tốt. Thầy làm được bao nhiêu giỏ?',
    a: '15 baskets',
    aVn: '15 giỏ',
    why: 'Each basket: 2 bananas and 3 oranges. There are 12 teachers.',
    whyVn: 'Mỗi giỏ: 2 quả chuối và 3 quả cam. Có 12 giáo viên.',
    source: 'deck 1.4 s17',
    check: 'hcf(30, 45)',
  },
  {
    id: 'm1.4-27',
    unit: '1.4',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen has 42 red beads and 56 blue beads. He makes identical bracelets, using every bead. What is the greatest number of bracelets?',
    qVn: 'Thầy Bowen có 42 hạt đỏ và 56 hạt xanh. Thầy làm các vòng tay giống hệt nhau, dùng hết mọi hạt. Số vòng tay nhiều nhất là bao nhiêu?',
    a: '14 bracelets',
    aVn: '14 vòng tay',
    why: 'Each one has 3 red beads and 4 blue beads.',
    whyVn: 'Mỗi vòng có 3 hạt đỏ và 4 hạt xanh.',
    source: 'hw03 A6.1',
    check: 'hcf(42, 56)',
  },
  {
    id: 'm1.4-28',
    unit: '1.4',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen shares 60 round biscuits and 48 square biscuits onto as many plates as possible, all the same. Then he eats one plate. How many biscuits are left?',
    qVn: 'Thầy Bowen chia 60 bánh quy tròn và 48 bánh quy vuông ra càng nhiều đĩa càng tốt, các đĩa giống hệt nhau. Rồi thầy ăn hết một đĩa. Còn lại bao nhiêu bánh quy?',
    a: '99',
    aVn: '99',
    why: '12 plates of 9 biscuits. 108 − 9 = 99.',
    whyVn: '12 đĩa, mỗi đĩa 9 bánh. 108 − 9 = 99.',
    source: 'hw05 D1.5 (adapted)',
    check: '60 + 48 - (60 + 48) / hcf(60, 48)',
  },
  {
    id: 'm1.4-29',
    unit: '1.4',
    level: 2,
    kind: 'words',
    q: 'Does 6 divide into 81 exactly?',
    qVn: '81 có chia hết cho 6 không?',
    a: 'No',
    aVn: 'Không',
    why: '81 ÷ 6 = 13 remainder 3.',
    whyVn: '81 ÷ 6 = 13 dư 3.',
    source: 'hw03 A3.4',
    check: 'divisible(81, 6)',
  },
  {
    id: 'm1.4-30',
    unit: '1.4',
    level: 2,
    kind: 'calc',
    q: 'Is 9 a common factor of 48 and 72?',
    qVn: '9 có phải là ước số chung của 48 và 72 không?',
    a: 'No',
    aVn: 'Không',
    why: '9 divides into 72, but not into 48.',
    whyVn: '72 chia hết cho 9, nhưng 48 thì không.',
    source: 'q1rev A4e',
    check: 'yes(48 % 9 === 0 && 72 % 9 === 0)',
  },
]
