// content/banks/y7-math/U01_2.js
// Maths 1.2 · Multiplying & dividing integers. Schema and house rules: bank.js.
//
// The spine is the deck's: "two negatives make a positive" is true for × and ÷
// and false for +, so the addition trap sits beside the sign rules on purpose,
// and the bracket in 20 ÷ (−3 + −2) holds an addition. "Divide −20 by 4" and
// "3 divided into −27" give the numbers in opposite orders. The three Workbook
// items the deck reused word for word come here with new numbers. Two long
// problems turn on a zero. After × and ÷ a negative takes no brackets, as the
// deck writes it; after + and − it does.
export const QUESTIONS = [
  {
    id: 'm1.2-01',
    unit: '1.2',
    level: 1,
    kind: 'calc',
    q: 'What is 3 × −4?',
    qVn: '3 × −4 bằng bao nhiêu?',
    a: '−12',
    aVn: '−12',
    why: 'Different signs give a negative.',
    whyVn: 'Hai dấu khác nhau thì âm.',
    source: 'jeopardy maths · Multiplying & Dividing 100',
    check: '3 * -4',
  },
  {
    id: 'm1.2-02',
    unit: '1.2',
    level: 1,
    kind: 'calc',
    q: 'What is −8 × 2?',
    qVn: '−8 × 2 bằng bao nhiêu?',
    a: '−16',
    aVn: '−16',
    source: 'jeopardy revision · Maths 1.2 100',
    check: '-8 * 2',
  },
  {
    id: 'm1.2-03',
    unit: '1.2',
    level: 1,
    kind: 'calc',
    q: 'What is 45 ÷ −9?',
    qVn: '45 ÷ −9 bằng bao nhiêu?',
    a: '−5',
    aVn: '−5',
    why: '45 ÷ 9 = 5, and different signs give a negative.',
    whyVn: '45 ÷ 9 = 5, và hai dấu khác nhau thì âm.',
    source: 'hw02 A1e',
    check: '45 / -9',
  },
  {
    id: 'm1.2-04',
    unit: '1.2',
    level: 1,
    kind: 'words',
    q: 'In maths, what does the word "product" mean?',
    qVn: 'Trong toán, từ "product" nghĩa là gì?',
    a: 'The answer when you multiply',
    aVn: 'Tích: kết quả khi em nhân',
    why: 'In a shop, a product is a thing you buy.',
    whyVn: 'Trong cửa hàng, "product" là món hàng em mua.',
    source: 'deck 1.2 s8',
  },
  {
    id: 'm1.2-05',
    unit: '1.2',
    level: 1,
    kind: 'words',
    q: 'Find the product of 3 and −7.',
    qVn: 'Tìm "product" của 3 và −7.',
    a: '−21',
    aVn: '−21',
    why: '"Product" means multiply: 3 × −7 = −21.',
    whyVn: '"Product" nghĩa là nhân: 3 × −7 = −21.',
    source: 'jeopardy revision · Maths 1.2 200 (adapted)',
    check: '3 * -7',
  },
  {
    id: 'm1.2-06',
    unit: '1.2',
    level: 1,
    kind: 'words',
    q: 'When you multiply or divide, which give a positive answer: same signs or different signs?',
    qVn: 'Khi nhân hoặc chia, trường hợp nào cho đáp án dương: hai dấu giống nhau hay hai dấu khác nhau?',
    a: 'Same signs',
    aVn: 'Hai dấu giống nhau',
    why: 'Different signs give a negative. The rules are the same for × and ÷.',
    whyVn: 'Hai dấu khác nhau thì âm. Quy tắc giống nhau cho cả × và ÷.',
    source: 'deck 1.2 s6',
  },
  {
    id: 'm1.2-07',
    unit: '1.2',
    level: 2,
    kind: 'calc',
    q: 'What is −6 × −5?',
    qVn: '−6 × −5 bằng bao nhiêu?',
    a: '30',
    aVn: '30',
    why: 'Same signs give a positive.',
    whyVn: 'Hai dấu giống nhau thì dương.',
    source: 'jeopardy maths · Multiplying & Dividing 200',
    check: '-6 * -5',
  },
  {
    id: 'm1.2-08',
    unit: '1.2',
    level: 2,
    kind: 'calc',
    q: 'What is −48 ÷ 6?',
    qVn: '−48 ÷ 6 bằng bao nhiêu?',
    a: '−8',
    aVn: '−8',
    why: 'Dividing uses the same four sign rules as multiplying.',
    whyVn: 'Phép chia dùng đúng bốn quy tắc dấu như phép nhân.',
    source: 'jeopardy maths · Multiplying & Dividing 300',
    check: '-48 / 6',
  },
  {
    id: 'm1.2-09',
    unit: '1.2',
    level: 2,
    kind: 'calc',
    q: 'What is −36 ÷ −9?',
    qVn: '−36 ÷ −9 bằng bao nhiêu?',
    a: '4',
    aVn: '4',
    why: 'Same signs give a positive, for ÷ as well as ×.',
    whyVn: 'Hai dấu giống nhau thì dương, với ÷ cũng như với ×.',
    source: 'jeopardy revision · Maths 1.2 300',
    check: '-36 / -9',
  },
  {
    id: 'm1.2-10',
    unit: '1.2',
    level: 2,
    kind: 'calc',
    q: 'What is −12 ÷ −12?',
    qVn: '−12 ÷ −12 bằng bao nhiêu?',
    a: '1',
    aVn: '1',
    why: 'Not −1. Same signs give a positive.',
    whyVn: 'Không phải −1. Hai dấu giống nhau thì dương.',
    source: 'hw02 A1h',
    check: '-12 / -12',
  },
  {
    id: 'm1.2-11',
    unit: '1.2',
    level: 2,
    kind: 'calc',
    q: 'Continue the pattern: 2 × −3 = −6, 1 × −3 = −3, 0 × −3 = 0. What is −1 × −3?',
    qVn: 'Tiếp tục quy luật: 2 × −3 = −6, 1 × −3 = −3, 0 × −3 = 0. Vậy −1 × −3 bằng bao nhiêu?',
    a: '3',
    aVn: '3',
    why: 'The answers climb by 3 each time. So a negative × a negative is positive.',
    whyVn: 'Mỗi dòng đáp án tăng thêm 3. Vậy âm × âm thì dương.',
    source: 'deck 1.2 s4 (adapted)',
    check: '-1 * -3',
  },
  {
    id: 'm1.2-12',
    unit: '1.2',
    level: 2,
    kind: 'calc',
    q: 'Write 3 × −11 as a repeated addition, then work it out.',
    qVn: 'Viết 3 × −11 thành phép cộng lặp lại, rồi tính ra.',
    a: '−11 + (−11) + (−11) = −33',
    aVn: '−11 + (−11) + (−11) = −33',
    why: 'Three jumps of 11 to the left, starting at 0.',
    whyVn: 'Ba bước nhảy 11 đơn vị sang trái, bắt đầu từ 0.',
    source: 'deck 1.2 s3 (adapted)',
    check: '3 * -11',
  },
  {
    id: 'm1.2-13',
    unit: '1.2',
    level: 2,
    kind: 'calc',
    q: 'Find the missing number: −72 ÷ ? = −9',
    qVn: 'Tìm số còn thiếu: −72 ÷ ? = −9',
    a: '8',
    aVn: '8',
    why: 'Sign first: −72 and −9 are both negative, so ? is positive.',
    whyVn: 'Xét dấu trước: −72 và −9 đều âm, nên ? là số dương.',
    source: 'deck 1.2 s14',
    check: '-72 / -9',
  },
  {
    id: 'm1.2-14',
    unit: '1.2',
    level: 2,
    kind: 'calc',
    q: 'Estimate −3.9 × 5.2 by rounding each number first.',
    qVn: 'Ước lượng −3.9 × 5.2 bằng cách làm tròn mỗi số trước.',
    a: 'About −20',
    aVn: 'Khoảng −20',
    why: 'Round: −4 × 5 = −20. The real answer must be close to it.',
    whyVn: 'Làm tròn: −4 × 5 = −20. Đáp án thật phải gần với số này.',
    source: 'jeopardy revision · Maths 1.2 400 (adapted)',
    check: '-4 * 5',
  },
  {
    id: 'm1.2-15',
    unit: '1.2',
    level: 2,
    kind: 'words',
    q: '"Divide −20 by 4." Write the calculation, then the answer.',
    qVn: '"Divide −20 by 4." Hãy viết phép tính, rồi viết đáp án.',
    a: '−20 ÷ 4 = −5',
    aVn: '−20 ÷ 4 = −5',
    why: 'The number after "divide" is the one being shared out.',
    whyVn: 'Số đứng sau "divide" là số bị chia.',
    source: 'jeopardy maths · Every Class Is an English Class 400',
    check: '-20 / 4',
  },
  {
    id: 'm1.2-16',
    unit: '1.2',
    level: 2,
    kind: 'words',
    q: '"Multiply −7 by 6." Write the calculation, then the answer.',
    qVn: '"Multiply −7 by 6." Hãy viết phép tính, rồi viết đáp án.',
    a: '−7 × 6 = −42',
    aVn: '−7 × 6 = −42',
    why: 'You start with −7, so it comes first.',
    whyVn: 'Em bắt đầu với −7, nên số đó đứng trước.',
    source: 'hw02 A2.1',
    check: '-7 * 6',
  },
  {
    id: 'm1.2-17',
    unit: '1.2',
    level: 2,
    kind: 'words',
    q: 'What is 8 times −3?',
    qVn: '"8 times −3" bằng bao nhiêu?',
    a: '−24',
    aVn: '−24',
    why: '"Times" is the everyday word for multiply: 8 × −3.',
    whyVn: '"Times" là từ thông dụng của phép nhân: 8 × −3.',
    source: 'deck 1.2 s10',
    check: '8 * -3',
  },
  {
    id: 'm1.2-18',
    unit: '1.2',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen shares a debt of 24 dollars equally between 6 people. Write each share as a negative number.',
    qVn: 'Thầy Bowen chia đều một khoản nợ 24 đô cho 6 người. Viết phần của mỗi người thành một số âm.',
    a: '−4 dollars each',
    aVn: 'Mỗi người −4 đô',
    why: 'A debt is negative: −24 ÷ 6 = −4.',
    whyVn: 'Khoản nợ là số âm: −24 ÷ 6 = −4.',
    source: 'hw02 A2.5',
    check: '-24 / 6',
  },
  {
    id: 'm1.2-19',
    unit: '1.2',
    level: 2,
    kind: 'words',
    q: 'The temperature falls 3 degrees every hour for 6 hours. Write the calculation and the change.',
    qVn: 'Nhiệt độ giảm 3 độ mỗi giờ, trong 6 giờ. Hãy viết phép tính và mức thay đổi.',
    a: '6 × −3 = −18',
    aVn: '6 × −3 = −18',
    why: 'It is 18 degrees colder.',
    whyVn: 'Tức là lạnh đi 18 độ.',
    source: 'jeopardy maths · Word Problems 300',
    check: '6 * -3',
  },
  {
    id: 'm1.2-20',
    unit: '1.2',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen dives from the surface to −32 m in 4 minutes, at a steady speed. How far does he go down each minute?',
    qVn: 'Thầy Bowen lặn từ mặt nước xuống −32 m trong 4 phút, với tốc độ đều. Mỗi phút thầy xuống bao xa?',
    a: '8 m each minute',
    aVn: 'Mỗi phút 8 m',
    why: '−32 ÷ 4 = −8: a change of −8 m every minute.',
    whyVn: '−32 ÷ 4 = −8: thay đổi −8 m mỗi phút.',
    source: 'jeopardy maths · Word Problems 400 (adapted)',
    check: 'Math.abs(-32 / 4)',
  },
  {
    id: 'm1.2-21',
    unit: '1.2',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen\'s bank charges him 7 dollars every day his account is empty. It has been empty for 5 days. What has that done to his balance?',
    qVn: 'Ngân hàng thu của thầy Bowen 7 đô mỗi ngày tài khoản của thầy trống. Tài khoản đã trống 5 ngày. Điều đó ảnh hưởng thế nào đến số dư của thầy?',
    a: '−35 dollars',
    aVn: '−35 đô',
    why: '5 × −7 = −35: his balance goes down 35 dollars.',
    whyVn: '5 × −7 = −35: số dư của thầy giảm 35 đô.',
    source: 'deck 1.2 s15',
    check: '5 * -7',
  },
  {
    id: 'm1.2-22',
    unit: '1.2',
    level: 3,
    kind: 'calc',
    q: 'Work out 20 ÷ (−3 + −2). Careful.',
    qVn: 'Hãy tính 20 ÷ (−3 + −2). Cẩn thận nhé.',
    a: '−4',
    aVn: '−4',
    why: 'The bracket is an addition: −3 + −2 = −5. Then 20 ÷ −5 = −4.',
    whyVn: 'Trong ngoặc là phép cộng: −3 + −2 = −5. Rồi 20 ÷ −5 = −4.',
    source: 'jeopardy maths · Multiplying & Dividing 400',
    check: '20 / (-3 + -2)',
  },
  {
    id: 'm1.2-23',
    unit: '1.2',
    level: 3,
    kind: 'calc',
    q: 'What is −3 + (−4)? Careful: it is not the same as −3 − (−4).',
    qVn: '−3 + (−4) bằng bao nhiêu? Cẩn thận: nó không giống −3 − (−4).',
    a: '−7',
    aVn: '−7',
    why: 'Adding a negative still moves left. Only − (−) becomes +.',
    whyVn: 'Cộng một số âm vẫn đi sang trái. Chỉ có − (−) mới thành +.',
    source: 'jeopardy maths · Traps & Tricks 300',
    check: '-3 + (-4)',
  },
  {
    id: 'm1.2-24',
    unit: '1.2',
    level: 3,
    kind: 'calc',
    q: 'Work out −5 × (3 − 7).',
    qVn: 'Hãy tính −5 × (3 − 7).',
    a: '20',
    aVn: '20',
    why: 'Bracket first: 3 − 7 = −4. Then −5 × −4 = 20.',
    whyVn: 'Làm trong ngoặc trước: 3 − 7 = −4. Rồi −5 × −4 = 20.',
    source: 'hw02 A4 (adapted)',
    check: '-5 * (3 - 7)',
  },
  {
    id: 'm1.2-25',
    unit: '1.2',
    level: 3,
    kind: 'calc',
    q: 'Find the missing number: ? × −7 = 56',
    qVn: 'Tìm số còn thiếu: ? × −7 = 56',
    a: '−8',
    aVn: '−8',
    why: 'Sign first: 56 is positive and −7 is negative, so ? is negative too.',
    whyVn: 'Xét dấu trước: 56 dương mà −7 âm, nên ? cũng phải âm.',
    source: 'jeopardy revision · Maths 1.2 500',
    check: '56 / -7',
  },
  {
    id: 'm1.2-26',
    unit: '1.2',
    level: 3,
    kind: 'words',
    q: 'Is "two negatives make a positive" always true?',
    qVn: 'Câu "two negatives make a positive" có luôn đúng không?',
    a: 'No. Only for × and ÷, not for +',
    aVn: 'Không. Chỉ đúng với × và ÷, không với +',
    why: '−6 × −2 = 12, but −6 + (−2) = −8.',
    whyVn: '−6 × −2 = 12, nhưng −6 + (−2) = −8.',
    source: 'jeopardy maths · Multiplying & Dividing 500',
    check: 'yes(-6 + (-2) > 0)',
  },
  {
    id: 'm1.2-27',
    unit: '1.2',
    level: 3,
    kind: 'words',
    q: '"3 divided into −27." Write the calculation, then the answer.',
    qVn: '"3 divided into −27." Hãy viết phép tính, rồi viết đáp án.',
    a: '−27 ÷ 3 = −9',
    aVn: '−27 ÷ 3 = −9',
    why: 'Not 3 ÷ −27. The number being shared out is −27.',
    whyVn: 'Không phải 3 ÷ −27. Số bị chia là −27.',
    source: 'hw02 A2.4 (adapted)',
    check: '-27 / 3',
  },
  {
    id: 'm1.2-28',
    unit: '1.2',
    level: 3,
    kind: 'words',
    q: 'How many pairs of integers have a product of −24?',
    qVn: 'Có bao nhiêu cặp số nguyên có tích bằng −24?',
    a: '8 pairs',
    aVn: '8 cặp',
    why: 'Four factor pairs of 24, and the minus sign can go on either number.',
    whyVn: '24 có bốn cặp thừa số, và dấu âm có thể đặt ở số nào cũng được.',
    source: 'jeopardy maths · Traps & Tricks 500',
    check: '2 * factors(24).filter((d) => d * d <= 24).length',
  },
  {
    id: 'm1.2-29',
    unit: '1.2',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen plans to buy durian for the class, at 90 000 dong each. 24 students want 3 each. Durian is not allowed on the school bus, so he buys 0. How much does he spend?',
    qVn: 'Thầy Bowen định mua sầu riêng cho cả lớp, mỗi quả 90 000 đồng. 24 học sinh, mỗi bạn muốn 3 quả. Sầu riêng không được mang lên xe buýt của trường, nên thầy mua 0 quả. Thầy tiêu hết bao nhiêu tiền?',
    a: 'Nothing: 0 dong',
    aVn: 'Không đồng nào: 0 đồng',
    why: 'Anything multiplied by 0 is 0. The other numbers do not matter.',
    whyVn: 'Bất cứ số nào nhân với 0 đều bằng 0. Các số khác không quan trọng.',
    source: 'jeopardy maths · Traps & Tricks 100 (adapted)',
    check: '0 * 90000',
  },
  {
    id: 'm1.2-30',
    unit: '1.2',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen takes 47 rubber ducks to market at 3 dollars each. The stall costs him 15 dollars. It rains all day and he sells 0. How much does he make or lose?',
    qVn: 'Thầy Bowen mang 47 con vịt cao su ra chợ bán, mỗi con 3 đô. Tiền thuê sạp là 15 đô. Trời mưa cả ngày và thầy bán được 0 con. Thầy lời hay lỗ bao nhiêu?',
    a: '−15 dollars: he loses 15',
    aVn: '−15 đô: thầy lỗ 15 đô',
    why: 'He earns 0 × 3 = 0, but the stall still costs 15 dollars.',
    whyVn: 'Thầy thu được 0 × 3 = 0, nhưng tiền sạp 15 đô vẫn phải trả.',
    source: 'hw02 A5.3 (adapted)',
    check: '0 * 3 - 15',
  },
]
