// content/banks/y7-math/U01_3.js
// Maths 1.3 · Lowest common multiples. Schema and house rules: bank.js.
//
// The traps are the deck's: the LCM of 4 and 8 is 8, not 32; multiplying is a
// lucky shortcut, not the rule; and two alarms that both ring every 15 minutes
// need no working at all. "Common" means shared, never ordinary. Fresh number
// pairs sit beside the deck's own, so a class cannot win on memory alone.
export const QUESTIONS = [
  {
    id: 'm1.3-01',
    unit: '1.3',
    level: 1,
    kind: 'calc',
    q: 'List the first five multiples of 4.',
    qVn: 'Liệt kê năm bội số đầu tiên của 4.',
    a: '4, 8, 12, 16, 20',
    aVn: '4, 8, 12, 16, 20',
    source: 'jeopardy maths · Multiples & the LCM 100',
    check: 'multiples(4, 5)',
  },
  {
    id: 'm1.3-02',
    unit: '1.3',
    level: 1,
    kind: 'calc',
    q: 'Write the first five multiples of 9.',
    qVn: 'Viết năm bội số đầu tiên của 9.',
    a: '9, 18, 27, 36, 45',
    aVn: '9, 18, 27, 36, 45',
    source: 'WB 1.3 ex 1 (adapted)',
    check: 'multiples(9, 5)',
  },
  {
    id: 'm1.3-03',
    unit: '1.3',
    level: 1,
    kind: 'words',
    q: 'What do the letters LCM stand for?',
    qVn: 'Ba chữ LCM là viết tắt của cụm từ nào?',
    a: 'Lowest common multiple',
    aVn: 'Lowest common multiple (BCNN)',
    source: 'jeopardy maths · Multiples & the LCM 200',
  },
  {
    id: 'm1.3-04',
    unit: '1.3',
    level: 1,
    kind: 'words',
    q: 'In maths, what does the word "common" mean?',
    qVn: 'Trong toán, từ "common" nghĩa là gì?',
    a: 'Shared: in both lists',
    aVn: 'Chung: có trong cả hai danh sách',
    why: 'In everyday English, it means ordinary.',
    whyVn: 'Trong tiếng Anh hằng ngày, nó nghĩa là bình thường.',
    source: 'deck 1.3 s4',
  },
  {
    id: 'm1.3-05',
    unit: '1.3',
    level: 1,
    kind: 'words',
    q: 'The LCM of 4 and 6 is 12. Is 24 a common multiple of 4 and 6?',
    qVn: 'BCNN của 4 và 6 là 12. 24 có phải là một bội số chung của 4 và 6 không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'So is 36. The LCM is the lowest one.',
    whyVn: '36 cũng vậy. BCNN là số nhỏ nhất.',
    source: 'deck 1.3 s5',
    check: 'yes(24 % 4 === 0 && 24 % 6 === 0)',
  },
  {
    id: 'm1.3-06',
    unit: '1.3',
    level: 1,
    kind: 'calc',
    q: 'Find the LCM of 3 and 7.',
    qVn: 'Tìm BCNN của 3 và 7.',
    a: '21',
    aVn: '21',
    source: 'hw02 B2a',
    check: 'lcm(3, 7)',
  },
  {
    id: 'm1.3-07',
    unit: '1.3',
    level: 2,
    kind: 'calc',
    q: 'What is the LCM of 6 and 9?',
    qVn: 'BCNN của 6 và 9 là bao nhiêu?',
    a: '18',
    aVn: '18',
    why: '6, 12, 18 and 9, 18. The first match is 18.',
    whyVn: '6, 12, 18 và 9, 18. Số trùng đầu tiên là 18.',
    source: 'jeopardy maths · Multiples & the LCM 300',
    check: 'lcm(6, 9)',
  },
  {
    id: 'm1.3-08',
    unit: '1.3',
    level: 2,
    kind: 'calc',
    q: 'Find the LCM of 6 and 8.',
    qVn: 'Tìm BCNN của 6 và 8.',
    a: '24',
    aVn: '24',
    source: 'hw02 B2c',
    check: 'lcm(6, 8)',
  },
  {
    id: 'm1.3-09',
    unit: '1.3',
    level: 2,
    kind: 'calc',
    q: 'Find the LCM of 8 and 10.',
    qVn: 'Tìm BCNN của 8 và 10.',
    a: '40',
    aVn: '40',
    source: 'WB 1.3 ex 3 (adapted)',
    check: 'lcm(8, 10)',
  },
  {
    id: 'm1.3-10',
    unit: '1.3',
    level: 2,
    kind: 'calc',
    q: 'Find the LCM of 9 and 15.',
    qVn: 'Tìm BCNN của 9 và 15.',
    a: '45',
    aVn: '45',
    source: 'q1rev A4c',
    check: 'lcm(9, 15)',
  },
  {
    id: 'm1.3-11',
    unit: '1.3',
    level: 2,
    kind: 'calc',
    q: 'Find the LCM of 4 and 14.',
    qVn: 'Tìm BCNN của 4 và 14.',
    a: '28',
    aVn: '28',
    source: 'WB 1.3 ex 8 (adapted)',
    check: 'lcm(4, 14)',
  },
  {
    id: 'm1.3-12',
    unit: '1.3',
    level: 2,
    kind: 'calc',
    q: 'What is the LCM of 3 and 5?',
    qVn: 'BCNN của 3 và 5 là bao nhiêu?',
    a: '15',
    aVn: '15',
    why: 'Multiplying works here. It is a lucky shortcut, not the rule.',
    whyVn: 'Lần này nhân hai số thì đúng. Đó là mẹo may mắn, không phải quy tắc.',
    source: 'jeopardy revision · Maths 1.3 300 (adapted)',
    check: 'lcm(3, 5)',
  },
  {
    id: 'm1.3-13',
    unit: '1.3',
    level: 3,
    kind: 'calc',
    q: 'What is the LCM of 4 and 8? Careful.',
    qVn: 'BCNN của 4 và 8 là bao nhiêu? Cẩn thận nhé.',
    a: '8',
    aVn: '8',
    why: 'Not 32. 4 divides into 8, so the LCM is the bigger number.',
    whyVn: 'Không phải 32. 8 chia hết cho 4, nên BCNN là số lớn hơn.',
    source: 'jeopardy maths · Multiples & the LCM 400',
    check: 'lcm(4, 8)',
  },
  {
    id: 'm1.3-14',
    unit: '1.3',
    level: 3,
    kind: 'calc',
    q: 'Find the LCM of 5 and 20.',
    qVn: 'Tìm BCNN của 5 và 20.',
    a: '20',
    aVn: '20',
    why: 'Not 100. 5 divides into 20.',
    whyVn: 'Không phải 100. 20 chia hết cho 5.',
    source: 'hw02 B2b',
    check: 'lcm(5, 20)',
  },
  {
    id: 'm1.3-15',
    unit: '1.3',
    level: 3,
    kind: 'calc',
    q: 'Find the LCM of 9 and 9.',
    qVn: 'Tìm BCNN của 9 và 9.',
    a: '9',
    aVn: '9',
    why: 'The two numbers are the same. There is nothing to work out.',
    whyVn: 'Hai số giống nhau. Chẳng có gì phải tính.',
    source: 'hw02 B2d',
    check: 'lcm(9, 9)',
  },
  {
    id: 'm1.3-16',
    unit: '1.3',
    level: 2,
    kind: 'words',
    q: 'The LCM of 5 and 10 is not 50. What is it?',
    qVn: 'BCNN của 5 và 10 không phải là 50. Vậy nó là bao nhiêu?',
    a: '10',
    aVn: '10',
    why: '5 divides into 10.',
    whyVn: '10 chia hết cho 5.',
    source: 'deck 1.3 s18',
    check: 'lcm(5, 10)',
  },
  {
    id: 'm1.3-17',
    unit: '1.3',
    level: 3,
    kind: 'words',
    q: 'True or false: to find the LCM, you always multiply the two numbers.',
    qVn: 'Đúng hay sai: muốn tìm BCNN, em luôn lấy hai số nhân với nhau.',
    a: 'False',
    aVn: 'Sai',
    why: 'The LCM of 4 and 8 is 8, not 32. When in doubt, list them.',
    whyVn: 'BCNN của 4 và 8 là 8, không phải 32. Nếu không chắc, hãy liệt kê ra.',
    source: 'jeopardy maths · Traps & Tricks 400',
    check: 'tf(lcm(4, 8) === 4 * 8)',
  },
  {
    id: 'm1.3-18',
    unit: '1.3',
    level: 2,
    kind: 'words',
    q: '8 × 12 = 96. Is 96 the LCM of 8 and 12?',
    qVn: '8 × 12 = 96. 96 có phải là BCNN của 8 và 12 không?',
    a: 'No. The LCM is 24.',
    aVn: 'Không. BCNN là 24.',
    why: '96 is in both lists, but 24 comes first.',
    whyVn: '96 có trong cả hai danh sách, nhưng 24 xuất hiện trước.',
    source: 'hw05 C1e',
    check: 'lcm(8, 12)',
  },
  {
    id: 'm1.3-19',
    unit: '1.3',
    level: 2,
    kind: 'words',
    q: 'How many multiples of 20 are less than 100?',
    qVn: 'Có bao nhiêu bội số của 20 nhỏ hơn 100?',
    a: '4',
    aVn: '4',
    why: '20, 40, 60, 80. 100 is not less than 100.',
    whyVn: '20, 40, 60, 80. 100 không nhỏ hơn 100.',
    source: 'WB 1.3 ex 2 (adapted)',
    check: 'multiples(20, 10).filter((m) => m < 100).length',
  },
  {
    id: 'm1.3-20',
    unit: '1.3',
    level: 2,
    kind: 'words',
    q: 'Which is a multiple of both 9 and 10: 80, 90 or 100?',
    qVn: 'Số nào là bội số của cả 9 và 10: 80, 90 hay 100?',
    a: '90',
    aVn: '90',
    source: 'WB 1.3 ex 10 (adapted)',
    check: 'lcm(9, 10)',
  },
  {
    id: 'm1.3-21',
    unit: '1.3',
    level: 2,
    kind: 'calc',
    q: 'Find the first three common multiples of 3 and 4.',
    qVn: 'Tìm ba bội số chung đầu tiên của 3 và 4.',
    a: '12, 24, 36',
    aVn: '12, 24, 36',
    source: 'WB 1.3 ex 5 (adapted)',
    check: 'multiples(lcm(3, 4), 3)',
  },
  {
    id: 'm1.3-22',
    unit: '1.3',
    level: 2,
    kind: 'words',
    q: 'A red light flashes every 4 seconds. A blue light flashes every 6 seconds. They have just flashed together. When do they next flash together?',
    qVn: 'Đèn đỏ nháy mỗi 4 giây. Đèn xanh nháy mỗi 6 giây. Hai đèn vừa nháy cùng lúc. Khi nào chúng lại nháy cùng nhau?',
    a: 'After 12 seconds',
    aVn: 'Sau 12 giây',
    why: 'The LCM of 4 and 6 is 12.',
    whyVn: 'BCNN của 4 và 6 là 12.',
    source: 'jeopardy maths · Multiples & the LCM 500',
    check: 'lcm(4, 6)',
  },
  {
    id: 'm1.3-23',
    unit: '1.3',
    level: 2,
    kind: 'words',
    q: 'Two buses leave Mr Bowen\'s stop at 7:00. One leaves every 10 minutes. The other leaves every 15 minutes. When do they next leave together?',
    qVn: 'Hai xe buýt rời trạm của thầy Bowen lúc 7:00. Một xe chạy mỗi 10 phút. Xe kia chạy mỗi 15 phút. Khi nào hai xe lại cùng rời trạm?',
    a: '7:30',
    aVn: '7:30',
    why: 'The LCM of 10 and 15 is 30, so 30 minutes later.',
    whyVn: 'BCNN của 10 và 15 là 30, tức là 30 phút sau.',
    source: 'deck 1.3 s11',
    check: 'clock("7:00", lcm(10, 15))',
  },
  {
    id: 'm1.3-24',
    unit: '1.3',
    level: 3,
    kind: 'words',
    q: 'A red bus leaves every 12 minutes. A blue bus leaves every 18 minutes. They leave together at 8:00. When do they next leave together?',
    qVn: 'Xe buýt đỏ chạy mỗi 12 phút. Xe buýt xanh chạy mỗi 18 phút. Hai xe cùng rời trạm lúc 8:00. Khi nào hai xe lại cùng rời trạm?',
    a: '8:36',
    aVn: '8:36',
    why: 'The LCM is 36. "When" wants a time, not a number.',
    whyVn: 'BCNN là 36. "When" hỏi giờ, không hỏi một con số.',
    source: 'hw05 C2 (adapted)',
    check: 'clock("8:00", lcm(12, 18))',
  },
  {
    id: 'm1.3-25',
    unit: '1.3',
    level: 3,
    kind: 'words',
    q: 'One tap drips every 4 seconds. Another tap drips every 12 seconds. They have just dripped together. How often do they drip together?',
    qVn: 'Một vòi nước nhỏ giọt mỗi 4 giây. Vòi kia nhỏ giọt mỗi 12 giây. Hai vòi vừa nhỏ giọt cùng lúc. Bao lâu thì chúng lại nhỏ giọt cùng nhau?',
    a: 'Every 12 seconds',
    aVn: 'Cứ 12 giây một lần',
    why: 'Not 48. 4 divides into 12.',
    whyVn: 'Không phải 48. 12 chia hết cho 4.',
    source: 'jeopardy revision · Maths 1.3 500',
    check: 'lcm(4, 12)',
  },
  {
    id: 'm1.3-26',
    unit: '1.3',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen sets two alarms. One rings every 15 minutes. The other rings every 15 minutes. They have just rung together. When do they next ring together?',
    qVn: 'Thầy Bowen đặt hai chuông báo thức. Một chuông reo mỗi 15 phút. Chuông kia reo mỗi 15 phút. Hai chuông vừa reo cùng lúc. Khi nào chúng lại reo cùng nhau?',
    a: 'In 15 minutes',
    aVn: 'Sau 15 phút',
    why: 'Read both numbers before you start.',
    whyVn: 'Hãy đọc cả hai con số trước khi bắt đầu.',
    source: 'deck 1.3 s15',
    check: 'lcm(15, 15)',
  },
  {
    id: 'm1.3-27',
    unit: '1.3',
    level: 2,
    kind: 'words',
    q: 'Hot dogs come in packs of 8. Buns come in packs of 12. What is the smallest number of each you can buy, with none left over?',
    qVn: 'Xúc xích bán theo gói 8 cái. Bánh mì bán theo gói 12 cái. Số ít nhất của mỗi loại em có thể mua mà không thừa cái nào là bao nhiêu?',
    a: '24 of each',
    aVn: 'Mỗi loại 24 cái',
    why: '3 packs of hot dogs and 2 packs of buns.',
    whyVn: '3 gói xúc xích và 2 gói bánh mì.',
    source: 'jeopardy revision · Maths 1.3 400',
    check: 'lcm(8, 12)',
  },
  {
    id: 'm1.3-28',
    unit: '1.3',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen buys sausages in packs of 6 and bread rolls in packs of 8. He wants the same number of each. What is the smallest number of sausage packs?',
    qVn: 'Thầy Bowen mua xúc xích theo gói 6 cái và bánh mì theo gói 8 cái. Thầy muốn số lượng mỗi loại bằng nhau. Số gói xúc xích ít nhất là bao nhiêu?',
    a: '4 packs',
    aVn: '4 gói',
    why: '24 of each: 4 packs of sausages, 3 packs of rolls.',
    whyVn: 'Mỗi loại 24 cái: 4 gói xúc xích, 3 gói bánh mì.',
    source: 'q1rev A5 (adapted)',
    check: 'lcm(6, 8) / 6',
  },
  {
    id: 'm1.3-29',
    unit: '1.3',
    level: 2,
    kind: 'words',
    q: 'One bell rings every 6 minutes. Another bell rings every 10 minutes. They ring together now. After how many minutes will they ring together again?',
    qVn: 'Một chuông reo mỗi 6 phút. Chuông kia reo mỗi 10 phút. Bây giờ hai chuông reo cùng lúc. Sau bao nhiêu phút chúng lại reo cùng nhau?',
    a: '30 minutes',
    aVn: '30 phút',
    why: 'Not 60. List them: 10, 20, 30.',
    whyVn: 'Không phải 60. Hãy liệt kê: 10, 20, 30.',
    source: 'hw05 C2',
    check: 'lcm(6, 10)',
  },
  {
    id: 'm1.3-30',
    unit: '1.3',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen runs one lap in 10 minutes. His cat runs one lap in 4 minutes. They start together. After how many minutes are they next at the start together?',
    qVn: 'Thầy Bowen chạy một vòng hết 10 phút. Con mèo của thầy chạy một vòng hết 4 phút. Cả hai xuất phát cùng lúc. Sau bao nhiêu phút cả hai lại cùng ở vạch xuất phát?',
    a: 'After 20 minutes',
    aVn: 'Sau 20 phút',
    why: 'The LCM of 4 and 10. Mr Bowen runs 2 laps. The cat runs 5.',
    whyVn: 'BCNN của 4 và 10. Thầy Bowen chạy 2 vòng. Con mèo chạy 5 vòng.',
    source: 'deck 1.3 s2 (adapted)',
    check: 'lcm(10, 4)',
  },
]
