// content/banks/y7-math/U02_1.js
// Maths 2.1 · Constructing expressions. Schema and house rules: bank.js.
//
// The English is the maths here, so most questions are words. The traps are
// the deck's: "h less than t" is t − h, "subtract from 4" starts at 4, "the
// result" is the part you built first, and c − 50 is a finished answer. A
// letter represents a number, never a thing. Where the English phrase is the
// question, the Vietnamese keeps it in English, as the deck does. A translation
// has nothing to recompute, so almost nothing here carries a `check`: a check
// that restates the answer would only make the count look better.
export const QUESTIONS = [
  {
    id: 'm2.1-01',
    unit: '2.1',
    level: 1,
    kind: 'words',
    q: 'Which one is an expression: 4m or y = 5x?',
    qVn: 'Cái nào là biểu thức: 4m hay y = 5x?',
    a: '4m',
    aVn: '4m',
    why: 'An expression has no = sign. y = 5x has one, so it is a formula.',
    whyVn: 'Biểu thức không có dấu =. y = 5x có dấu =, nên nó là một công thức.',
    source: 'jeopardy maths-u2 · Expressions & Formulae 100',
  },
  {
    id: 'm2.1-02',
    unit: '2.1',
    level: 1,
    kind: 'words',
    q: 'Mr Bowen has n pens. What does n represent: a pen, or the number of pens?',
    qVn: 'Thầy Bowen có n cây bút. n đại diện cho cái gì: một cây bút, hay số cây bút?',
    a: 'The number of pens',
    aVn: 'Số cây bút',
    why: 'A letter represents a number, not a thing.',
    whyVn: 'Chữ cái đại diện cho một con số, không phải một đồ vật.',
    source: 'deck 2.1 s3 (adapted)',
  },
  {
    id: 'm2.1-03',
    unit: '2.1',
    level: 1,
    kind: 'calc',
    q: 'Write 6 × m × n the short way.',
    qVn: 'Viết 6 × m × n theo cách ngắn.',
    a: '6mn',
    aVn: '6mn',
    why: 'Algebra drops the × sign, and only the × sign.',
    whyVn: 'Đại số lược bỏ dấu ×, và chỉ lược bỏ dấu × mà thôi.',
    source: 'deck 2.1 s7 (adapted)',
  },
  {
    id: 'm2.1-04',
    unit: '2.1',
    level: 1,
    kind: 'calc',
    q: 'Write p ÷ 3 the short way.',
    qVn: 'Viết p ÷ 3 theo cách ngắn.',
    a: 'p/3',
    aVn: 'p/3',
    why: 'Algebra writes ÷ as a fraction: p over 3.',
    whyVn: 'Đại số viết phép chia thành phân số: p trên 3.',
    source: 'deck 2.1 s7',
  },
  {
    id: 'm2.1-05',
    unit: '2.1',
    level: 1,
    kind: 'words',
    q: 'A cup holds c ml of coffee. Mr Bowen drinks 50 ml. Write an expression for what is left.',
    qVn: 'Một cốc chứa c ml cà phê. Thầy Bowen uống 50 ml. Hãy viết biểu thức cho lượng còn lại.',
    a: 'c − 50',
    aVn: 'c − 50',
    why: 'That is the finished answer. Nobody has told you c, so you stop there.',
    whyVn: 'Đó là đáp án hoàn chỉnh. Chưa ai cho em biết c, nên em dừng ở đó.',
    source: 'deck 2.1 s4',
  },
  {
    id: 'm2.1-06',
    unit: '2.1',
    level: 1,
    kind: 'words',
    q: 'A box holds t toys. Mr Bowen takes 5 toys out. Write an expression for the number of toys left.',
    qVn: 'Một hộp có t món đồ chơi. Thầy Bowen lấy ra 5 món. Hãy viết biểu thức cho số đồ chơi còn lại.',
    a: 't − 5',
    aVn: 't − 5',
    source: 'WB 2.1 ex 4 (adapted)',
  },
  {
    id: 'm2.1-07',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'A bottle holds w ml of water. A jug holds five times as much as the bottle. Write an expression for the jug.',
    qVn: 'Một cái chai chứa w ml nước. Một cái bình chứa lượng nước gấp năm lần cái chai. Hãy viết biểu thức cho cái bình.',
    a: '5w',
    aVn: '5w',
    why: 'Times as much means multiply. The number goes in front: 5w, not w5.',
    whyVn: 'Times as much nghĩa là nhân. Số đứng trước chữ cái: 5w, không phải w5.',
    source: 'deck 2.1 s10 (adapted)',
  },
  {
    id: 'm2.1-08',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen\'s red box holds r grams of salt. His blue box holds 25 grams more than the red box. Write an expression for the blue box.',
    qVn: 'Hộp đỏ của thầy Bowen chứa r gam muối. Hộp xanh chứa nhiều hơn hộp đỏ 25 gam. Hãy viết biểu thức cho hộp xanh.',
    a: 'r + 25',
    aVn: 'r + 25',
    source: 'hw06 A2a (adapted)',
  },
  {
    id: 'm2.1-09',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'A big jar holds k sweets. A small jar holds half as many as the big jar. Write an expression for the small jar.',
    qVn: 'Một hũ lớn có k viên kẹo. Một hũ nhỏ có số kẹo bằng một nửa hũ lớn. Hãy viết biểu thức cho hũ nhỏ.',
    a: 'k/2',
    aVn: 'k/2',
    why: 'Half as many means divide by 2.',
    whyVn: 'Half as many nghĩa là chia cho 2.',
    source: 'WB 2.1 ex 5 (adapted)',
  },
  {
    id: 'm2.1-10',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'A bus has s seats. A minibus has 20 fewer seats than the bus. Write an expression for the minibus.',
    qVn: 'Một xe buýt có s ghế. Một xe buýt nhỏ có ít hơn xe buýt 20 ghế. Hãy viết biểu thức cho xe buýt nhỏ.',
    a: 's − 20',
    aVn: 's − 20',
    why: 'Fewer than means subtract. Start from s.',
    whyVn: 'Fewer than nghĩa là trừ. Bắt đầu từ s.',
    source: 'WB 2.1 ex 5 (adapted)',
  },
  {
    id: 'm2.1-11',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'Write "7 less than y" in algebra.',
    qVn: 'Viết "7 less than y" bằng đại số.',
    a: 'y − 7',
    aVn: 'y − 7',
    why: 'Start at y and take 7 away. Not 7 − y.',
    whyVn: 'Bắt đầu từ y rồi bớt đi 7. Không phải 7 − y.',
    source: 'deck 2.1 s14 (adapted)',
  },
  {
    id: 'm2.1-12',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'Write "h less than t" in algebra.',
    qVn: 'Viết "h less than t" bằng đại số.',
    a: 't − h',
    aVn: 't − h',
    why: 'Write the starting number first. 5 less than 12 is 12 − 5 = 7.',
    whyVn: 'Viết số ban đầu trước. 5 less than 12 là 12 − 5 = 7.',
    source: 'jeopardy maths-u2 · Expressions & Formulae 300',
  },
  {
    id: 'm2.1-13',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: '"Multiply x by 7, then subtract 3." Write the expression.',
    qVn: '"Multiply x by 7, then subtract 3." Hãy viết biểu thức.',
    a: '7x − 3',
    aVn: '7x − 3',
    source: 'hw06 A3a',
  },
  {
    id: 'm2.1-14',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen thinks of a number, n. He multiplies it by 3, then subtracts 2. Write an expression.',
    qVn: 'Thầy Bowen nghĩ ra một số n. "He multiplies it by 3, then subtracts 2." Hãy viết biểu thức.',
    a: '3n − 2',
    aVn: '3n − 2',
    source: 'q1rev B2c',
  },
  {
    id: 'm2.1-15',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen thinks of a number, n. He divides it by 5, then adds 9. Write an expression.',
    qVn: 'Thầy Bowen nghĩ ra một số n. "He divides it by 5, then adds 9." Hãy viết biểu thức.',
    a: 'n/5 + 9',
    aVn: 'n/5 + 9',
    why: 'Divide first, then add: n/5, then + 9.',
    whyVn: 'Chia trước, rồi cộng: n/5, rồi + 9.',
    source: 'q1rev B2d',
  },
  {
    id: 'm2.1-16',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen thinks of a number, n. He subtracts 5 from it. Write an expression.',
    qVn: 'Thầy Bowen nghĩ ra một số n. "He subtracts 5 from it." Hãy viết biểu thức.',
    a: 'n − 5',
    aVn: 'n − 5',
    why: '"From it" means you start at n.',
    whyVn: '"From it" nghĩa là bắt đầu từ n.',
    source: 'q1rev B2a',
  },
  {
    id: 'm2.1-17',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'One rice dish costs r thousand dong. One drink costs d thousand dong. Mr Bowen buys 3 rice dishes and 2 drinks. Write an expression for the total cost.',
    qVn: 'Một đĩa cơm giá r nghìn đồng. Một ly nước giá d nghìn đồng. Thầy Bowen mua 3 đĩa cơm và 2 ly nước. Hãy viết biểu thức cho tổng số tiền.',
    a: '3r + 2d',
    aVn: '3r + 2d',
    why: 'Two different prices, so two different letters. Not 5rd.',
    whyVn: 'Hai giá khác nhau, nên dùng hai chữ cái khác nhau. Không phải 5rd.',
    source: 'WB 2.1 ex 8 (adapted)',
  },
  {
    id: 'm2.1-18',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'A tall glass holds t ml. A short glass holds s ml. The tall glass holds more. Write an expression for the difference.',
    qVn: 'Một ly cao chứa t ml. Một ly thấp chứa s ml. Ly cao chứa nhiều hơn. Hãy viết biểu thức cho hiệu (difference).',
    a: 't − s',
    aVn: 't − s',
    why: 'Difference means subtract. Start with the bigger amount.',
    whyVn: 'Difference (hiệu) nghĩa là trừ. Bắt đầu từ lượng lớn hơn.',
    source: 'deck 2.1 s11 (adapted)',
  },
  {
    id: 'm2.1-19',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'Describe 4n + 1 in words.',
    qVn: 'Mô tả 4n + 1 bằng lời.',
    a: 'Multiply n by 4, then add 1',
    aVn: 'Nhân n với 4, rồi cộng 1',
    why: 'The multiplying comes first, so you say it first.',
    whyVn: 'Phép nhân làm trước, nên em nói nó trước.',
    source: 'WB 2.1 ex 12 (adapted)',
  },
  {
    id: 'm2.1-20',
    unit: '2.1',
    level: 2,
    kind: 'words',
    q: 'Is 8 + 5 = 13 an expression?',
    qVn: '8 + 5 = 13 có phải là một biểu thức không?',
    a: 'No',
    aVn: 'Không',
    why: 'It has an = sign. It has no letter either.',
    whyVn: 'Nó có dấu =. Nó cũng không có chữ cái nào.',
    source: 'hw06 A1',
  },
  {
    id: 'm2.1-21',
    unit: '2.1',
    level: 2,
    kind: 'calc',
    q: 'Write y × 8 the short way.',
    qVn: 'Viết y × 8 theo cách ngắn.',
    a: '8y',
    aVn: '8y',
    why: 'The number goes in front: 8y, never y8.',
    whyVn: 'Số đứng trước chữ cái: 8y, không bao giờ viết y8.',
    source: 'hw06x E3 (adapted)',
  },
  {
    id: 'm2.1-22',
    unit: '2.1',
    level: 3,
    kind: 'words',
    q: 'Write "m more than four times n" in algebra.',
    qVn: 'Viết "m more than four times n" bằng đại số.',
    a: '4n + m',
    aVn: '4n + m',
    why: 'Build "four times n" first: 4n. Then add m to it.',
    whyVn: 'Dựng "four times n" trước: 4n. Rồi cộng thêm m.',
    source: 'deck 2.1 s14 (adapted)',
  },
  {
    id: 'm2.1-23',
    unit: '2.1',
    level: 3,
    kind: 'words',
    q: '"Multiply x by 5, then subtract from 4." Write the expression.',
    qVn: '"Multiply x by 5, then subtract from 4." Hãy viết biểu thức.',
    a: '4 − 5x',
    aVn: '4 − 5x',
    why: '"From 4" means you start at 4. "Subtract 4" would be 5x − 4.',
    whyVn: '"From 4" nghĩa là bắt đầu từ 4. "Subtract 4" mới là 5x − 4.',
    source: 'jeopardy maths-u2 · Expressions & Formulae 400',
  },
  {
    id: 'm2.1-24',
    unit: '2.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen thinks of a number, n. He multiplies it by 2, then subtracts the result from 40. Write an expression.',
    qVn: 'Thầy Bowen nghĩ ra một số n. "He multiplies it by 2, then subtracts the result from 40." Hãy viết biểu thức.',
    a: '40 − 2n',
    aVn: '40 − 2n',
    why: '"The result" is 2n. "From 40" means start at 40. Not 2n − 40.',
    whyVn: '"The result" là 2n. "From 40" nghĩa là bắt đầu từ 40. Không phải 2n − 40.',
    source: 'q1rev B2e',
  },
  {
    id: 'm2.1-25',
    unit: '2.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen says 9 − 2m means "Multiply m by 2, then subtract 9." Is he right?',
    qVn: 'Thầy Bowen nói 9 − 2m nghĩa là "Multiply m by 2, then subtract 9." Thầy nói đúng không?',
    a: 'No',
    aVn: 'Không',
    why: 'His words give 2m − 9. For 9 − 2m, he needs "subtract the result from 9".',
    whyVn: 'Câu của thầy cho ra 2m − 9. Muốn có 9 − 2m, thầy cần "subtract the result from 9".',
    source: 'hw06 A3f',
    check: 'yes(val("2m - 9", {m: 1}) === val("9 - 2m", {m: 1}))',
  },
  {
    id: 'm2.1-26',
    unit: '2.1',
    level: 3,
    kind: 'words',
    q: 'Describe 10 − k in words. Use the word "subtract".',
    qVn: 'Mô tả 10 − k bằng lời. Dùng từ "subtract".',
    a: 'Subtract k from 10',
    aVn: 'Subtract k from 10 (lấy mười trừ đi k)',
    why: 'Not "10 less than k". That would be k − 10.',
    whyVn: 'Không phải "10 less than k". Câu đó là k − 10.',
    source: 'deck 2.1 s19 (adapted)',
  },
  {
    id: 'm2.1-27',
    unit: '2.1',
    level: 3,
    kind: 'words',
    q: 'A sealed syringe holds v ml of air. Mr Bowen pushes until half is left. Then he pushes 10 ml further. Write an expression for the air now.',
    qVn: 'Một ống tiêm bịt kín chứa v ml không khí. Thầy Bowen đẩy đến khi chỉ còn một nửa. Rồi thầy đẩy thêm 10 ml nữa. Hãy viết biểu thức cho lượng không khí bây giờ.',
    a: 'v/2 − 10',
    aVn: 'v/2 − 10',
    why: 'Half first, then take 10 away.',
    whyVn: 'Lấy một nửa trước, rồi bớt đi 10.',
    source: 'deck 2.1 s20 (adapted)',
  },
  {
    id: 'm2.1-28',
    unit: '2.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen puts n ice cubes in a glass and adds 3 more. He answers the door and comes back 40 minutes later. Write an expression for the ice cubes now.',
    qVn: 'Thầy Bowen bỏ n viên đá vào một cái cốc rồi bỏ thêm 3 viên. Thầy ra mở cửa, 40 phút sau mới quay lại. Hãy viết biểu thức cho số viên đá bây giờ.',
    a: '0',
    aVn: '0',
    why: 'They melted. The water is all still there, but it is not ice.',
    whyVn: 'Chúng đã tan hết. Nước thì vẫn còn nguyên, nhưng không còn là đá.',
    source: 'deck 2.1 s21 (adapted)',
  },
  {
    id: 'm2.1-29',
    unit: '2.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen has b books. He reads 3 of them. Write an expression for the number of books he has now.',
    qVn: 'Thầy Bowen có b cuốn sách. Thầy đọc 3 cuốn trong số đó. Hãy viết biểu thức cho số sách thầy có bây giờ.',
    a: 'b',
    aVn: 'b',
    why: 'Reading a book does not make it go away. One letter on its own is an answer.',
    whyVn: 'Đọc sách không làm cuốn sách biến mất. Một chữ cái đứng một mình cũng là đáp án.',
    source: 'WB 2.1 ex 6 (adapted)',
  },
  {
    id: 'm2.1-30',
    unit: '2.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen has p pairs of socks. A pair is 2 socks. He loses 1 sock. Write an expression for the number of socks he has.',
    qVn: 'Thầy Bowen có p đôi tất. Một đôi là 2 chiếc. Thầy làm mất 1 chiếc. Hãy viết biểu thức cho số chiếc tất thầy có.',
    a: '2p − 1',
    aVn: '2p − 1',
    why: 'p pairs is 2p socks. Then take 1 away.',
    whyVn: 'p đôi là 2p chiếc. Rồi bớt đi 1.',
    source: 'WB 2.1 ex 10 (adapted)',
  },
]
