// content/banks/y7-math/U02_6.js
// Maths 2.6 · Inequalities. Schema and house rules: bank.js.
//
// The class has known < and > since Grade 1. The unit is the English: read
// left to right as a full sentence with "is", and the other words a word
// problem uses (under, below, fewer than for <; over, above, more than for >).
// The traps are the deck's: the circle's own number does not work (x > 3, so
// the smallest integer is 4, not 3), and less than means further LEFT, even
// below zero (t < −2 gives −3, −4, −5, …). Every inequality is strict: 2.6
// never taught ≤, ≥ or a closed circle. Two conditions are written as two
// inequalities joined by "and". The bank is text only, so the one number line
// is described in words.
export const QUESTIONS = [
  {
    id: 'm2.6-01',
    unit: '2.6',
    level: 1,
    kind: 'words',
    q: 'Say it in English: −3 < 2',
    qVn: 'Đọc bằng tiếng Anh: −3 < 2',
    a: '−3 is less than 2',
    aVn: '−3 is less than 2',
    why: 'Read it from left to right.',
    whyVn: 'Đọc từ trái sang phải.',
    source: 'jeopardy maths-u2 · Inequalities 100',
  },
  {
    id: 'm2.6-02',
    unit: '2.6',
    level: 1,
    kind: 'words',
    q: 'On a number line, what does an open circle mean?',
    qVn: 'Trên trục số, vòng tròn rỗng nghĩa là gì?',
    a: 'That number is not included',
    aVn: 'Số đó không được tính',
    why: 'x > 3: the open circle is at 3, and 3 does not work.',
    whyVn: 'x > 3: vòng tròn rỗng ở số 3, và 3 không thỏa mãn.',
    source: 'deck 2.6 s10',
  },
  {
    id: 'm2.6-03',
    unit: '2.6',
    level: 1,
    kind: 'words',
    q: 'On a number line, is "less than" further left or further right?',
    qVn: 'Trên trục số, "less than" nằm xa hơn về bên trái hay bên phải?',
    a: 'Further left',
    aVn: 'Xa hơn về bên trái',
    why: 'Even below zero: −5 is less than −2.',
    whyVn: 'Kể cả khi dưới 0: −5 nhỏ hơn −2.',
    source: 'deck 2.6 s18',
  },
  {
    id: 'm2.6-04',
    unit: '2.6',
    level: 1,
    kind: 'calc',
    q: 'Write < or > in the box: −7 □ −4',
    qVn: 'Viết < hoặc > vào ô trống: −7 □ −4',
    a: '−7 < −4',
    aVn: '−7 < −4',
    why: '−7 is further left, so it is less. It is colder.',
    whyVn: '−7 nằm xa hơn về bên trái, nên nó nhỏ hơn. Nó lạnh hơn.',
    source: 'deck 2.6 s1 (adapted)',
    check: '(-7 < -4) ? "<" : ">"',
  },
  {
    id: 'm2.6-05',
    unit: '2.6',
    level: 1,
    kind: 'words',
    q: 'Write "m is greater than −7" as an inequality.',
    qVn: 'Viết "m is greater than −7" thành bất đẳng thức.',
    a: 'm > −7',
    aVn: 'm > −7',
    source: 'deck 2.6 s8 (adapted)',
  },
  {
    id: 'm2.6-06',
    unit: '2.6',
    level: 1,
    kind: 'words',
    q: 'Is −6 an integer?',
    qVn: '−6 có phải là số nguyên không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'An integer can be negative, 0 or positive.',
    whyVn: 'Số nguyên có thể âm, bằng 0 hoặc dương.',
    source: 'deck 2.6 s7 (adapted)',
    check: 'yes(Number.isInteger(-6))',
  },
  {
    id: 'm2.6-07',
    unit: '2.6',
    level: 2,
    kind: 'words',
    q: '"Under 18 years old." Is that less than, or greater than? Write it with a for age.',
    qVn: '"Under 18 years old." Đó là nhỏ hơn hay lớn hơn? Viết bằng chữ a cho tuổi.',
    a: 'Less than: a < 18',
    aVn: 'Nhỏ hơn: a < 18',
    why: 'Under, below and fewer than all mean <.',
    whyVn: 'Under, below và fewer than đều nghĩa là <.',
    source: 'jeopardy maths-u2 · Inequalities 200',
  },
  {
    id: 'm2.6-08',
    unit: '2.6',
    level: 2,
    kind: 'words',
    q: 'Say it in English: k > −6',
    qVn: 'Đọc bằng tiếng Anh: k > −6',
    a: 'k is greater than −6',
    aVn: 'k is greater than −6',
    why: 'A full sentence, with "is". Read it from left to right.',
    whyVn: 'Một câu đầy đủ, có "is". Đọc từ trái sang phải.',
    source: 'deck 2.6 s9 (adapted)',
  },
  {
    id: 'm2.6-09',
    unit: '2.6',
    level: 2,
    kind: 'words',
    q: 'Which two of these words mean <: under, over, below, above?',
    qVn: 'Hai từ nào trong số này nghĩa là <: under, over, below, above?',
    a: 'Under and below',
    aVn: 'Under và below',
    why: 'Over and above mean >.',
    whyVn: 'Over và above nghĩa là >.',
    source: 'deck 2.6 s4',
  },
  {
    id: 'm2.6-10',
    unit: '2.6',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen\'s soup is above 70 °C. Write this as an inequality. Use t.',
    qVn: 'Món súp của thầy Bowen có nhiệt độ "above 70 °C". Viết thành bất đẳng thức. Dùng chữ t.',
    a: 't > 70',
    aVn: 't > 70',
    why: '"Above" means greater than.',
    whyVn: '"Above" nghĩa là lớn hơn.',
    source: 'deck 2.6 s4 (adapted)',
  },
  {
    id: 'm2.6-11',
    unit: '2.6',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen has fewer than 9 pens. Write this as an inequality. Use p.',
    qVn: 'Thầy Bowen có "fewer than 9" cây bút. Viết thành bất đẳng thức. Dùng chữ p.',
    a: 'p < 9',
    aVn: 'p < 9',
    why: '"Fewer than" means less than.',
    whyVn: '"Fewer than" nghĩa là nhỏ hơn.',
    source: 'hw08 C3 (adapted)',
  },
  {
    id: 'm2.6-12',
    unit: '2.6',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen has more than 5 cats. How many cats could he have?',
    qVn: 'Thầy Bowen có nhiều hơn 5 con mèo. Thầy có thể có bao nhiêu con mèo?',
    a: '6, 7, 8, …',
    aVn: '6, 7, 8, …',
    why: 'An inequality can have many answers. Not 5, and not 5.5.',
    whyVn: 'Bất đẳng thức có thể có nhiều đáp án. Không phải 5, cũng không phải 5.5.',
    source: 'deck 2.6 s5 (adapted)',
    check: 'first("c > 5", 3)',
  },
  {
    id: 'm2.6-13',
    unit: '2.6',
    level: 2,
    kind: 'words',
    q: 'Which of these are integers: −3, 0, 1.5, 8?',
    qVn: 'Số nào trong các số này là số nguyên: −3, 0, 1.5, 8?',
    a: '−3, 0 and 8',
    aVn: '−3, 0 và 8',
    why: 'An integer is a whole number. 1.5 is not.',
    whyVn: 'Số nguyên không có phần thập phân. 1.5 thì không phải.',
    source: 'deck 2.6 s7 (adapted)',
    check: '[-3, 0, 1.5, 8].filter(Number.isInteger)',
  },
  {
    id: 'm2.6-14',
    unit: '2.6',
    level: 2,
    kind: 'words',
    q: 'A number line has an open circle at 4 and an arrow to the left. Write the inequality. Use x.',
    qVn: 'Một trục số có vòng tròn rỗng ở số 4 và mũi tên sang trái. Viết bất đẳng thức. Dùng chữ x.',
    a: 'x < 4',
    aVn: 'x < 4',
    why: 'Arrow to the left: less than. The circle is open, so 4 is not included.',
    whyVn: 'Mũi tên sang trái: nhỏ hơn. Vòng tròn rỗng, nên không tính 4.',
    source: 'deck 2.6 s14 (adapted)',
  },
  {
    id: 'm2.6-15',
    unit: '2.6',
    level: 2,
    kind: 'calc',
    q: 'x > 11. What is the smallest integer x could be?',
    qVn: 'x > 11. Số nguyên nhỏ nhất mà x có thể là bao nhiêu?',
    a: '12',
    aVn: '12',
    why: '11 is not greater than 11.',
    whyVn: '11 không lớn hơn 11.',
    source: 'deck 2.6 s21 (adapted)',
    check: 'least("x > 11")',
  },
  {
    id: 'm2.6-16',
    unit: '2.6',
    level: 2,
    kind: 'calc',
    q: 'y < 9. What is the largest integer y could be?',
    qVn: 'y < 9. Số nguyên lớn nhất mà y có thể là bao nhiêu?',
    a: '8',
    aVn: '8',
    why: '9 is not less than 9.',
    whyVn: '9 không nhỏ hơn 9.',
    source: 'deck 2.6 s13 (adapted)',
    check: 'greatest("y < 9")',
  },
  {
    id: 'm2.6-17',
    unit: '2.6',
    level: 2,
    kind: 'calc',
    q: 'r > −4. What is the smallest integer r could be?',
    qVn: 'r > −4. Số nguyên nhỏ nhất mà r có thể là bao nhiêu?',
    a: '−3',
    aVn: '−3',
    why: 'Greater than means further right: −3 is to the right of −4.',
    whyVn: 'Lớn hơn nghĩa là xa hơn về bên phải: −3 ở bên phải −4.',
    source: 'deck 2.6 s20 (adapted)',
    check: 'least("r > -4")',
  },
  {
    id: 'm2.6-18',
    unit: '2.6',
    level: 2,
    kind: 'calc',
    q: 'n < 1. What is the largest integer n could be?',
    qVn: 'n < 1. Số nguyên lớn nhất mà n có thể là bao nhiêu?',
    a: '0',
    aVn: '0',
    why: '0 is an integer, and it is less than 1.',
    whyVn: '0 là một số nguyên, và nó nhỏ hơn 1.',
    source: 'hw08 C5 (adapted)',
    check: 'greatest("n < 1")',
  },
  {
    id: 'm2.6-19',
    unit: '2.6',
    level: 2,
    kind: 'calc',
    q: 'x > 8. Could x be 8?',
    qVn: 'x > 8. x có thể là 8 không?',
    a: 'No',
    aVn: 'Không',
    why: '8 is not greater than 8.',
    whyVn: '8 không lớn hơn 8.',
    source: 'deck 2.6 s16 (adapted)',
    check: 'yes(8 > 8)',
  },
  {
    id: 'm2.6-20',
    unit: '2.6',
    level: 2,
    kind: 'calc',
    q: 'k < 1. Could k be −50?',
    qVn: 'k < 1. k có thể là −50 không?',
    a: 'Yes',
    aVn: 'Có',
    why: '−50 is less than 1. It is far to the left.',
    whyVn: '−50 nhỏ hơn 1. Nó nằm rất xa về bên trái.',
    source: 'deck 2.6 s16 (adapted)',
    check: 'yes(-50 < 1)',
  },
  {
    id: 'm2.6-21',
    unit: '2.6',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen writes "n is less than 12" as n > 12. What should it be?',
    qVn: 'Thầy Bowen viết "n is less than 12" thành n > 12. Đúng ra phải là gì?',
    a: 'n < 12',
    aVn: 'n < 12',
    why: '"Less than" is <. The small end points at the smaller number.',
    whyVn: '"Less than" là <. Đầu nhỏ chỉ vào số nhỏ hơn.',
    source: 'deck 2.6 s22 (adapted)',
  },
  {
    id: 'm2.6-22',
    unit: '2.6',
    level: 3,
    kind: 'calc',
    q: 'x > 6. The smallest integer x could be: is it A: 7, or B: 6?',
    qVn: 'x > 6. Số nguyên nhỏ nhất mà x có thể là: A: 7, hay B: 6?',
    a: 'A: 7',
    aVn: 'A: 7',
    why: 'Is 6 greater than 6? No. The circle is open.',
    whyVn: '6 có lớn hơn 6 không? Không. Vòng tròn rỗng.',
    source: 'deck 2.6 s11 (adapted)',
    check: 'least("x > 6")',
  },
  {
    id: 'm2.6-23',
    unit: '2.6',
    level: 3,
    kind: 'calc',
    q: 'q < −8. What is the largest integer q could be?',
    qVn: 'q < −8. Số nguyên lớn nhất mà q có thể là bao nhiêu?',
    a: '−9',
    aVn: '−9',
    why: 'Less than means further left. −7 is greater than −8.',
    whyVn: 'Nhỏ hơn nghĩa là xa hơn về bên trái. −7 lớn hơn −8.',
    source: 'q1rev B9c (adapted)',
    check: 'greatest("q < -8")',
  },
  {
    id: 'm2.6-24',
    unit: '2.6',
    level: 3,
    kind: 'calc',
    q: 'p > 9.5. What is the smallest integer p could be?',
    qVn: 'p > 9.5. Số nguyên nhỏ nhất mà p có thể là bao nhiêu?',
    a: '10',
    aVn: '10',
    why: 'The circle sits at 9.5, so the next integer is 10. Not 9.5, and not 9.',
    whyVn: 'Vòng tròn nằm ở 9.5, nên số nguyên kế tiếp là 10. Không phải 9.5, cũng không phải 9.',
    source: 'deck 2.6 s21 (adapted)',
    check: 'least("p > 9.5")',
  },
  {
    id: 'm2.6-25',
    unit: '2.6',
    level: 3,
    kind: 'calc',
    q: 't < −2. Which integers could t be?',
    qVn: 't < −2. t có thể là những số nguyên nào?',
    a: '−3, −4, −5, …',
    aVn: '−3, −4, −5, …',
    why: 'Less than means further left. −1 is greater than −2.',
    whyVn: 'Nhỏ hơn nghĩa là xa hơn về bên trái. −1 lớn hơn −2.',
    source: 'jeopardy maths-u2 · Inequalities 400',
    check: 'first("t < -2", 3)',
  },
  {
    id: 'm2.6-26',
    unit: '2.6',
    level: 3,
    kind: 'words',
    q: 'm > −3. Mr Bowen says the smallest integer m could be is −4. Is he right?',
    qVn: 'm > −3. Thầy Bowen nói số nguyên nhỏ nhất mà m có thể là −4. Thầy nói đúng không?',
    a: 'No. It is −2.',
    aVn: 'Không. Đó là −2.',
    why: '−4 is less than −3. Greater than goes right.',
    whyVn: '−4 nhỏ hơn −3. Lớn hơn là đi sang phải.',
    source: 'deck 2.6 s22 (adapted)',
    check: 'least("m > -3")',
  },
  {
    id: 'm2.6-27',
    unit: '2.6',
    level: 3,
    kind: 'calc',
    q: 'x is an integer. x > −2 and x < 3. List all the values x could be.',
    qVn: 'x là số nguyên. x > −2 và x < 3. Liệt kê tất cả các giá trị x có thể nhận.',
    a: '−1, 0, 1, 2',
    aVn: '−1, 0, 1, 2',
    why: '−2 and 3 are not included.',
    whyVn: 'Không tính −2 và 3.',
    source: 'q1rev B9d (adapted)',
    check: 'ints(-2, 3)',
  },
  {
    id: 'm2.6-28',
    unit: '2.6',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen\'s class has more than 20 students. It has fewer than 24 students. How many students could there be?',
    qVn: 'Lớp của thầy Bowen có nhiều hơn 20 học sinh. Lớp có ít hơn 24 học sinh. Lớp có thể có bao nhiêu học sinh?',
    a: '21, 22 or 23',
    aVn: '21, 22 hoặc 23',
    why: 's > 20 and s < 24. Not 20, and not 24.',
    whyVn: 's > 20 và s < 24. Không phải 20, cũng không phải 24.',
    source: 'jeopardy maths-u2 · Inequalities 500',
    check: 'ints(20, 24)',
  },
  {
    id: 'm2.6-29',
    unit: '2.6',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen has fewer than 1 cat. He has more than −1 cats. How many cats does Mr Bowen have?',
    qVn: 'Thầy Bowen có ít hơn 1 con mèo. Thầy có nhiều hơn −1 con mèo. Thầy Bowen có bao nhiêu con mèo?',
    a: '0 cats',
    aVn: '0 con mèo',
    why: 'c < 1 and c > −1. The only integer is 0.',
    whyVn: 'c < 1 và c > −1. Số nguyên duy nhất là 0.',
    source: 'deck 2.6 s24',
    check: 'ints(-1, 1)',
  },
  {
    id: 'm2.6-30',
    unit: '2.6',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen thinks of an integer. It is greater than 7. It is less than 8. What is Mr Bowen\'s number?',
    qVn: 'Thầy Bowen nghĩ ra một số nguyên. Nó lớn hơn 7. Nó nhỏ hơn 8. Số của thầy Bowen là số nào?',
    a: 'No integer works',
    aVn: 'Không có số nguyên nào thỏa mãn',
    why: 'n > 7 and n < 8. Mr Bowen should think again.',
    whyVn: 'n > 7 và n < 8. Thầy Bowen nên nghĩ lại.',
    source: 'deck 2.6 s25',
    check: 'ints(7, 8).length === 0 ? "No" : "Yes"',
  },
]
