// content/banks/y7-math/U02_3.js
// Maths 2.3 · Collecting like terms. Schema and house rules: bank.js.
//
// The traps are the deck's: x means 1x, so 8s − s is 7s and not 8; only like
// terms collect, so 5t + 5 is already finished; ab and ba are like terms, x
// and x² are not; and every sign moves with its own term. "Like" means the
// same kind, never "I like mangoes". A letter is a number, never a fruit, and
// answers put the letter terms first and the number last, as the deck does.
export const QUESTIONS = [
  {
    id: 'm2.3-01',
    unit: '2.3',
    level: 1,
    kind: 'calc',
    q: 'Simplify 4c + 5c.',
    qVn: 'Rút gọn 4c + 5c.',
    a: '9c',
    aVn: '9c',
    source: 'WB 2.3 ex 7 (adapted)',
    check: 'simplify("4c + 5c")',
  },
  {
    id: 'm2.3-02',
    unit: '2.3',
    level: 1,
    kind: 'calc',
    q: 'Simplify m + m + m.',
    qVn: 'Rút gọn m + m + m.',
    a: '3m',
    aVn: '3m',
    source: 'WB 2.3 ex 7 (adapted)',
    check: 'simplify("m + m + m")',
  },
  {
    id: 'm2.3-03',
    unit: '2.3',
    level: 1,
    kind: 'words',
    q: 'How many terms are in y + 2z − 5 + 3y?',
    qVn: 'Biểu thức y + 2z − 5 + 3y có bao nhiêu hạng tử?',
    a: '4',
    aVn: '4',
    why: 'The + and − signs separate the terms. A number on its own is a term too.',
    whyVn: 'Các dấu + và − ngăn cách các hạng tử. Một số đứng một mình cũng là hạng tử.',
    source: 'hw07 A1',
    check: '"y + 2z - 5 + 3y".split(/[+-]/).length',
  },
  {
    id: 'm2.3-04',
    unit: '2.3',
    level: 1,
    kind: 'words',
    q: 'Are 6m and 9m like terms?',
    qVn: '6m và 9m có phải là hạng tử đồng dạng không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'They have the same letter. Look at the letter, not the number.',
    whyVn: 'Chúng có cùng chữ cái. Nhìn vào chữ cái, không nhìn con số.',
    source: 'deck 2.3 s8 (adapted)',
    check: 'yes("6m".replace(/[^a-z]/g, "") === "9m".replace(/[^a-z]/g, ""))',
  },
  {
    id: 'm2.3-05',
    unit: '2.3',
    level: 1,
    kind: 'words',
    q: 'In maths, what does "simplify" mean?',
    qVn: 'Trong toán, "simplify" nghĩa là gì?',
    a: 'Write it in a shorter way',
    aVn: 'Rút gọn: viết ngắn gọn hơn',
    why: 'a + a + a = 3a. The same value, written shorter.',
    whyVn: 'a + a + a = 3a. Cùng một giá trị, viết ngắn hơn.',
    source: 'deck 2.3 s9',
  },
  {
    id: 'm2.3-06',
    unit: '2.3',
    level: 1,
    kind: 'calc',
    q: 'Simplify 8s − s.',
    qVn: 'Rút gọn 8s − s.',
    a: '7s',
    aVn: '7s',
    why: 's means 1s. The letter never disappears. Not 8.',
    whyVn: 's nghĩa là 1s. Chữ cái không bao giờ biến mất. Không phải 8.',
    source: 'jeopardy maths-u2 · Like Terms 100',
    check: 'simplify("8s - s")',
  },
  {
    id: 'm2.3-07',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'In "like terms", what does "like" mean?',
    qVn: 'Trong "like terms", từ "like" nghĩa là gì?',
    a: 'The same kind',
    aVn: 'Cùng loại',
    why: 'Terms with the same letter, like 2a and 5a. Not "I like mangoes".',
    whyVn: 'Các hạng tử có cùng chữ cái, như 2a và 5a. Không phải "thích" như trong "I like mangoes".',
    source: 'jeopardy maths-u2 · Like Terms 200',
  },
  {
    id: 'm2.3-08',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'Which pair are like terms: 3a and 2b, 4ab and 3ba, or x and x²?',
    qVn: 'Cặp nào là hạng tử đồng dạng: 3a và 2b, 4ab và 3ba, hay x và x²?',
    a: '4ab and 3ba',
    aVn: '4ab và 3ba',
    why: 'a × b = b × a. But x² means x × x, so it is not like x.',
    whyVn: 'a × b = b × a. Còn x² nghĩa là x × x, nên nó không đồng dạng với x.',
    source: 'jeopardy maths-u2 · Like Terms 300',
  },
  {
    id: 'm2.3-09',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'In "collecting like terms", what does "collect" mean?',
    qVn: 'Trong "collecting like terms", từ "collect" nghĩa là gì?',
    a: 'Put together',
    aVn: 'Gộp lại',
    why: 'Not "collect the books". In maths, 2a + 5a = 7a.',
    whyVn: 'Không phải "collect the books" (thu sách). Trong toán, 2a + 5a = 7a.',
    source: 'deck 2.3 s7',
  },
  {
    id: 'm2.3-10',
    unit: '2.3',
    level: 2,
    kind: 'calc',
    q: 'Simplify 6m + 3n + 2m.',
    qVn: 'Rút gọn 6m + 3n + 2m.',
    a: '8m + 3n',
    aVn: '8m + 3n',
    source: 'hw07 A3c',
    check: 'simplify("6m + 3n + 2m")',
  },
  {
    id: 'm2.3-11',
    unit: '2.3',
    level: 2,
    kind: 'calc',
    q: 'Simplify 4x + x + 2x.',
    qVn: 'Rút gọn 4x + x + 2x.',
    a: '7x',
    aVn: '7x',
    why: 'x means 1x. Not 6x.',
    whyVn: 'x nghĩa là 1x. Không phải 6x.',
    source: 'deck 2.3 s10',
    check: 'simplify("4x + x + 2x")',
  },
  {
    id: 'm2.3-12',
    unit: '2.3',
    level: 2,
    kind: 'calc',
    q: 'Simplify 3a + 2b + 4a + b.',
    qVn: 'Rút gọn 3a + 2b + 4a + b.',
    a: '7a + 3b',
    aVn: '7a + 3b',
    why: 'b means 1b, so 2b + b = 3b.',
    whyVn: 'b nghĩa là 1b, nên 2b + b = 3b.',
    source: 'deck 2.3 s4',
    check: 'simplify("3a + 2b + 4a + b")',
  },
  {
    id: 'm2.3-13',
    unit: '2.3',
    level: 2,
    kind: 'calc',
    q: 'Simplify 4 + 3m + 6.',
    qVn: 'Rút gọn 4 + 3m + 6.',
    a: '3m + 10',
    aVn: '3m + 10',
    why: 'Numbers are like terms: 4 + 6 = 10. Write the letter term first.',
    whyVn: 'Các số là hạng tử đồng dạng: 4 + 6 = 10. Viết hạng tử có chữ cái trước.',
    source: 'hw07 B3 (adapted)',
    check: 'simplify("4 + 3m + 6")',
  },
  {
    id: 'm2.3-14',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'Can 5t + 5 be simplified?',
    qVn: '5t + 5 có rút gọn được không?',
    a: 'No',
    aVn: 'Không',
    why: '5t has a letter. 5 does not. They are not like terms.',
    whyVn: '5t có chữ cái. 5 thì không. Chúng không phải hạng tử đồng dạng.',
    source: 'deck 2.3 s14 (adapted)',
    check: 'yes("5t".replace(/[^a-z]/g, "") === "5".replace(/[^a-z]/g, ""))',
  },
  {
    id: 'm2.3-15',
    unit: '2.3',
    level: 2,
    kind: 'calc',
    q: 'In an algebraic pyramid, each block is the two blocks below it added. The two blocks below are 3a + b and 2a + 4b. What is the top block?',
    qVn: 'Trong kim tự tháp đại số, mỗi ô bằng hai ô bên dưới cộng lại. Hai ô bên dưới là 3a + b và 2a + 4b. Ô trên cùng là gì?',
    a: '5a + 5b',
    aVn: '5a + 5b',
    source: 'deck 2.3 s22 (adapted)',
    check: 'simplify("3a + b + 2a + 4b")',
  },
  {
    id: 'm2.3-16',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'A striped brick is x cm long. A spotted brick is y cm long. A row is striped, spotted, striped, striped. Write its length in simplest form.',
    qVn: 'Một viên gạch sọc dài x cm. Một viên gạch chấm bi dài y cm. Một hàng gồm: sọc, chấm bi, sọc, sọc. Viết chiều dài hàng đó ở dạng gọn nhất.',
    a: '3x + y',
    aVn: '3x + y',
    why: 'x + y + x + x. Collect the three x terms.',
    whyVn: 'x + y + x + x. Gộp ba hạng tử x lại.',
    source: 'WB 2.3 ex 6 (adapted)',
    check: 'simplify("x + y + x + x")',
  },
  {
    id: 'm2.3-17',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen buys n pens on Monday and 4n pens on Tuesday. How many pens does he buy?',
    qVn: 'Thầy Bowen mua n cây bút vào thứ Hai và 4n cây bút vào thứ Ba. Thầy mua tất cả bao nhiêu cây bút?',
    a: '5n',
    aVn: '5n',
    why: 'n means 1n, so n + 4n = 5n.',
    whyVn: 'n nghĩa là 1n, nên n + 4n = 5n.',
    source: 'deck 2.3 s24 (adapted)',
    check: 'simplify("n + 4n")',
  },
  {
    id: 'm2.3-18',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen walks 2k km to the shop and 2k km home. He has forgotten his wallet. He walks there and back again. It was in his pocket. How many km did he walk?',
    qVn: 'Thầy Bowen đi bộ 2k km đến cửa hàng và 2k km về nhà. Thầy quên ví. Thầy lại đi bộ đến đó rồi về. Cái ví ở trong túi áo của thầy. Thầy đã đi bộ bao nhiêu km?',
    a: '8k',
    aVn: '8k',
    why: 'Four trips of 2k. The wallet walked 8k km too.',
    whyVn: 'Bốn chặng, mỗi chặng 2k. Cái ví cũng đã đi 8k km.',
    source: 'deck 2.3 s26 (adapted)',
    check: 'simplify("2k + 2k + 2k + 2k")',
  },
  {
    id: 'm2.3-19',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen simplifies 6y − y and writes 6. He gives himself full marks. What should he have written?',
    qVn: 'Thầy Bowen rút gọn 6y − y và viết 6. Thầy tự chấm điểm tối đa. Lẽ ra thầy phải viết gì?',
    a: '5y',
    aVn: '5y',
    why: 'y means 1y. The letter never disappears.',
    whyVn: 'y nghĩa là 1y. Chữ cái không bao giờ biến mất.',
    source: 'deck 2.3 s23',
    check: 'simplify("6y - y")',
  },
  {
    id: 'm2.3-20',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'Are 5c and −2c like terms?',
    qVn: '5c và −2c có phải là hạng tử đồng dạng không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'Both are c terms. The minus sign belongs to the term, but does not change its kind.',
    whyVn: 'Cả hai đều là hạng tử c. Dấu trừ thuộc về hạng tử, nhưng không làm đổi loại của nó.',
    source: 'hw07 A2',
    check: 'yes("5c".replace(/[^a-z]/g, "") === "-2c".replace(/[^a-z]/g, ""))',
  },
  {
    id: 'm2.3-21',
    unit: '2.3',
    level: 2,
    kind: 'words',
    q: 'An apple weighs a grams. A banana weighs b grams. Mr Bowen buys 4 apples and 3 bananas, then 2 apples and 1 banana. Write the total weight.',
    qVn: 'Một quả táo nặng a gam. Một quả chuối nặng b gam. Thầy Bowen mua 4 quả táo và 3 quả chuối, rồi 2 quả táo và 1 quả chuối. Viết tổng khối lượng.',
    a: '6a + 4b',
    aVn: '6a + 4b',
    why: '4a + 3b + 2a + b. The letters are weights, not fruit.',
    whyVn: '4a + 3b + 2a + b. Chữ cái là khối lượng, không phải trái cây.',
    source: 'deck 2.3 s3 (adapted)',
    check: 'simplify("4a + 3b + 2a + b")',
  },
  {
    id: 'm2.3-22',
    unit: '2.3',
    level: 3,
    kind: 'calc',
    q: 'Simplify 10g − 6g − g.',
    qVn: 'Rút gọn 10g − 6g − g.',
    a: '3g',
    aVn: '3g',
    why: 'g means 1g: 10 − 6 − 1 = 3. Not 4g.',
    whyVn: 'g nghĩa là 1g: 10 − 6 − 1 = 3. Không phải 4g.',
    source: 'hw07 A3i',
    check: 'simplify("10g - 6g - g")',
  },
  {
    id: 'm2.3-23',
    unit: '2.3',
    level: 3,
    kind: 'calc',
    q: 'Simplify 7m + 3 − 2m − 8.',
    qVn: 'Rút gọn 7m + 3 − 2m − 8.',
    a: '5m − 5',
    aVn: '5m − 5',
    why: 'The m terms: 7m − 2m = 5m. The numbers: 3 − 8 = −5.',
    whyVn: 'Các hạng tử m: 7m − 2m = 5m. Các số: 3 − 8 = −5.',
    source: 'q1rev B5e',
    check: 'simplify("7m + 3 - 2m - 8")',
  },
  {
    id: 'm2.3-24',
    unit: '2.3',
    level: 3,
    kind: 'words',
    q: 'A rectangle has two sides of 3x + 2 cm and two sides of x cm. Write its perimeter in simplest form.',
    qVn: 'Một hình chữ nhật có hai cạnh dài 3x + 2 cm và hai cạnh dài x cm. Viết chu vi của nó ở dạng gọn nhất.',
    a: '8x + 4',
    aVn: '8x + 4',
    why: '3x + 2 + x + 3x + 2 + x. Collect the x terms, then the numbers.',
    whyVn: '3x + 2 + x + 3x + 2 + x. Gộp các hạng tử x, rồi gộp các số.',
    source: 'deck 2.3 s24 (adapted)',
    check: 'simplify("3x + 2 + x + 3x + 2 + x")',
  },
  {
    id: 'm2.3-25',
    unit: '2.3',
    level: 3,
    kind: 'calc',
    q: 'In an algebraic pyramid, each block is the two blocks below it added. The bottom row is 3x, 4x, x. What is the top block?',
    qVn: 'Trong kim tự tháp đại số, mỗi ô bằng hai ô bên dưới cộng lại. Hàng dưới cùng là 3x, 4x, x. Ô trên cùng là gì?',
    a: '12x',
    aVn: '12x',
    why: 'The middle row is 7x and 5x. Then 7x + 5x = 12x.',
    whyVn: 'Hàng giữa là 7x và 5x. Rồi 7x + 5x = 12x.',
    source: 'deck 2.3 s22 (adapted)',
    check: 'simplify("(3x + 4x) + (4x + x)")',
  },
  {
    id: 'm2.3-26',
    unit: '2.3',
    level: 3,
    kind: 'calc',
    q: 'Simplify 4a² + 3a − a² + 2a.',
    qVn: 'Rút gọn 4a² + 3a − a² + 2a.',
    a: '3a² + 5a',
    aVn: '3a² + 5a',
    why: 'a² and a are not like terms. a² means a × a.',
    whyVn: 'a² và a không phải hạng tử đồng dạng. a² nghĩa là a × a.',
    source: 'q1rev B5f',
    check: 'simplify("4a^2 + 3a - a^2 + 2a")',
  },
  {
    id: 'm2.3-27',
    unit: '2.3',
    level: 3,
    kind: 'calc',
    q: 'Simplify 6x + 4y − 2x + y.',
    qVn: 'Rút gọn 6x + 4y − 2x + y.',
    a: '4x + 5y',
    aVn: '4x + 5y',
    why: 'The minus moves with the 2x, so 6x − 2x = 4x. Not 8x + 5y.',
    whyVn: 'Dấu trừ đi cùng với 2x, nên 6x − 2x = 4x. Không phải 8x + 5y.',
    source: 'jeopardy maths-u2 · Like Terms 400 (adapted)',
    check: 'simplify("6x + 4y - 2x + y")',
  },
  {
    id: 'm2.3-28',
    unit: '2.3',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen has 4c cats. He buys 3c more cats and 2d dogs. Then 5c cats leave. One goldfish, called x, arrives. How many animals does he have now?',
    qVn: 'Thầy Bowen có 4c con mèo. Thầy mua thêm 3c con mèo và 2d con chó. Sau đó 5c con mèo bỏ đi. Một con cá vàng tên là x đến. Bây giờ thầy có bao nhiêu con vật?',
    a: '2c + 2d + 1',
    aVn: '2c + 2d + 1',
    why: '4c + 3c − 5c = 2c. The goldfish is 1 animal. Its name is not a number.',
    whyVn: '4c + 3c − 5c = 2c. Con cá vàng là 1 con vật. Tên của nó không phải là một con số.',
    source: 'jeopardy maths-u2 · Like Terms 500',
    check: 'simplify("4c + 3c + 2d - 5c + 1")',
  },
  {
    id: 'm2.3-29',
    unit: '2.3',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen simplifies 2ab + 3ba and writes "no like terms". What is the right answer?',
    qVn: 'Thầy Bowen rút gọn 2ab + 3ba và viết "no like terms" (không có hạng tử đồng dạng). Đáp án đúng là gì?',
    a: '5ab',
    aVn: '5ab',
    why: 'ab and ba are like terms, because a × b = b × a.',
    whyVn: 'ab và ba là hạng tử đồng dạng, vì a × b = b × a.',
    source: 'deck 2.3 s23',
    check: 'simplify("2ab + 3ba")',
  },
  {
    id: 'm2.3-30',
    unit: '2.3',
    level: 3,
    kind: 'calc',
    q: 'Simplify 7p − 2q − 3p + 6q + 4.',
    qVn: 'Rút gọn 7p − 2q − 3p + 6q + 4.',
    a: '4p + 4q + 4',
    aVn: '4p + 4q + 4',
    why: '7p − 3p = 4p and −2q + 6q = 4q. The 4 stays on its own.',
    whyVn: '7p − 3p = 4p và −2q + 6q = 4q. Số 4 đứng riêng.',
    source: 'hw07 A4d',
    check: 'simplify("7p - 2q - 3p + 6q + 4")',
  },
]
