// content/banks/y7-math/U02_5.js
// Maths 2.5 · Constructing and solving equations. Schema and house rules: bank.js.
//
// The traps are the deck's: doing the operation you see instead of its inverse
// (x − 4 = 6, so x = 2), and halving first in a two-step equation (2a + 4 = 18,
// so a = 5). Checking settles both: put the answer back in. The English is
// "reverse" (go backwards) against "inverse" (the opposite operation), "think
// of a number" (choose one and keep it secret), and "subtract 6 from it"
// against "subtract it from 6". The deck's x − 4 = 6, n − 5 = 21, 2a + 4 = 18
// and the 4x and 5x angles are Workbook exercises, so they appear here with new
// numbers. The letter is on one side only, and only the plant has a negative
// answer.
export const QUESTIONS = [
  {
    id: 'm2.5-01',
    unit: '2.5',
    level: 1,
    kind: 'words',
    q: 'In "I think of a number", what does "think of" mean?',
    qVn: 'Trong câu "I think of a number", cụm "think of" nghĩa là gì?',
    a: 'Choose a number and keep it secret',
    aVn: 'Nghĩ ra một số và giữ bí mật',
    why: 'Not "think about". Call the secret number n.',
    whyVn: 'Không phải "think about" (nghĩ về). Gọi số bí mật đó là n.',
    source: 'deck 2.5 s4',
  },
  {
    id: 'm2.5-02',
    unit: '2.5',
    level: 1,
    kind: 'words',
    q: 'What is the inverse operation of × 4?',
    qVn: 'Trong toán, "inverse operation" của × 4 là gì?',
    a: '÷ 4',
    aVn: '÷ 4',
    why: '× and ÷ undo each other: 3 × 4 = 12, and 12 ÷ 4 = 3.',
    whyVn: '× và ÷ là hai phép ngược nhau: 3 × 4 = 12, và 12 ÷ 4 = 3.',
    source: 'deck 2.5 s7',
  },
  {
    id: 'm2.5-03',
    unit: '2.5',
    level: 1,
    kind: 'words',
    q: 'Mr Bowen puts on his socks. Then he puts on his shoes. Which does he take off first?',
    qVn: 'Thầy Bowen mang tất. Rồi thầy mang giày. Thầy cởi cái nào ra trước?',
    a: 'His shoes',
    aVn: 'Giày',
    why: 'Last on, first off. In a two-step equation, undo the last step first.',
    whyVn: 'Mang sau, cởi trước. Trong phương trình hai bước, làm ngược bước cuối trước.',
    source: 'deck 2.5 s16',
  },
  {
    id: 'm2.5-04',
    unit: '2.5',
    level: 1,
    kind: 'words',
    q: 'What does "check your answer" mean, when you solve an equation?',
    qVn: '"Check your answer" nghĩa là gì, khi em giải một phương trình?',
    a: 'Put it back into the equation',
    aVn: 'Thay đáp án vào lại phương trình',
    why: 'x + 7 = 12, so x = 5. Check: 5 + 7 = 12 ✓',
    whyVn: 'x + 7 = 12, nên x = 5. Thử lại: 5 + 7 = 12 ✓',
    source: 'deck 2.5 s6',
  },
  {
    id: 'm2.5-05',
    unit: '2.5',
    level: 1,
    kind: 'words',
    q: 'Which one is an equation: 5k − 2, or 5k − 2 = 18?',
    qVn: 'Cái nào là phương trình: 5k − 2, hay 5k − 2 = 18?',
    a: '5k − 2 = 18',
    aVn: '5k − 2 = 18',
    why: 'An equation has an = sign and an unknown number. 5k − 2 is an expression.',
    whyVn: 'Phương trình có dấu = và một số chưa biết. 5k − 2 là một biểu thức.',
    source: 'q1rev B1 (adapted)',
  },
  {
    id: 'm2.5-06',
    unit: '2.5',
    level: 1,
    kind: 'calc',
    q: 'Solve x − 9 = 14. Then check your answer.',
    qVn: 'Giải x − 9 = 14. Rồi thử lại đáp án.',
    a: 'x = 23',
    aVn: 'x = 23',
    why: 'Check: 23 − 9 = 14 ✓. Not x = 5: 5 − 9 = −4.',
    whyVn: 'Thử lại: 23 − 9 = 14 ✓. Không phải x = 5: 5 − 9 = −4.',
    source: 'jeopardy maths-u2 · Equations 100 (adapted)',
    check: 'solve("x - 9 = 14")',
  },
  {
    id: 'm2.5-07',
    unit: '2.5',
    level: 2,
    kind: 'words',
    q: '"Reverse" and "inverse" look the same. What does each one mean?',
    qVn: '"Reverse" và "inverse" trông giống nhau. Mỗi từ nghĩa là gì?',
    a: 'Reverse: go backwards. Inverse: undo',
    aVn: 'Reverse: đi ngược lại. Inverse: phép ngược',
    why: 'Inverse is the opposite operation: + 5 is undone by − 5.',
    whyVn: 'Inverse là phép toán ngược: + 5 được xóa bỏ bằng − 5.',
    source: 'jeopardy maths-u2 · Equations 200',
  },
  {
    id: 'm2.5-08',
    unit: '2.5',
    level: 2,
    kind: 'words',
    q: '25 = x + 9. Is that the same equation as x + 9 = 25?',
    qVn: '25 = x + 9. Đó có phải cùng một phương trình với x + 9 = 25 không?',
    a: 'Yes. x = 16',
    aVn: 'Có. x = 16',
    why: 'Either way round means the same. 25 − 9 = 16.',
    whyVn: 'Viết chiều nào cũng có nghĩa như nhau. 25 − 9 = 16.',
    source: 'deck 2.5 s11 (adapted)',
    check: 'solve("25 = x + 9")',
  },
  {
    id: 'm2.5-09',
    unit: '2.5',
    level: 2,
    kind: 'calc',
    q: 'Solve 8x = 72.',
    qVn: 'Giải 8x = 72.',
    a: 'x = 9',
    aVn: 'x = 9',
    why: 'The inverse of × 8 is ÷ 8: 72 ÷ 8 = 9.',
    whyVn: 'Phép ngược của × 8 là ÷ 8: 72 ÷ 8 = 9.',
    source: 'deck 2.5 s10 (adapted)',
    check: 'solve("8x = 72")',
  },
  {
    id: 'm2.5-10',
    unit: '2.5',
    level: 2,
    kind: 'calc',
    q: 'Solve 40 = x + 13.',
    qVn: 'Giải 40 = x + 13.',
    a: 'x = 27',
    aVn: 'x = 27',
    why: '40 − 13 = 27. Check: 27 + 13 = 40 ✓',
    whyVn: '40 − 13 = 27. Thử lại: 27 + 13 = 40 ✓',
    source: 'WB 2.5 ex 6 (adapted)',
    check: 'solve("40 = x + 13")',
  },
  {
    id: 'm2.5-11',
    unit: '2.5',
    level: 2,
    kind: 'calc',
    q: 'Solve n ÷ 5 = 7.',
    qVn: 'Giải n ÷ 5 = 7.',
    a: 'n = 35',
    aVn: 'n = 35',
    why: 'The inverse of ÷ 5 is × 5: 7 × 5 = 35.',
    whyVn: 'Phép ngược của ÷ 5 là × 5: 7 × 5 = 35.',
    source: 'deck 2.5 s15 (adapted)',
    check: 'solve("n / 5 = 7")',
  },
  {
    id: 'm2.5-12',
    unit: '2.5',
    level: 2,
    kind: 'calc',
    q: 'Solve 5b − 4 = 31.',
    qVn: 'Giải 5b − 4 = 31.',
    a: 'b = 7',
    aVn: 'b = 7',
    why: '31 + 4 = 35, then 35 ÷ 5 = 7.',
    whyVn: '31 + 4 = 35, rồi 35 ÷ 5 = 7.',
    source: 'deck 2.5 s21 (adapted)',
    check: 'solve("5b - 4 = 31")',
  },
  {
    id: 'm2.5-13',
    unit: '2.5',
    level: 2,
    kind: 'calc',
    q: 'Solve 6c + 9 = 45.',
    qVn: 'Giải 6c + 9 = 45.',
    a: 'c = 6',
    aVn: 'c = 6',
    why: '45 − 9 = 36, then 36 ÷ 6 = 6.',
    whyVn: '45 − 9 = 36, rồi 36 ÷ 6 = 6.',
    source: 'hw08 D2 (adapted)',
    check: 'solve("6c + 9 = 45")',
  },
  {
    id: 'm2.5-14',
    unit: '2.5',
    level: 2,
    kind: 'calc',
    q: 'Solve 18 = 3k − 6.',
    qVn: 'Giải 18 = 3k − 6.',
    a: 'k = 8',
    aVn: 'k = 8',
    why: '18 + 6 = 24, then 24 ÷ 3 = 8.',
    whyVn: '18 + 6 = 24, rồi 24 ÷ 3 = 8.',
    source: 'q1rev B7g (adapted)',
    check: 'solve("18 = 3k - 6")',
  },
  {
    id: 'm2.5-15',
    unit: '2.5',
    level: 2,
    kind: 'calc',
    q: 'Solve x − 8 = 5. Is it A: x = 13, or B: x = 3?',
    qVn: 'Giải x − 8 = 5. Là A: x = 13, hay B: x = 3?',
    a: 'A: x = 13',
    aVn: 'A: x = 13',
    why: 'Check: 13 − 8 = 5 ✓. B did 8 − 5.',
    whyVn: 'Thử lại: 13 − 8 = 5 ✓. B đã lấy 8 − 5.',
    source: 'deck 2.5 s5 (adapted)',
    check: 'solve("x - 8 = 5")',
  },
  {
    id: 'm2.5-16',
    unit: '2.5',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen solves x − 6 = 9 and writes x = 3. Check his answer. Is he right?',
    qVn: 'Thầy Bowen giải x − 6 = 9 và viết x = 3. Thử lại đáp án của thầy. Thầy làm đúng không?',
    a: 'No. x = 15',
    aVn: 'Không. x = 15',
    why: 'Check: 3 − 6 = −3, not 9. He did 9 − 6.',
    whyVn: 'Thử lại: 3 − 6 = −3, không phải 9. Thầy đã lấy 9 − 6.',
    source: 'hw08 D1 (adapted)',
    check: 'solve("x - 6 = 9")',
  },
  {
    id: 'm2.5-17',
    unit: '2.5',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen says x = 0 is the answer to x + 11 = 11. Check it. Is he right?',
    qVn: 'Thầy Bowen nói x = 0 là đáp án của x + 11 = 11. Hãy thử lại. Thầy nói đúng không?',
    a: 'Yes',
    aVn: 'Đúng',
    why: 'Check: 0 + 11 = 11 ✓. 0 can be an answer.',
    whyVn: 'Thử lại: 0 + 11 = 11 ✓. Số 0 cũng có thể là đáp án.',
    source: 'deck 2.5 s12 (adapted)',
    check: 'yes(solve("x + 11 = 11") === 0)',
  },
  {
    id: 'm2.5-18',
    unit: '2.5',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen thinks of a number and subtracts 7. His answer is 15. What number did he first think of?',
    qVn: 'Thầy Bowen nghĩ ra một số rồi trừ đi 7. Kết quả là 15. Lúc đầu thầy đã nghĩ ra số nào?',
    a: '22',
    aVn: '22',
    why: 'n − 7 = 15, so n = 15 + 7 = 22. Check: 22 − 7 = 15 ✓',
    whyVn: 'n − 7 = 15, nên n = 15 + 7 = 22. Thử lại: 22 − 7 = 15 ✓',
    source: 'jeopardy maths-u2 · Equations 300 (adapted)',
    check: 'solve("n - 7 = 15")',
  },
  {
    id: 'm2.5-19',
    unit: '2.5',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen thinks of a number and multiplies it by 6. The answer is 42. Write an equation and solve it.',
    qVn: 'Thầy Bowen nghĩ ra một số rồi nhân nó với 6. Kết quả là 42. Viết phương trình rồi giải.',
    a: '6n = 42, so n = 7',
    aVn: '6n = 42, nên n = 7',
    source: 'deck 2.5 s15 (adapted)',
    check: 'solve("6n = 42")',
  },
  {
    id: 'm2.5-20',
    unit: '2.5',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen thinks of a number and adds 12. The answer is 31. What is his number?',
    qVn: 'Thầy Bowen nghĩ ra một số rồi cộng 12. Kết quả là 31. Số của thầy là số nào?',
    a: '19',
    aVn: '19',
    why: 'n + 12 = 31, so n = 31 − 12 = 19.',
    whyVn: 'n + 12 = 31, nên n = 31 − 12 = 19.',
    source: 'WB 2.5 ex 8 (adapted)',
    check: 'solve("n + 12 = 31")',
  },
  {
    id: 'm2.5-21',
    unit: '2.5',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen buys 5 notebooks and one pen. The pen costs 6 thousand dong. He pays 41 thousand dong. How much is one notebook?',
    qVn: 'Thầy Bowen mua 5 cuốn vở và một cây bút. Cây bút giá 6 nghìn đồng. Thầy trả 41 nghìn đồng. Một cuốn vở giá bao nhiêu?',
    a: '7 thousand dong',
    aVn: '7 nghìn đồng',
    why: '5n + 6 = 41, so 5n = 35 and n = 7.',
    whyVn: '5n + 6 = 41, nên 5n = 35 và n = 7.',
    source: 'deck 2.5 s24 (adapted)',
    check: 'solve("5n + 6 = 41")',
  },
  {
    id: 'm2.5-22',
    unit: '2.5',
    level: 3,
    kind: 'calc',
    q: 'Solve 2b + 8 = 22.',
    qVn: 'Giải 2b + 8 = 22.',
    a: 'b = 7',
    aVn: 'b = 7',
    why: 'Undo the last step first: 22 − 8 = 14, then 14 ÷ 2 = 7. Not b = 3.',
    whyVn: 'Làm ngược bước cuối trước: 22 − 8 = 14, rồi 14 ÷ 2 = 7. Không phải b = 3.',
    source: 'jeopardy maths-u2 · Equations 400 (adapted)',
    check: 'solve("2b + 8 = 22")',
  },
  {
    id: 'm2.5-23',
    unit: '2.5',
    level: 3,
    kind: 'calc',
    q: 'Solve 3c − 6 = 21. Is it A: c = 13, or B: c = 9?',
    qVn: 'Giải 3c − 6 = 21. Là A: c = 13, hay B: c = 9?',
    a: 'B: c = 9',
    aVn: 'B: c = 9',
    why: 'Undo the − 6 first: 21 + 6 = 27, then 27 ÷ 3 = 9. A divided first.',
    whyVn: 'Làm ngược phép − 6 trước: 21 + 6 = 27, rồi 27 ÷ 3 = 9. A đã chia trước.',
    source: 'deck 2.5 s18 (adapted)',
    check: 'solve("3c - 6 = 21")',
  },
  {
    id: 'm2.5-24',
    unit: '2.5',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen solves 4x + 8 = 40 and gets x = 2. What should the answer be?',
    qVn: 'Thầy Bowen giải 4x + 8 = 40 và được x = 2. Đáp án đúng phải là gì?',
    a: 'x = 8',
    aVn: 'x = 8',
    why: 'He divided first. Undo the + 8 first: 40 − 8 = 32, then 32 ÷ 4 = 8.',
    whyVn: 'Thầy đã chia trước. Làm ngược phép + 8 trước: 40 − 8 = 32, rồi 32 ÷ 4 = 8.',
    source: 'deck 2.5 s22 (adapted)',
    check: 'solve("4x + 8 = 40")',
  },
  {
    id: 'm2.5-25',
    unit: '2.5',
    level: 3,
    kind: 'words',
    q: 'A right angle is split into two angles, 4x and 2x. Write an equation and find x.',
    qVn: 'Một góc vuông được chia thành hai góc, 4x và 2x. Viết phương trình rồi tìm x.',
    a: '4x + 2x = 90, so x = 15',
    aVn: '4x + 2x = 90, nên x = 15',
    why: 'A right angle is 90°. The two angles are 60° and 30°.',
    whyVn: 'Góc vuông là 90°. Hai góc là 60° và 30°.',
    source: 'deck 2.5 s23 (adapted)',
    check: 'solve("4x + 2x = 90")',
  },
  {
    id: 'm2.5-26',
    unit: '2.5',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen thinks of a number. He multiplies it by 3, then adds 4. The answer is 25. What number did he first think of?',
    qVn: 'Thầy Bowen nghĩ ra một số. Thầy nhân nó với 3, rồi cộng 4. Kết quả là 25. Lúc đầu thầy đã nghĩ ra số nào?',
    a: '7',
    aVn: '7',
    why: '3n + 4 = 25. Undo the + 4 first: 21, then 21 ÷ 3 = 7.',
    whyVn: '3n + 4 = 25. Làm ngược phép + 4 trước: 21, rồi 21 ÷ 3 = 7.',
    source: 'deck 2.5 s15 (adapted)',
    check: 'solve("3n + 4 = 25")',
  },
  {
    id: 'm2.5-27',
    unit: '2.5',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen says a = 5 is the answer to 2a + 6 = 16. Check it. Is he right?',
    qVn: 'Thầy Bowen nói a = 5 là đáp án của 2a + 6 = 16. Hãy thử lại. Thầy nói đúng không?',
    a: 'Yes',
    aVn: 'Đúng',
    why: 'Check: 2 × 5 + 6 = 16 ✓',
    whyVn: 'Thử lại: 2 × 5 + 6 = 16 ✓',
    source: 'deck 2.5 s20 (adapted)',
    check: 'yes(solve("2a + 6 = 16") === 5)',
  },
  {
    id: 'm2.5-28',
    unit: '2.5',
    level: 3,
    kind: 'words',
    q: 'A taxi costs C = 10n + 15 thousand dong for n kilometres. Mr Bowen pays 75 thousand dong. How far does he go?',
    qVn: 'Một chiếc taxi tính C = 10n + 15 nghìn đồng cho n ki-lô-mét. Thầy Bowen trả 75 nghìn đồng. Thầy đi bao xa?',
    a: '6 km',
    aVn: '6 km',
    why: '10n + 15 = 75, so 10n = 60 and n = 6.',
    whyVn: '10n + 15 = 75, nên 10n = 60 và n = 6.',
    source: 'hw08 D3 (adapted)',
    check: 'solve("10n + 15 = 75")',
  },
  {
    id: 'm2.5-29',
    unit: '2.5',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen thinks of his age. He doubles it, then subtracts 7. The answer is 1. How old is Mr Bowen?',
    qVn: 'Thầy Bowen nghĩ đến tuổi của mình. Thầy nhân đôi nó, rồi trừ đi 7. Kết quả là 1. Thầy Bowen bao nhiêu tuổi?',
    a: '4 years old',
    aVn: '4 tuổi',
    why: '2a − 7 = 1, so 2a = 8 and a = 4.',
    whyVn: '2a − 7 = 1, nên 2a = 8 và a = 4.',
    source: 'jeopardy maths-u2 · Equations 500',
    check: 'solve("2a - 7 = 1")',
  },
  {
    id: 'm2.5-30',
    unit: '2.5',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen buys a plant. It grows 5 cm every week. After 6 weeks, it is 26 cm tall. How tall was it when he bought it?',
    qVn: 'Thầy Bowen mua một cái cây. Mỗi tuần nó cao thêm 5 cm. Sau 6 tuần, nó cao 26 cm. Lúc thầy mua, cái cây cao bao nhiêu?',
    a: '−4 cm',
    aVn: '−4 cm',
    why: 'h + 30 = 26, so h = 26 − 30 = −4.',
    whyVn: 'h + 30 = 26, nên h = 26 − 30 = −4.',
    source: 'deck 2.5 s26',
    check: 'solve("h + 5 * 6 = 26")',
  },
]
