// content/banks/y7-math/U02_2.js
// Maths 2.2 · Using expressions and formulae. Schema and house rules: bank.js.
//
// The traps are the deck's: 3n with n = 4 is 12, never 34; × and ÷ still come
// before + and − after substituting; a negative number goes in with its
// brackets, so 6 − 2n with n = −4 is 14; and a formula stops being true when
// its situation does. An expression has no = sign, a formula has one. No
// formula uses l for length, which reads as 1 on a TV.
export const QUESTIONS = [
  {
    id: 'm2.2-01',
    unit: '2.2',
    level: 1,
    kind: 'calc',
    q: 'Work out x + 6 when x = 9.',
    qVn: 'Tính x + 6 khi x = 9.',
    a: '15',
    aVn: '15',
    source: 'WB 2.2 ex 2 (adapted)',
    check: 'val("x + 6", {x: 9})',
  },
  {
    id: 'm2.2-02',
    unit: '2.2',
    level: 1,
    kind: 'words',
    q: 'In algebra, what does "substitute" mean?',
    qVn: 'Trong đại số, "substitute" nghĩa là gì?',
    a: 'Put a number in place of a letter',
    aVn: 'Thay số: đặt một số vào chỗ chữ cái',
    why: 'Like a football substitute: the place stays the same, only who is in it changes.',
    whyVn: 'Như cầu thủ dự bị trong bóng đá: vị trí giữ nguyên, chỉ đổi người đứng ở đó.',
    source: 'deck 2.2 s3',
  },
  {
    id: 'm2.2-03',
    unit: '2.2',
    level: 1,
    kind: 'words',
    q: 'Which one is a formula: 5p − 2 or V = 4t?',
    qVn: 'Cái nào là công thức: 5p − 2 hay V = 4t?',
    a: 'V = 4t',
    aVn: 'V = 4t',
    why: 'A formula has an = sign. 5p − 2 has none, so it is an expression.',
    whyVn: 'Công thức có dấu =. 5p − 2 không có, nên nó là một biểu thức.',
    source: 'hw06x E6',
  },
  {
    id: 'm2.2-04',
    unit: '2.2',
    level: 1,
    kind: 'words',
    q: 'In maths, what is the plural of "formula"?',
    qVn: 'Trong toán, số nhiều của "formula" là gì?',
    a: 'Formulae',
    aVn: 'Formulae (các công thức)',
    why: 'Say it out loud: formulae, not formulas.',
    whyVn: 'Đọc to lên: formulae, không phải formulas.',
    source: 'deck 2.2 s9',
  },
  {
    id: 'm2.2-05',
    unit: '2.2',
    level: 1,
    kind: 'calc',
    q: 'Work out k/4 when k = 28.',
    qVn: 'Tính k/4 khi k = 28.',
    a: '7',
    aVn: '7',
    why: 'k/4 means k ÷ 4.',
    whyVn: 'k/4 nghĩa là k ÷ 4.',
    source: 'WB 2.2 ex 6 (adapted)',
    check: 'val("k / 4", {k: 28})',
  },
  {
    id: 'm2.2-06',
    unit: '2.2',
    level: 1,
    kind: 'calc',
    q: 'Work out 15 − y when y = 6.',
    qVn: 'Tính 15 − y khi y = 6.',
    a: '9',
    aVn: '9',
    source: 'WB 2.2 ex 4 (adapted)',
    check: 'val("15 - y", {y: 6})',
  },
  {
    id: 'm2.2-07',
    unit: '2.2',
    level: 2,
    kind: 'calc',
    q: 'When n = 4, what is 3n?',
    qVn: 'Khi n = 4, 3n bằng bao nhiêu?',
    a: '12',
    aVn: '12',
    why: '3n means 3 × n, so 3 × 4 = 12. Never 34.',
    whyVn: '3n nghĩa là 3 × n, nên 3 × 4 = 12. Không bao giờ là 34.',
    source: 'jeopardy maths-u2 · Expressions & Formulae 200',
    check: 'val("3n", {n: 4})',
  },
  {
    id: 'm2.2-08',
    unit: '2.2',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen works out 5k when k = 3. He writes 53. What should he have written?',
    qVn: 'Thầy Bowen tính 5k khi k = 3. Thầy viết 53. Lẽ ra thầy phải viết gì?',
    a: '15',
    aVn: '15',
    why: '5k means 5 × k. The × sign was hidden, not deleted.',
    whyVn: '5k nghĩa là 5 × k. Dấu × chỉ bị ẩn đi, chứ không mất.',
    source: 'deck 2.2 s4 (adapted)',
    check: 'val("5k", {k: 3})',
  },
  {
    id: 'm2.2-09',
    unit: '2.2',
    level: 2,
    kind: 'calc',
    q: 'Work out 2x + 5 when x = 8.',
    qVn: 'Tính 2x + 5 khi x = 8.',
    a: '21',
    aVn: '21',
    why: 'Multiply first: 2 × 8 + 5 = 16 + 5. Not 26.',
    whyVn: 'Nhân trước: 2 × 8 + 5 = 16 + 5. Không phải 26.',
    source: 'deck 2.2 s6 (adapted)',
    check: 'val("2x + 5", {x: 8})',
  },
  {
    id: 'm2.2-10',
    unit: '2.2',
    level: 2,
    kind: 'calc',
    q: 'Work out k/3 + 9 when k = 24.',
    qVn: 'Tính k/3 + 9 khi k = 24.',
    a: '17',
    aVn: '17',
    why: 'Divide first: 24 ÷ 3 = 8, then 8 + 9.',
    whyVn: 'Chia trước: 24 ÷ 3 = 8, rồi 8 + 9.',
    source: 'hw06 A5d',
    check: 'val("k / 3 + 9", {k: 24})',
  },
  {
    id: 'm2.2-11',
    unit: '2.2',
    level: 2,
    kind: 'calc',
    q: 'Work out 6x − 5 when x = 4.',
    qVn: 'Tính 6x − 5 khi x = 4.',
    a: '19',
    aVn: '19',
    why: '6 × 4 − 5 = 24 − 5.',
    whyVn: '6 × 4 − 5 = 24 − 5.',
    source: 'hw06 A5a',
    check: 'val("6x - 5", {x: 4})',
  },
  {
    id: 'm2.2-12',
    unit: '2.2',
    level: 2,
    kind: 'calc',
    q: 'Work out h − 3w when h = 20 and w = 3.',
    qVn: 'Tính h − 3w khi h = 20 và w = 3.',
    a: '11',
    aVn: '11',
    why: 'Multiply first: 20 − 9. Not 51.',
    whyVn: 'Nhân trước: 20 − 9. Không phải 51.',
    source: 'WB 2.2 ex 6 (adapted)',
    check: 'val("h - 3w", {h: 20, w: 3})',
  },
  {
    id: 'm2.2-13',
    unit: '2.2',
    level: 2,
    kind: 'calc',
    q: 'A rectangle has base b and height h. Its area is A = bh. Find A when b = 9 and h = 4.',
    qVn: 'Một hình chữ nhật có cạnh đáy b và chiều cao h. Diện tích của nó là A = bh. Tìm A khi b = 9 và h = 4.',
    a: '36',
    aVn: '36',
    why: 'bh means b × h. Substitute both letters: 9 × 4.',
    whyVn: 'bh nghĩa là b × h. Thay cả hai chữ cái: 9 × 4.',
    source: 'WB 2.2 ex 9 (adapted)',
    check: 'val("bh", {b: 9, h: 4})',
  },
  {
    id: 'm2.2-14',
    unit: '2.2',
    level: 2,
    kind: 'calc',
    q: 'T = 3a − b. Find T when a = 5 and b = 7.',
    qVn: 'T = 3a − b. Tìm T khi a = 5 và b = 7.',
    a: '8',
    aVn: '8',
    why: '3 × 5 − 7 = 15 − 7.',
    whyVn: '3 × 5 − 7 = 15 − 7.',
    source: 'deck 2.2 s11 (adapted)',
    check: 'val("3a - b", {a: 5, b: 7})',
  },
  {
    id: 'm2.2-15',
    unit: '2.2',
    level: 2,
    kind: 'calc',
    q: 'Work out 8 − m when m = −5.',
    qVn: 'Tính 8 − m khi m = −5.',
    a: '13',
    aVn: '13',
    why: '8 − (−5) = 8 + 5. The minus sign goes in with the 5.',
    whyVn: '8 − (−5) = 8 + 5. Dấu trừ đi cùng với số 5.',
    source: 'hw06 A6b',
    check: 'val("8 - m", {m: -5})',
  },
  {
    id: 'm2.2-16',
    unit: '2.2',
    level: 2,
    kind: 'calc',
    q: 'Work out 4b when b = −3.',
    qVn: 'Tính 4b khi b = −3.',
    a: '−12',
    aVn: '−12',
    why: '4 × (−3) = −12. Put the negative number in brackets.',
    whyVn: '4 × (−3) = −12. Đặt số âm trong dấu ngoặc.',
    source: 'q1rev B3b',
    check: 'val("4b", {b: -3})',
  },
  {
    id: 'm2.2-17',
    unit: '2.2',
    level: 2,
    kind: 'words',
    q: 'There are 60 minutes in an hour. Write a formula for the number of minutes, m, in h hours.',
    qVn: 'Một giờ có 60 phút. Viết công thức tính số phút m trong h giờ.',
    a: 'm = 60h',
    aVn: 'm = 60h',
    why: 'A formula has an = sign. 60h means 60 × h.',
    whyVn: 'Công thức có dấu =. 60h nghĩa là 60 × h.',
    source: 'WB 2.2 ex 10 (adapted)',
  },
  {
    id: 'm2.2-18',
    unit: '2.2',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen buys n notebooks at 12 thousand dong each. Write a formula for the total cost, C, in thousand dong.',
    qVn: 'Thầy Bowen mua n quyển vở, mỗi quyển 12 nghìn đồng. Viết công thức tính tổng chi phí C, theo nghìn đồng.',
    a: 'C = 12n',
    aVn: 'C = 12n',
    why: 'C is the cost and n is the number of notebooks.',
    whyVn: 'C là chi phí và n là số quyển vở.',
    source: 'deck 2.2 s14 (adapted)',
  },
  {
    id: 'm2.2-19',
    unit: '2.2',
    level: 2,
    kind: 'words',
    q: 'Money collected = kilometres walked × rate. Mr Bowen walks 6 km at a rate of 15 thousand dong per km. How much does he collect?',
    qVn: 'Tiền quyên góp = số ki-lô-mét đi bộ × mức tiền. Thầy Bowen đi bộ 6 km với mức 15 nghìn đồng mỗi km. Thầy quyên góp được bao nhiêu?',
    a: '90 thousand dong',
    aVn: '90 nghìn đồng',
    source: 'WB 2.2 ex 7 (adapted)',
    check: '6 * 15',
  },
  {
    id: 'm2.2-20',
    unit: '2.2',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen heats water. After t minutes, its temperature is T = 22 + 6t, in °C. Find T when t = 5.',
    qVn: 'Thầy Bowen đun nước. Sau t phút, nhiệt độ của nước là T = 22 + 6t, tính bằng °C. Tìm T khi t = 5.',
    a: '52 °C',
    aVn: '52 °C',
    why: '22 + 6 × 5 = 22 + 30. The 22 is added once.',
    whyVn: '22 + 6 × 5 = 22 + 30. Số 22 chỉ cộng một lần.',
    source: 'hw06 A7a',
    check: 'val("22 + 6t", {t: 5})',
  },
  {
    id: 'm2.2-21',
    unit: '2.2',
    level: 2,
    kind: 'words',
    q: 'The number of legs on c cats is g = 4c. Mr Bowen has 3 cats. One of them is asleep. How many legs do his cats have?',
    qVn: 'Số chân của c con mèo là g = 4c. Thầy Bowen có 3 con mèo. Một con đang ngủ. Các con mèo của thầy có bao nhiêu chân?',
    a: '12',
    aVn: '12',
    why: '4 × 3 = 12. A sleeping cat still has 4 legs.',
    whyVn: '4 × 3 = 12. Mèo đang ngủ vẫn có 4 chân.',
    source: 'WB 2.2 ex 8 (adapted)',
    check: 'val("4c", {c: 3})',
  },
  {
    id: 'm2.2-22',
    unit: '2.2',
    level: 3,
    kind: 'calc',
    q: 'Work out 30 − 4n when n = 7.',
    qVn: 'Tính 30 − 4n khi n = 7.',
    a: '2',
    aVn: '2',
    why: 'Multiply first: 30 − 28. The × is written second, but done first.',
    whyVn: 'Nhân trước: 30 − 28. Dấu × viết sau, nhưng làm trước.',
    source: 'hw06 A5b',
    check: 'val("30 - 4n", {n: 7})',
  },
  {
    id: 'm2.2-23',
    unit: '2.2',
    level: 3,
    kind: 'calc',
    q: 'Work out 6 − 2n when n = −4.',
    qVn: 'Tính 6 − 2n khi n = −4.',
    a: '14',
    aVn: '14',
    why: '2 × (−4) = −8, so 6 − (−8) = 6 + 8. Not −2.',
    whyVn: '2 × (−4) = −8, nên 6 − (−8) = 6 + 8. Không phải −2.',
    source: 'deck 2.2 s12 (adapted)',
    check: 'val("6 - 2n", {n: -4})',
  },
  {
    id: 'm2.2-24',
    unit: '2.2',
    level: 3,
    kind: 'calc',
    q: 'Work out 2a − 3b when a = 5 and b = −3.',
    qVn: 'Tính 2a − 3b khi a = 5 và b = −3.',
    a: '19',
    aVn: '19',
    why: '3 × (−3) = −9, so 10 − (−9) = 10 + 9. Not 1.',
    whyVn: '3 × (−3) = −9, nên 10 − (−9) = 10 + 9. Không phải 1.',
    source: 'q1rev B3d',
    check: 'val("2a - 3b", {a: 5, b: -3})',
  },
  {
    id: 'm2.2-25',
    unit: '2.2',
    level: 3,
    kind: 'words',
    q: 'True or false: when t = 5, the value of 4 + 2t is 30.',
    qVn: 'Đúng hay sai: khi t = 5, giá trị của 4 + 2t là 30.',
    a: 'False',
    aVn: 'Sai',
    why: 'Multiply first: 4 + 2 × 5 = 4 + 10 = 14.',
    whyVn: 'Nhân trước: 4 + 2 × 5 = 4 + 10 = 14.',
    source: 'hw06x E9f',
    check: 'tf(val("4 + 2t", {t: 5}) === 30)',
  },
  {
    id: 'm2.2-26',
    unit: '2.2',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen\'s taxi costs 15 thousand dong to start, then 9 thousand dong for every kilometre. Write a formula for the cost C of k kilometres. Then find the cost of 6 km.',
    qVn: 'Taxi của thầy Bowen tính 15 nghìn đồng tiền mở cửa, sau đó 9 nghìn đồng mỗi ki-lô-mét. Viết công thức tính chi phí C cho k ki-lô-mét. Rồi tính chi phí cho 6 km.',
    a: 'C = 15 + 9k. 6 km: 69 thousand dong',
    aVn: 'C = 15 + 9k. 6 km: 69 nghìn đồng',
    why: 'The 15 is paid once. The 9 is paid every kilometre: 15 + 9 × 6 = 69.',
    whyVn: 'Số 15 trả một lần. Số 9 trả cho mỗi ki-lô-mét: 15 + 9 × 6 = 69.',
    source: 'jeopardy maths-u2 · Expressions & Formulae 500',
    check: 'String(val("15 + 9k", {k: 6}))',
  },
  {
    id: 'm2.2-27',
    unit: '2.2',
    level: 3,
    kind: 'words',
    q: 'Which formula is right? A: kilograms = 1000 × grams. B: grams = 1000 × kilograms.',
    qVn: 'Công thức nào đúng? A: số ki-lô-gam = 1000 × số gam. B: số gam = 1000 × số ki-lô-gam.',
    a: 'B',
    aVn: 'B',
    why: 'Test it with a number you know: 2 kg is 2000 g.',
    whyVn: 'Thử bằng một số em đã biết: 2 kg là 2000 g.',
    source: 'q1rev B4a',
    check: 'val("1000k", {k: 2}) === 2000 ? "B" : "A"',
  },
  {
    id: 'm2.2-28',
    unit: '2.2',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen heats water. It starts at 24 °C and rises 3 °C every minute, so T = 24 + 3m. The formula gives T = 144 after 40 minutes. Is that possible?',
    qVn: 'Thầy Bowen đun nước. Nước bắt đầu ở 24 °C và tăng 3 °C mỗi phút, nên T = 24 + 3m. Công thức cho ra T = 144 sau 40 phút. Điều đó có thể xảy ra không?',
    a: 'No',
    aVn: 'Không',
    why: 'Water stops getting hotter at 100 °C. A formula is only true while the situation is.',
    whyVn: 'Nước không nóng hơn 100 °C. Công thức chỉ đúng khi tình huống còn đúng.',
    source: 'deck 2.2 s15',
    check: 'yes(val("24 + 3m", {m: 40}) <= 100)',
  },
  {
    id: 'm2.2-29',
    unit: '2.2',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen\'s coffee cools. After m minutes, its temperature is T = 90 − 5m, in °C. He forgets it for 30 minutes. What does the formula give for T?',
    qVn: 'Cà phê của thầy Bowen nguội dần. Sau m phút, nhiệt độ của nó là T = 90 − 5m, tính bằng °C. Thầy quên nó trong 30 phút. Công thức cho ra T bằng bao nhiêu?',
    a: '−60 °C',
    aVn: '−60 °C',
    why: 'The arithmetic is right: 90 − 150. Coffee on a desk does not get that cold.',
    whyVn: 'Phép tính đúng: 90 − 150. Cà phê để trên bàn không thể lạnh đến thế.',
    source: 'deck 2.2 s15 (adapted)',
    check: 'val("90 - 5m", {m: 30})',
  },
  {
    id: 'm2.2-30',
    unit: '2.2',
    level: 3,
    kind: 'words',
    q: 'A tank has a base of 20 cm by 15 cm. Water is h cm deep. Volume = base area × depth. Write a formula for V. Then find V when h = 4.',
    qVn: 'Một bể có đáy 20 cm × 15 cm. Nước sâu h cm. Thể tích = diện tích đáy × độ sâu. Viết công thức tính V. Rồi tìm V khi h = 4.',
    a: 'V = 300h; 1200 cm³',
    aVn: 'V = 300h; 1200 cm³',
    why: '20 × 15 = 300, so V = 300h. Then 300 × 4. Not 3004.',
    whyVn: '20 × 15 = 300, nên V = 300h. Rồi 300 × 4. Không phải 3004.',
    source: 'hw06 C2',
    check: 'String(val("300h", {h: 4}))',
  },
]
