// content/banks/y7-math/U02_4.js
// Maths 2.4 · Expanding brackets. Schema and house rules: bank.js.
//
// The traps are the deck's: multiply EVERY term inside, so 5(a + 3) is not
// 5a + 3; stop at 12 − 4c, because 12 and 4c are not like terms; 5 × 2p is 10p,
// not 7p; and the minus goes into the box with its number. The English is
// "expand" (the value never gets bigger, only the writing gets longer), "multiply
// out" (the same job) and "each". Many of the deck's own expansions are Workbook
// exercises, so every one used here has new numbers and says (adapted).
export const QUESTIONS = [
  {
    id: 'm2.4-01',
    unit: '2.4',
    level: 1,
    kind: 'words',
    q: '"Expand" and "multiply out": same job, or different jobs?',
    qVn: '"Expand" và "multiply out": cùng một việc, hay hai việc khác nhau?',
    a: 'The same job',
    aVn: 'Cùng một việc',
    why: 'And the value does not get bigger. Only the writing gets longer.',
    whyVn: 'Và giá trị không lớn hơn. Chỉ có cách viết dài ra.',
    source: 'jeopardy maths-u2 · Brackets 200',
  },
  {
    id: 'm2.4-02',
    unit: '2.4',
    level: 1,
    kind: 'words',
    q: 'A balloon expands: it gets bigger. When you expand 4(10 + 6), does the value get bigger?',
    qVn: 'Quả bóng bay "expands" nghĩa là nó to ra. Khi em "expand" 4(10 + 6), giá trị có lớn hơn không?',
    a: 'No. It is still 64.',
    aVn: 'Không. Nó vẫn là 64.',
    why: '4(10 + 6) = 40 + 24 = 64. Only the writing gets longer.',
    whyVn: '4(10 + 6) = 40 + 24 = 64. Chỉ có cách viết dài ra.',
    source: 'deck 2.4 s5',
    check: '4 * (10 + 6)',
  },
  {
    id: 'm2.4-03',
    unit: '2.4',
    level: 1,
    kind: 'words',
    q: 'What are the marks ( ) called in maths?',
    qVn: 'Trong tiếng Anh, các dấu ( ) trong toán gọi là gì?',
    a: 'Brackets',
    aVn: 'Brackets (dấu ngoặc)',
    why: '4(10 + 6) means 4 × (10 + 6). The times sign is hidden.',
    whyVn: '4(10 + 6) nghĩa là 4 × (10 + 6). Dấu nhân bị ẩn đi.',
    source: 'deck 2.4 s6',
  },
  {
    id: 'm2.4-04',
    unit: '2.4',
    level: 1,
    kind: 'words',
    q: 'The rule is "multiply each term inside the brackets". What does "each" mean here?',
    qVn: 'Quy tắc là "multiply each term inside the brackets". Từ "each" ở đây nghĩa là gì?',
    a: 'Every single one',
    aVn: 'Mỗi: từng cái một, không sót cái nào',
    why: 'In 2(x + 9), the x and the 9 are both multiplied.',
    whyVn: 'Trong 2(x + 9), cả x và 9 đều được nhân.',
    source: 'deck 2.4 s5',
  },
  {
    id: 'm2.4-05',
    unit: '2.4',
    level: 1,
    kind: 'calc',
    q: 'Work out 6 × 23 by splitting 23 into 20 + 3.',
    qVn: 'Tính 6 × 23 bằng cách tách 23 thành 20 + 3.',
    a: '120 + 18 = 138',
    aVn: '120 + 18 = 138',
    why: 'That is expanding brackets: 6(20 + 3).',
    whyVn: 'Đó chính là khai triển dấu ngoặc: 6(20 + 3).',
    source: 'hw07x F3 (adapted)',
    check: '6 * 23',
  },
  {
    id: 'm2.4-06',
    unit: '2.4',
    level: 1,
    kind: 'calc',
    q: 'Expand 4(b + 6).',
    qVn: 'Khai triển 4(b + 6).',
    a: '4b + 24',
    aVn: '4b + 24',
    why: 'Multiply every term inside the brackets. Not 4b + 6.',
    whyVn: 'Nhân mọi hạng tử bên trong ngoặc. Không phải 4b + 6.',
    source: 'jeopardy maths-u2 · Brackets 100 (adapted)',
    check: 'expand("4(b + 6)")',
  },
  {
    id: 'm2.4-07',
    unit: '2.4',
    level: 2,
    kind: 'calc',
    q: 'Expand 8(y − 3).',
    qVn: 'Khai triển 8(y − 3).',
    a: '8y − 24',
    aVn: '8y − 24',
    why: 'The minus goes into the box with the 3. Not 8y + 24.',
    whyVn: 'Dấu trừ đi vào ô cùng với số 3. Không phải 8y + 24.',
    source: 'deck 2.4 s12 (adapted)',
    check: 'expand("8(y - 3)")',
  },
  {
    id: 'm2.4-08',
    unit: '2.4',
    level: 2,
    kind: 'calc',
    q: 'Expand 9(2 + w).',
    qVn: 'Khai triển 9(2 + w).',
    a: '18 + 9w',
    aVn: '18 + 9w',
    why: 'Both terms, in the same order. 9w + 18 is also right.',
    whyVn: 'Cả hai hạng tử, theo đúng thứ tự. 9w + 18 cũng đúng.',
    source: 'deck 2.4 s10 (adapted)',
    check: 'expand("9(2 + w)")',
  },
  {
    id: 'm2.4-09',
    unit: '2.4',
    level: 2,
    kind: 'words',
    q: 'Multiply out 6(k + 4).',
    qVn: 'Hãy "multiply out" 6(k + 4).',
    a: '6k + 24',
    aVn: '6k + 24',
    why: '"Multiply out" means the same as expand.',
    whyVn: '"Multiply out" nghĩa giống như khai triển (expand).',
    source: 'deck 2.4 s17 (adapted)',
    check: 'expand("6(k + 4)")',
  },
  {
    id: 'm2.4-10',
    unit: '2.4',
    level: 2,
    kind: 'calc',
    q: 'Expand 3(4g − 1).',
    qVn: 'Khai triển 3(4g − 1).',
    a: '12g − 3',
    aVn: '12g − 3',
    why: '3 × 4g = 12g, and 3 × 1 = 3.',
    whyVn: '3 × 4g = 12g, và 3 × 1 = 3.',
    source: 'hw07 B2k (adapted)',
    check: 'expand("3(4g - 1)")',
  },
  {
    id: 'm2.4-11',
    unit: '2.4',
    level: 2,
    kind: 'calc',
    q: 'Expand 5(1 − 3h).',
    qVn: 'Khai triển 5(1 − 3h).',
    a: '5 − 15h',
    aVn: '5 − 15h',
    why: 'The letter is second, so the answer starts with a number.',
    whyVn: 'Chữ cái đứng sau, nên đáp án bắt đầu bằng một số.',
    source: 'hw07 B2l (adapted)',
    check: 'expand("5(1 - 3h)")',
  },
  {
    id: 'm2.4-12',
    unit: '2.4',
    level: 2,
    kind: 'calc',
    q: 'Expand 5(4 − d). Is it A: 20 − 5d, or B: 15d?',
    qVn: 'Khai triển 5(4 − d). Là A: 20 − 5d, hay B: 15d?',
    a: 'A: 20 − 5d',
    aVn: 'A: 20 − 5d',
    why: 'Stop there. 20 and 5d are not like terms, so it is not 15d.',
    whyVn: 'Dừng ở đó. 20 và 5d không đồng dạng, nên không phải 15d.',
    source: 'jeopardy maths-u2 · Brackets 300 (adapted)',
    check: 'val("5(4 - d)", {d: 7}) === val("20 - 5d", {d: 7}) ? "A" : "B"',
  },
  {
    id: 'm2.4-13',
    unit: '2.4',
    level: 2,
    kind: 'words',
    q: 'Is 18 − 6m finished, or can you collect it into one term?',
    qVn: '18 − 6m đã xong chưa, hay còn gộp được thành một hạng tử?',
    a: 'Finished',
    aVn: 'Đã xong',
    why: '18 and 6m are not like terms. Not 12m.',
    whyVn: '18 và 6m không đồng dạng. Không phải 12m.',
    source: 'hw07 B3 (adapted)',
  },
  {
    id: 'm2.4-14',
    unit: '2.4',
    level: 2,
    kind: 'words',
    q: '"Expand and simplify" means two jobs. Which one do you do first?',
    qVn: '"Expand and simplify" là hai việc. Em làm việc nào trước?',
    a: 'Expand the brackets',
    aVn: 'Khai triển dấu ngoặc',
    why: 'Then collect the like terms: 2(y + 4) + 3y = 5y + 8.',
    whyVn: 'Rồi gộp các hạng tử đồng dạng: 2(y + 4) + 3y = 5y + 8.',
    source: 'deck 2.4 s20',
  },
  {
    id: 'm2.4-15',
    unit: '2.4',
    level: 2,
    kind: 'calc',
    q: 'Expand and simplify 5(x + 2) − 3x.',
    qVn: 'Khai triển rồi rút gọn 5(x + 2) − 3x.',
    a: '2x + 10',
    aVn: '2x + 10',
    why: '5x + 10 − 3x. Then 5x − 3x = 2x.',
    whyVn: '5x + 10 − 3x. Rồi 5x − 3x = 2x.',
    source: 'deck 2.4 s28 (adapted)',
    check: 'expand("5(x + 2) - 3x")',
  },
  {
    id: 'm2.4-16',
    unit: '2.4',
    level: 2,
    kind: 'calc',
    q: 'Expand and simplify 3(2y + 4) − 5.',
    qVn: 'Khai triển rồi rút gọn 3(2y + 4) − 5.',
    a: '6y + 7',
    aVn: '6y + 7',
    why: '6y + 12 − 5. Then 12 − 5 = 7.',
    whyVn: '6y + 12 − 5. Rồi 12 − 5 = 7.',
    source: 'deck 2.4 s21 (adapted)',
    check: 'expand("3(2y + 4) - 5")',
  },
  {
    id: 'm2.4-17',
    unit: '2.4',
    level: 2,
    kind: 'words',
    q: 'Put b = 3 into 6(b + 2), then into 6b + 12. Do you get the same answer?',
    qVn: 'Thay b = 3 vào 6(b + 2), rồi vào 6b + 12. Hai kết quả có giống nhau không?',
    a: 'Yes: 30 both times',
    aVn: 'Có: cả hai lần đều là 30',
    why: 'Expanding never changes the value. Only the writing changes.',
    whyVn: 'Khai triển không bao giờ làm đổi giá trị. Chỉ có cách viết thay đổi.',
    source: 'hw07x F17 (adapted)',
    check: 'val("6(b + 2)", {b: 3}) === val("6b + 12", {b: 3}) ? val("6b + 12", {b: 3}) : NaN',
  },
  {
    id: 'm2.4-18',
    unit: '2.4',
    level: 2,
    kind: 'calc',
    q: 'Right or wrong? 2(3x + 1) = 6x + 2',
    qVn: 'Đúng hay sai? 2(3x + 1) = 6x + 2',
    a: 'Right',
    aVn: 'Đúng',
    why: '2 × 3x = 6x, and 2 × 1 = 2.',
    whyVn: '2 × 3x = 6x, và 2 × 1 = 2.',
    source: 'deck 2.4 s15',
    check: 'val("2(3x + 1)", {x: 5}) === val("6x + 2", {x: 5}) ? "Right" : "Wrong"',
  },
  {
    id: 'm2.4-19',
    unit: '2.4',
    level: 2,
    kind: 'calc',
    q: 'Right or wrong? 3(y − 6) = 3y + 18',
    qVn: 'Đúng hay sai? 3(y − 6) = 3y + 18',
    a: 'Wrong. 3(y − 6) = 3y − 18',
    aVn: 'Sai. 3(y − 6) = 3y − 18',
    why: 'The minus does not change. It goes in with the 6.',
    whyVn: 'Dấu trừ không đổi. Nó đi cùng với số 6.',
    source: 'deck 2.4 s15 (adapted)',
    check: 'expand("3(y - 6)")',
  },
  {
    id: 'm2.4-20',
    unit: '2.4',
    level: 2,
    kind: 'words',
    q: 'A rectangle is 5 cm wide and (x + 4) cm long. Write its area in its simplest form.',
    qVn: 'Một hình chữ nhật rộng 5 cm và dài (x + 4) cm. Viết diện tích của nó ở dạng gọn nhất.',
    a: '5(x + 4) = 5x + 20',
    aVn: '5(x + 4) = 5x + 20',
    why: 'Area = length × width, in square centimetres.',
    whyVn: 'Diện tích = chiều dài × chiều rộng, tính bằng xăng-ti-mét vuông.',
    source: 'deck 2.4 s22 (adapted)',
    check: 'expand("5(x + 4)")',
  },
  {
    id: 'm2.4-21',
    unit: '2.4',
    level: 2,
    kind: 'words',
    q: 'Which is the odd one out: 2(4x + 6), 4(2x + 3) or 3(3x + 4)?',
    qVn: 'Biểu thức nào khác loại: 2(4x + 6), 4(2x + 3) hay 3(3x + 4)?',
    a: '3(3x + 4) = 9x + 12',
    aVn: '3(3x + 4) = 9x + 12',
    why: 'The other two both give 8x + 12.',
    whyVn: 'Hai biểu thức kia đều cho 8x + 12.',
    source: 'deck 2.4 s19 (adapted)',
    check: 'expand("3(3x + 4)")',
  },
  {
    id: 'm2.4-22',
    unit: '2.4',
    level: 3,
    kind: 'calc',
    q: 'Expand 7(2k + 3).',
    qVn: 'Khai triển 7(2k + 3).',
    a: '14k + 21',
    aVn: '14k + 21',
    why: 'Multiply the numbers: 7 × 2k = 14k. The letter stays. Not 9k.',
    whyVn: 'Nhân các con số: 7 × 2k = 14k. Chữ cái giữ nguyên. Không phải 9k.',
    source: 'jeopardy maths-u2 · Brackets 400 (adapted)',
    check: 'expand("7(2k + 3)")',
  },
  {
    id: 'm2.4-23',
    unit: '2.4',
    level: 3,
    kind: 'calc',
    q: 'Expand 2(4u + 3v − 5).',
    qVn: 'Khai triển 2(4u + 3v − 5).',
    a: '8u + 6v − 10',
    aVn: '8u + 6v − 10',
    why: 'Three terms inside, so three multiplications. Do not leave the 5 behind.',
    whyVn: 'Ba hạng tử bên trong, nên ba phép nhân. Đừng bỏ quên số 5.',
    source: 'hw07 B2m (adapted)',
    check: 'expand("2(4u + 3v - 5)")',
  },
  {
    id: 'm2.4-24',
    unit: '2.4',
    level: 3,
    kind: 'calc',
    q: 'Expand and simplify 2(a + 3) + 4(a + 1).',
    qVn: 'Khai triển rồi rút gọn 2(a + 3) + 4(a + 1).',
    a: '6a + 10',
    aVn: '6a + 10',
    why: '2a + 6 + 4a + 4. Expand both brackets first, then collect.',
    whyVn: '2a + 6 + 4a + 4. Khai triển cả hai ngoặc trước, rồi gộp.',
    source: 'hw07 B5b (adapted)',
    check: 'expand("2(a + 3) + 4(a + 1)")',
  },
  {
    id: 'm2.4-25',
    unit: '2.4',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen writes 4(2m + 5) = 6m + 20. What should the answer be?',
    qVn: 'Thầy Bowen viết 4(2m + 5) = 6m + 20. Đáp án đúng phải là gì?',
    a: '8m + 20',
    aVn: '8m + 20',
    why: 'He did 4 + 2. It should be 4 × 2m = 8m.',
    whyVn: 'Thầy lấy 4 + 2. Phải là 4 × 2m = 8m.',
    source: 'deck 2.4 s18 (adapted)',
    check: 'expand("4(2m + 5)")',
  },
  {
    id: 'm2.4-26',
    unit: '2.4',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen expands 4(3k − 2) and gets 12k − 2. Is he correct?',
    qVn: 'Thầy Bowen khai triển 4(3k − 2) và được 12k − 2. Thầy làm đúng không?',
    a: 'No. 4(3k − 2) = 12k − 8',
    aVn: 'Không. 4(3k − 2) = 12k − 8',
    why: 'He multiplied the 3k but not the 2.',
    whyVn: 'Thầy đã nhân 3k nhưng chưa nhân số 2.',
    source: 'q1rev B6f (adapted)',
    check: 'expand("4(3k - 2)")',
  },
  {
    id: 'm2.4-27',
    unit: '2.4',
    level: 3,
    kind: 'words',
    q: 'A rectangle is 3 cm wide and (y + 6) cm long. Write its perimeter in its simplest form.',
    qVn: 'Một hình chữ nhật rộng 3 cm và dài (y + 6) cm. Viết chu vi của nó ở dạng gọn nhất.',
    a: '2y + 18',
    aVn: '2y + 18',
    why: 'All four sides: 2(y + 6) + 2 × 3 = 2y + 12 + 6.',
    whyVn: 'Cả bốn cạnh: 2(y + 6) + 2 × 3 = 2y + 12 + 6.',
    source: 'deck 2.4 s22 (adapted)',
    check: 'expand("2(y + 6) + 2 * 3")',
  },
  {
    id: 'm2.4-28',
    unit: '2.4',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen buys 6 bags. Each bag has m mangoes and 2 dragon fruits. On the way home, he eats 4 mangoes. How much fruit does he carry into the house?',
    qVn: 'Thầy Bowen mua 6 túi. Mỗi túi có m quả xoài và 2 quả thanh long. Trên đường về, thầy ăn 4 quả xoài. Thầy mang vào nhà bao nhiêu quả?',
    a: '6m + 8',
    aVn: '6m + 8',
    why: '6(m + 2) − 4. "Fruit" means the mangoes and the dragon fruits.',
    whyVn: '6(m + 2) − 4. "Fruit" là cả xoài và thanh long.',
    source: 'jeopardy maths-u2 · Brackets 500',
    check: 'expand("6(m + 2) - 4")',
  },
  {
    id: 'm2.4-29',
    unit: '2.4',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen has 7 drawers. Each drawer holds s socks and 3 spiders. Every spider picks up one sock and walks out. How many things are in the drawers now?',
    qVn: 'Thầy Bowen có 7 ngăn kéo. Mỗi ngăn có s chiếc tất và 3 con nhện. Mỗi con nhện cầm một chiếc tất rồi bò ra ngoài. Bây giờ trong các ngăn kéo có bao nhiêu thứ?',
    a: '7s − 21',
    aVn: '7s − 21',
    why: 'Each drawer loses 3 spiders and 3 socks: 7(s − 3).',
    whyVn: 'Mỗi ngăn mất 3 con nhện và 3 chiếc tất: 7(s − 3).',
    source: 'deck 2.4 s25',
    check: 'expand("7(s - 3)")',
  },
  {
    id: 'm2.4-30',
    unit: '2.4',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen keeps 5 fish tanks. Every tank holds f fish and 3 rubber ducks. Rubber ducks are not alive. How many living things are in the tanks?',
    qVn: 'Thầy Bowen nuôi 5 bể cá. Mỗi bể có f con cá và 3 con vịt cao su. Vịt cao su không phải là vật sống. Trong các bể có bao nhiêu vật sống?',
    a: '5f',
    aVn: '5f',
    why: 'Only the fish are alive, so nothing is added to 5f.',
    whyVn: 'Chỉ có cá là vật sống, nên không cộng thêm gì vào 5f.',
    source: 'hw07 B6 (adapted)',
    check: 'expand("5(f + 3) - 5 * 3")',
  },
]
