// content/banks/y7-math/U03_1_2.js
// Maths 3.1 · Place value and powers of 10, and 3.2 · Rounding: one deck, two
// sections. Schema and house rules: bank.js.
//
// 3.1's trap is the folk rule: 7.2 × 10³ is 7200, not 7.2000. The digits move,
// the point never does, and a zero that appears when dividing holds a column
// open (520 ÷ 10⁴ is 0.052, not 0.52). The mass ladder is three steps of 10³.
// 3.2's traps are the deck's: keep the trailing zero (35.0, not 35), work one
// place further before rounding, and round once. "Correct to" means round; "as
// far as" does not. 58 ÷ 7 is left out: it may be the Workbook's own item, so
// the stop-too-early questions use the repo's numbers. Big numbers take a space
// from five digits, as the homework writes them (60 000).
export const QUESTIONS = [
  // ── 3.1 · Place value and powers of 10 ─────────────────────────────────────
  {
    id: 'm3.1-01',
    unit: '3.1',
    level: 1,
    kind: 'words',
    q: 'Say it in English: 10³',
    qVn: 'Đọc bằng tiếng Anh: 10³',
    a: 'Ten cubed',
    aVn: 'Ten cubed (mười lập phương)',
    why: 'Or "ten to the power of three". It is 1000.',
    whyVn: 'Hoặc "ten to the power of three". Nó bằng 1000.',
    source: 'jeopardy maths-u2 · Place Value & Rounding 100',
  },
  {
    id: 'm3.1-02',
    unit: '3.1',
    level: 1,
    kind: 'words',
    q: 'Say it in English: 10⁶',
    qVn: 'Đọc bằng tiếng Anh: 10⁶',
    a: 'Ten to the power of six',
    aVn: 'Ten to the power of six',
    why: 'It is 1 000 000. After 10³, English says "to the power of".',
    whyVn: 'Nó bằng 1 000 000. Sau 10³, tiếng Anh nói "to the power of".',
    source: 'deck 3.1 s4',
  },
  {
    id: 'm3.1-03',
    unit: '3.1',
    level: 1,
    kind: 'words',
    q: 'In maths, what does the word "power" mean?',
    qVn: 'Trong toán, từ "power" nghĩa là gì?',
    a: 'The small raised number',
    aVn: 'Số mũ: con số nhỏ viết cao',
    why: 'It says how many to multiply: 10³ = 10 × 10 × 10. Not electricity.',
    whyVn: 'Nó cho biết nhân bao nhiêu số: 10³ = 10 × 10 × 10. Không phải là điện.',
    source: 'deck 3.1 s3',
  },
  {
    id: 'm3.1-04',
    unit: '3.1',
    level: 1,
    kind: 'calc',
    q: 'Write 10 000 as a power of 10.',
    qVn: 'Viết 10 000 dưới dạng lũy thừa của 10.',
    a: '10⁴',
    aVn: '10⁴',
    why: 'Count the zeros after the 1. There are four.',
    whyVn: 'Đếm số 0 sau số 1: có bốn.',
    source: 'q1rev C1b',
    check: "'10^' + Math.log10(10000)",
  },
  {
    id: 'm3.1-05',
    unit: '3.1',
    level: 1,
    kind: 'words',
    q: 'What is the name of the first column after the decimal point?',
    qVn: 'Cột đầu tiên sau dấu thập phân tên là gì?',
    a: 'Tenths',
    aVn: 'Tenths (phần mười)',
    why: 'Then hundredths, then thousandths.',
    whyVn: 'Rồi đến hundredths (phần trăm), rồi thousandths (phần nghìn).',
    source: 'deck 3.1 s17',
  },
  {
    id: 'm3.1-06',
    unit: '3.1',
    level: 1,
    kind: 'words',
    q: 'How many milligrams are there in 1 gram?',
    qVn: '1 gam bằng bao nhiêu miligam?',
    a: '1000 mg',
    aVn: '1000 mg',
    why: 'Every step on the ladder is 10³: mg, g, kg, t.',
    whyVn: 'Mỗi bậc trên thang đều là 10³: mg, g, kg, t.',
    source: 'deck 3.1 s15',
    check: '10 ** 3',
  },
  {
    id: 'm3.1-07',
    unit: '3.1',
    level: 2,
    kind: 'calc',
    q: 'Work out 7.2 × 10³.',
    qVn: 'Tính 7.2 × 10³.',
    a: '7200',
    aVn: '7200',
    why: 'The digits move 3 places left. 7.2000 is still 7.2.',
    whyVn: 'Các chữ số dịch 3 cột sang trái. 7.2000 vẫn chỉ là 7.2.',
    source: 'jeopardy maths-u2 · Place Value & Rounding 200',
    check: '7.2 * 10 ** 3',
  },
  {
    id: 'm3.1-08',
    unit: '3.1',
    level: 2,
    kind: 'calc',
    q: 'Work out 0.9 × 10⁵.',
    qVn: 'Tính 0.9 × 10⁵.',
    a: '90 000',
    aVn: '90 000',
    why: 'The 9 moves 5 places left.',
    whyVn: 'Số 9 dịch 5 cột sang trái.',
    source: 'deck 3.1 s10',
    check: '0.9 * 10 ** 5',
  },
  {
    id: 'm3.1-09',
    unit: '3.1',
    level: 2,
    kind: 'calc',
    q: 'Work out 2.08 × 10³.',
    qVn: 'Tính 2.08 × 10³.',
    a: '2080',
    aVn: '2080',
    why: 'Three places left: 20.8, 208, 2080.',
    whyVn: 'Ba cột sang trái: 20.8, 208, 2080.',
    source: 'q1rev C1d',
    check: '2.08 * 10 ** 3',
  },
  {
    id: 'm3.1-10',
    unit: '3.1',
    level: 2,
    kind: 'calc',
    q: 'Work out 6 ÷ 10³.',
    qVn: 'Tính 6 ÷ 10³.',
    a: '0.006',
    aVn: '0.006',
    why: 'The 6 moves 3 places right. Write a zero in each empty column.',
    whyVn: 'Số 6 dịch 3 cột sang phải. Viết số 0 vào mỗi cột trống.',
    source: 'deck 3.1 s11',
    check: '6 / 10 ** 3',
  },
  {
    id: 'm3.1-11',
    unit: '3.1',
    level: 2,
    kind: 'calc',
    q: 'Work out 48 600 ÷ 10³.',
    qVn: 'Tính 48 600 ÷ 10³.',
    a: '48.6',
    aVn: '48.6',
    why: 'Three places right: 4860, 486, 48.6.',
    whyVn: 'Ba cột sang phải: 4860, 486, 48.6.',
    source: 'deck 3.1 s9',
    check: '48600 / 10 ** 3',
  },
  {
    id: 'm3.1-12',
    unit: '3.1',
    level: 2,
    kind: 'calc',
    q: '6.1 × 10ⁿ = 61 000. What is n?',
    qVn: '6.1 × 10ⁿ = 61 000. n bằng bao nhiêu?',
    a: '4',
    aVn: '4',
    why: 'The digits moved 4 places left, so it is 10⁴.',
    whyVn: 'Các chữ số dịch 4 cột sang trái, nên đó là 10⁴.',
    source: 'deck 3.1 s13',
    check: 'Math.round(Math.log10(61000 / 6.1))',
  },
  {
    id: 'm3.1-13',
    unit: '3.1',
    level: 2,
    kind: 'words',
    q: '5.3 × 10² = 530. What moved: the digits, or the decimal point?',
    qVn: '5.3 × 10² = 530. Cái gì đã dịch chuyển: các chữ số, hay dấu thập phân?',
    a: 'The digits',
    aVn: 'Các chữ số',
    why: 'The digits move. The point never does.',
    whyVn: 'Các chữ số dịch chuyển. Dấu thập phân thì không.',
    source: 'deck 3.1 s9 (adapted)',
  },
  {
    id: 'm3.1-14',
    unit: '3.1',
    level: 2,
    kind: 'words',
    q: 'The Sun is 1.496 × 10⁸ km from Earth. Write this as an ordinary number.',
    qVn: 'Mặt Trời cách Trái Đất 1.496 × 10⁸ km. Hãy viết số này thành số thường.',
    a: '149 600 000 km',
    aVn: '149 600 000 km',
    why: 'The digits move 8 places left.',
    whyVn: 'Các chữ số dịch 8 cột sang trái.',
    source: 'deck 3.1 s16 (adapted)',
    check: '1.496 * 10 ** 8',
  },
  {
    id: 'm3.1-15',
    unit: '3.1',
    level: 2,
    kind: 'words',
    q: 'The Moon is 3.844 × 10⁵ km from Earth. Jupiter is 6.287 × 10⁸ km from Earth. Which is further away?',
    qVn: 'Mặt Trăng cách Trái Đất 3.844 × 10⁵ km. Sao Mộc cách Trái Đất 6.287 × 10⁸ km. Cái nào xa hơn?',
    a: 'Jupiter',
    aVn: 'Sao Mộc',
    why: '10⁸ is bigger than 10⁵. The power tells you before you write anything.',
    whyVn: '10⁸ lớn hơn 10⁵. Số mũ cho biết trước khi em viết gì cả.',
    source: 'deck 3.1 s16',
    check: "6.287 * 10 ** 8 > 3.844 * 10 ** 5 ? 'Jupiter' : 'Moon'",
  },
  {
    id: 'm3.1-16',
    unit: '3.1',
    level: 2,
    kind: 'words',
    q: 'Write 3 tonnes in kilograms.',
    qVn: 'Viết 3 tấn theo ki-lô-gam.',
    a: '3000 kg',
    aVn: '3000 kg',
    why: 'One step down the ladder: × 10³.',
    whyVn: 'Xuống một bậc trên thang: × 10³.',
    source: 'q1rev C2c',
    check: '3 * 10 ** 3',
  },
  {
    id: 'm3.1-17',
    unit: '3.1',
    level: 2,
    kind: 'words',
    q: 'Write 2500 mg in grams.',
    qVn: 'Viết 2500 mg theo gam.',
    a: '2.5 g',
    aVn: '2.5 g',
    why: 'One step up: ÷ 10³. The number gets smaller.',
    whyVn: 'Lên một bậc: ÷ 10³. Số nhỏ đi.',
    source: 'q1rev C2d',
    check: '2500 / 10 ** 3',
  },
  {
    id: 'm3.1-18',
    unit: '3.1',
    level: 2,
    kind: 'words',
    q: 'Which is heavier: 400 g or 0.5 kg?',
    qVn: 'Cái nào nặng hơn: 400 g hay 0.5 kg?',
    a: '0.5 kg',
    aVn: '0.5 kg',
    why: '0.5 kg = 500 g, and 500 g is more than 400 g.',
    whyVn: '0.5 kg = 500 g, và 500 g nhiều hơn 400 g.',
    source: 'hw08x X19a',
    check: '0.5 * 1000 > 400 ? 0.5 : 400',
  },
  {
    id: 'm3.1-19',
    unit: '3.1',
    level: 2,
    kind: 'words',
    q: 'In 0.86, what is the 6 worth?',
    qVn: 'Trong 0.86, chữ số 6 có giá trị bao nhiêu?',
    a: '0.06, six hundredths',
    aVn: '0.06, sáu phần trăm',
    why: 'It is in the second column after the point.',
    whyVn: 'Nó ở cột thứ hai sau dấu thập phân.',
    source: 'hw08x X2',
    check: '6 / 100',
  },
  {
    id: 'm3.1-20',
    unit: '3.1',
    level: 2,
    kind: 'words',
    q: 'Say it in English: 8.06',
    qVn: 'Đọc bằng tiếng Anh: 8.06',
    a: 'Eight point zero six',
    aVn: 'Eight point zero six',
    why: 'After the point, say one digit at a time, and say the 0.',
    whyVn: 'Sau dấu thập phân, đọc từng chữ số một, và đọc cả số 0.',
    source: 'hw08x X3',
  },
  {
    id: 'm3.1-21',
    unit: '3.1',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen writes 4.6 × 10³ = 4.6000 and gives himself a tick. What is the right answer?',
    qVn: 'Thầy Bowen viết 4.6 × 10³ = 4.6000 và tự chấm đúng. Đáp án đúng là gì?',
    a: '4600',
    aVn: '4600',
    why: 'The digits move 3 places left: 46, 460, 4600.',
    whyVn: 'Các chữ số dịch 3 cột sang trái: 46, 460, 4600.',
    source: 'deck 3.2 s34',
    check: '4.6 * 10 ** 3',
  },
  {
    id: 'm3.1-22',
    unit: '3.1',
    level: 3,
    kind: 'calc',
    q: 'Work out 520 ÷ 10⁴.',
    qVn: 'Tính 520 ÷ 10⁴.',
    a: '0.052',
    aVn: '0.052',
    why: 'Not 0.52: that is only 3 places.',
    whyVn: 'Không phải 0.52: như thế mới dịch 3 cột.',
    source: 'deck 3.1 s11',
    check: '520 / 10 ** 4',
  },
  {
    id: 'm3.1-23',
    unit: '3.1',
    level: 3,
    kind: 'calc',
    q: 'Work out 0.06 × 10³.',
    qVn: 'Tính 0.06 × 10³.',
    a: '60',
    aVn: '60',
    why: 'Three places left, straight past the point: 0.6, 6, 60.',
    whyVn: 'Ba cột sang trái, đi qua dấu thập phân: 0.6, 6, 60.',
    source: 'hw08x X9b',
    check: '0.06 * 10 ** 3',
  },
  {
    id: 'm3.1-24',
    unit: '3.1',
    level: 3,
    kind: 'calc',
    q: '900 ÷ 10ⁿ = 0.09. What is n?',
    qVn: '900 ÷ 10ⁿ = 0.09. n bằng bao nhiêu?',
    a: '4',
    aVn: '4',
    why: 'The 9 moves 4 places right: 90, 9, 0.9, 0.09.',
    whyVn: 'Số 9 dịch 4 cột sang phải: 90, 9, 0.9, 0.09.',
    source: 'deck 3.1 s13',
    check: 'Math.round(Math.log10(900 / 0.09))',
  },
  {
    id: 'm3.1-25',
    unit: '3.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen starts with 5. He multiplies by 10⁴, then divides by 10², then multiplies by 10³. What number does he end with?',
    qVn: 'Thầy Bowen bắt đầu với 5. Thầy nhân với 10⁴, rồi chia cho 10², rồi nhân với 10³. Cuối cùng thầy được số nào?',
    a: '500 000',
    aVn: '500 000',
    why: 'Left 4, right 2, left 3: 5 places left. 5 × 10⁵.',
    whyVn: 'Trái 4, phải 2, trái 3: 5 cột sang trái. 5 × 10⁵.',
    source: 'deck 3.1 s14',
    check: '5 * 10 ** 4 / 10 ** 2 * 10 ** 3',
  },
  {
    id: 'm3.1-26',
    unit: '3.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen says: "To multiply by 10, just add a zero." Does that work for 3.2 × 10?',
    qVn: 'Thầy Bowen nói: "Muốn nhân với 10, chỉ cần thêm một số 0." Cách đó có đúng với 3.2 × 10 không?',
    a: 'No. 3.2 × 10 = 32',
    aVn: 'Không. 3.2 × 10 = 32',
    why: 'Adding a zero gives 3.20, which is still 3.2. The digits move.',
    whyVn: 'Thêm số 0 ra 3.20, vẫn chỉ là 3.2. Các chữ số dịch chuyển.',
    source: 'deck 3.1 s7 (adapted)',
    check: '3.2 * 10',
  },
  {
    id: 'm3.1-27',
    unit: '3.1',
    level: 3,
    kind: 'words',
    q: 'The digits of 6.1 move to make 0.061. Which way did they move, and how many places?',
    qVn: 'Các chữ số của 6.1 dịch chuyển thành 0.061. Chúng dịch về hướng nào, và mấy cột?',
    a: 'Right, 2 places',
    aVn: 'Sang phải, 2 cột',
    why: 'Not 3. Follow the 6: 6.1, 0.61, 0.061.',
    whyVn: 'Không phải 3. Theo dõi số 6: 6.1, 0.61, 0.061.',
    source: 'hw08x X10',
    check: 'Math.round(Math.log10(6.1 / 0.061))',
  },
  {
    id: 'm3.1-28',
    unit: '3.1',
    level: 3,
    kind: 'words',
    q: 'Write 750 g in kilograms.',
    qVn: 'Viết 750 g theo ki-lô-gam.',
    a: '0.75 kg',
    aVn: '0.75 kg',
    why: 'Up the ladder is ÷ 10³, so the number gets smaller. Not 750 000.',
    whyVn: 'Lên thang là ÷ 10³, nên số nhỏ đi. Không phải 750 000.',
    source: 'hw08x X17d',
    check: '750 / 10 ** 3',
  },
  {
    id: 'm3.1-29',
    unit: '3.1',
    level: 3,
    kind: 'words',
    q: 'One grain of rice has a mass of 29 mg. Mr Bowen buys a 5 kg bag and offers to count the grains. First, write 5 kg in milligrams.',
    qVn: 'Một hạt gạo nặng 29 mg. Thầy Bowen mua một túi 5 kg và đề nghị đếm từng hạt. Trước tiên, hãy viết 5 kg theo miligam.',
    a: '5 000 000 mg',
    aVn: '5 000 000 mg',
    why: 'kg to g to mg is two steps, so × 10⁶. That is about 172 414 grains.',
    whyVn: 'kg sang g sang mg là hai bậc, nên × 10⁶. Khoảng 172 414 hạt.',
    source: 'deck 3.2 s36',
    check: '5 * 10 ** 6',
  },
  {
    id: 'm3.1-30',
    unit: '3.1',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen writes 380 ÷ 10² = 38 and marks it right. What should it be?',
    qVn: 'Thầy Bowen viết 380 ÷ 10² = 38 và tự chấm đúng. Đáp án đúng là gì?',
    a: '3.8',
    aVn: '3.8',
    why: '38 is only 1 place. 10² means 2 places right.',
    whyVn: '38 mới chỉ dịch 1 cột. 10² nghĩa là dịch 2 cột sang phải.',
    source: 'hw08 E4b',
    check: '380 / 10 ** 2',
  },

  // ── 3.2 · Rounding ─────────────────────────────────────────────────────────
  {
    id: 'm3.2-01',
    unit: '3.2',
    level: 1,
    kind: 'words',
    q: 'What does "d.p." stand for?',
    qVn: 'Chữ "d.p." là viết tắt của cụm từ nào?',
    a: 'Decimal places',
    aVn: 'Decimal places (chữ số thập phân)',
    why: 'The digits after the decimal point.',
    whyVn: 'Các chữ số sau dấu thập phân.',
    source: 'deck 3.2 s23',
  },
  {
    id: 'm3.2-02',
    unit: '3.2',
    level: 1,
    kind: 'words',
    q: 'In maths, what does the word "round" mean?',
    qVn: 'Trong toán, từ "round" nghĩa là gì?',
    a: 'Write a simpler number close to it',
    aVn: 'Viết số đơn giản hơn, gần bằng nó',
    why: 'Vietnamese says it well: làm tròn means "make it round".',
    whyVn: 'Tiếng Anh "round" cũng có nghĩa là "tròn", giống tiếng Việt.',
    source: 'deck 3.2 s19',
  },
  {
    id: 'm3.2-03',
    unit: '3.2',
    level: 1,
    kind: 'words',
    q: 'What does "degree of accuracy" mean?',
    qVn: 'Cụm từ "degree of accuracy" nghĩa là gì?',
    a: 'How exact the answer has to be',
    aVn: 'Đáp án cần chính xác đến mức nào',
    why: 'The question always tells you. Do not choose your own.',
    whyVn: 'Đề bài luôn nói rõ. Đừng tự chọn theo ý mình.',
    source: 'deck 3.2 s22',
  },
  {
    id: 'm3.2-04',
    unit: '3.2',
    level: 1,
    kind: 'words',
    q: 'To round to 2 decimal places, which decimal place do you look at?',
    qVn: 'Muốn làm tròn đến 2 chữ số thập phân, em nhìn vào chữ số thập phân thứ mấy?',
    a: 'The third',
    aVn: 'Chữ số thập phân thứ ba',
    why: 'Always the next digit after the place you want.',
    whyVn: 'Luôn là chữ số ngay sau vị trí em cần.',
    source: 'deck 3.2 s24',
  },
  {
    id: 'm3.2-05',
    unit: '3.2',
    level: 1,
    kind: 'calc',
    q: 'Round 2.78 to 1 decimal place.',
    qVn: 'Làm tròn 2.78 đến 1 chữ số thập phân.',
    a: '2.8',
    aVn: '2.8',
    why: 'The next digit is 8, so round up.',
    whyVn: 'Chữ số ngay sau là 8, nên làm tròn lên.',
    source: 'deck 3.2 s25',
    check: 'round(2.78, 1)',
  },
  {
    id: 'm3.2-06',
    unit: '3.2',
    level: 1,
    kind: 'words',
    q: 'Is 4.53 nearer to 4.5 or to 4.6?',
    qVn: '4.53 gần 4.5 hơn hay gần 4.6 hơn?',
    a: '4.5',
    aVn: '4.5',
    why: 'Rounding means picking the nearer one.',
    whyVn: 'Làm tròn là chọn số gần hơn.',
    source: 'deck 3.2 s24',
    check: 'round(4.53, 1)',
  },
  {
    id: 'm3.2-07',
    unit: '3.2',
    level: 2,
    kind: 'calc',
    q: 'Round 34.9892 to 1 decimal place.',
    qVn: 'Làm tròn 34.9892 đến 1 chữ số thập phân.',
    a: '35.0',
    aVn: '35.0',
    why: 'The 9 carries. The .0 shows 1 decimal place: 35 loses the mark.',
    whyVn: 'Số 9 được nhớ lên. Phần .0 cho thấy 1 chữ số thập phân: viết 35 là mất điểm.',
    source: 'jeopardy maths-u2 · Place Value & Rounding 300',
    check: 'round(34.9892, 1)',
  },
  {
    id: 'm3.2-08',
    unit: '3.2',
    level: 2,
    kind: 'calc',
    q: 'Round 14.5 to the nearest whole number.',
    qVn: 'Làm tròn 14.5 đến số nguyên gần nhất.',
    a: '15',
    aVn: '15',
    why: 'Exactly halfway rounds up.',
    whyVn: 'Đúng ở giữa thì làm tròn lên.',
    source: 'hw08x X12c',
    check: 'round(14.5, 0)',
  },
  {
    id: 'm3.2-09',
    unit: '3.2',
    level: 2,
    kind: 'calc',
    q: 'Round 5.376 to 2 d.p.',
    qVn: 'Làm tròn 5.376 đến 2 d.p.',
    a: '5.38',
    aVn: '5.38',
    why: 'The next digit is 6, so the 7 rounds up.',
    whyVn: 'Chữ số ngay sau là 6, nên số 7 được làm tròn lên.',
    source: 'hw08 E2',
    check: 'round(5.376, 2)',
  },
  {
    id: 'm3.2-10',
    unit: '3.2',
    level: 2,
    kind: 'calc',
    q: 'Round 8.24618 to 3 d.p.',
    qVn: 'Làm tròn 8.24618 đến 3 d.p.',
    a: '8.246',
    aVn: '8.246',
    why: 'The next digit is 1: leave it.',
    whyVn: 'Chữ số ngay sau là 1: giữ nguyên.',
    source: 'deck 3.2 s28',
    check: 'round(8.24618, 3)',
  },
  {
    id: 'm3.2-11',
    unit: '3.2',
    level: 2,
    kind: 'calc',
    q: 'Round 2.04 to 1 decimal place.',
    qVn: 'Làm tròn 2.04 đến 1 chữ số thập phân.',
    a: '2.0',
    aVn: '2.0',
    why: 'The 4 says leave it. Keep the .0.',
    whyVn: 'Số 4 nghĩa là giữ nguyên. Giữ lại phần .0.',
    source: 'hw08x X15d',
    check: 'round(2.04, 1)',
  },
  {
    id: 'm3.2-12',
    unit: '3.2',
    level: 2,
    kind: 'words',
    q: 'Write 283.4617529 correct to the nearest 10.',
    qVn: 'Viết 283.4617529 chính xác đến hàng chục gần nhất (nearest 10).',
    a: '280',
    aVn: '280',
    why: '283 is nearer 280 than 290.',
    whyVn: '283 gần 280 hơn 290.',
    source: 'deck 3.2 s33',
    check: 'nearest(283.4617529, 10)',
  },
  {
    id: 'm3.2-13',
    unit: '3.2',
    level: 2,
    kind: 'words',
    q: 'Does "correct to 2 d.p." mean the same as "round to 2 d.p."?',
    qVn: '"Correct to 2 d.p." có nghĩa giống "round to 2 d.p." không?',
    a: 'Yes, the same job',
    aVn: 'Có, cùng một việc',
    why: '"To 2 decimal places" is the same job too.',
    whyVn: '"To 2 decimal places" cũng là cùng một việc.',
    source: 'deck 3.2 s21',
  },
  {
    id: 'm3.2-14',
    unit: '3.2',
    level: 2,
    kind: 'calc',
    q: 'Round 0.952 to 1 decimal place.',
    qVn: 'Làm tròn 0.952 đến 1 chữ số thập phân.',
    a: '1.0',
    aVn: '1.0',
    why: 'The 9 rounds up and carries: 1.0, not 1.',
    whyVn: 'Số 9 làm tròn lên và nhớ sang: 1.0, không phải 1.',
    source: 'hw08 E2',
    check: 'round(0.952, 1)',
  },
  {
    id: 'm3.2-15',
    unit: '3.2',
    level: 2,
    kind: 'words',
    q: 'A kitchen scale says 82 g. Does that mean exactly 82 g?',
    qVn: 'Cái cân nhà bếp ghi 82 g. Như vậy có nghĩa là đúng chính xác 82 g không?',
    a: 'No: 82 g to the nearest gram',
    aVn: 'Không: 82 g, làm tròn đến gam',
    why: 'The scale has rounded it. Its degree of accuracy is 1 gram.',
    whyVn: 'Cái cân đã làm tròn rồi. Độ chính xác của nó là 1 gam.',
    source: 'deck 3.2 s19',
  },
  {
    id: 'm3.2-16',
    unit: '3.2',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen rounds 0.0854 to 2 d.p. and gets 0.09. Is he right?',
    qVn: 'Thầy Bowen làm tròn 0.0854 đến 2 d.p. và được 0.09. Thầy làm đúng không?',
    a: 'Yes',
    aVn: 'Có',
    why: 'The next digit is 5, so 0.08 rounds up to 0.09.',
    whyVn: 'Chữ số ngay sau là 5, nên 0.08 được làm tròn lên 0.09.',
    source: 'q1rev C5d',
    check: "yes(round(0.0854, 2) === '0.09')",
  },
  {
    id: 'm3.2-17',
    unit: '3.2',
    level: 2,
    kind: 'calc',
    q: 'Work out 47 ÷ 9, correct to 2 d.p.',
    qVn: 'Tính 47 ÷ 9, chính xác đến 2 d.p.',
    a: '5.22',
    aVn: '5.22',
    why: '47 ÷ 9 = 5.222…, and the third digit is 2.',
    whyVn: '47 ÷ 9 = 5.222…, và chữ số thứ ba là 2.',
    source: 'hw08 E3a',
    check: 'round(47 / 9, 2)',
  },
  {
    id: 'm3.2-18',
    unit: '3.2',
    level: 2,
    kind: 'words',
    q: 'How many decimal places does 130.4 have?',
    qVn: '130.4 có bao nhiêu chữ số thập phân?',
    a: '1',
    aVn: '1',
    why: 'Not 4. Count from the point, not from the front.',
    whyVn: 'Không phải 4. Đếm từ dấu thập phân, không phải từ đầu số.',
    source: 'hw08x X13',
    check: "dp('130.4')",
  },
  {
    id: 'm3.2-19',
    unit: '3.2',
    level: 2,
    kind: 'words',
    q: 'Mr Bowen runs 100 m in 15.738 seconds. Write his time correct to 1 decimal place.',
    qVn: 'Thầy Bowen chạy 100 m hết 15.738 giây. Viết thời gian của thầy chính xác đến 1 chữ số thập phân.',
    a: '15.7 seconds',
    aVn: '15.7 giây',
    why: 'The next digit is 3: leave it.',
    whyVn: 'Chữ số ngay sau là 3: giữ nguyên.',
    source: 'deck 3.2 s22 (adapted)',
    check: 'round(15.738, 1)',
  },
  {
    id: 'm3.2-20',
    unit: '3.2',
    level: 2,
    kind: 'calc',
    q: 'Round 12.005 to 2 d.p.',
    qVn: 'Làm tròn 12.005 đến 2 d.p.',
    a: '12.01',
    aVn: '12.01',
    why: 'The 5 rounds the second 0 up to 1.',
    whyVn: 'Số 5 làm tròn số 0 thứ hai lên thành 1.',
    source: 'hw08x X16c',
    check: 'round(12.005, 2)',
  },
  {
    id: 'm3.2-21',
    unit: '3.2',
    level: 2,
    kind: 'calc',
    q: 'Round 7.4955 to 2 d.p.',
    qVn: 'Làm tròn 7.4955 đến 2 d.p.',
    a: '7.50',
    aVn: '7.50',
    why: 'The 9 carries. Write 7.50, not 7.5.',
    whyVn: 'Số 9 được nhớ lên. Viết 7.50, không phải 7.5.',
    source: 'deck 3.2 s27',
    check: 'round(7.4955, 2)',
  },
  {
    id: 'm3.2-22',
    unit: '3.2',
    level: 3,
    kind: 'calc',
    q: 'Round 0.649 to 1 decimal place.',
    qVn: 'Làm tròn 0.649 đến 1 chữ số thập phân.',
    a: '0.6',
    aVn: '0.6',
    why: 'Look at the 4 only. Not 0.65, then 0.7.',
    whyVn: 'Chỉ nhìn số 4. Không phải 0.65 rồi 0.7.',
    source: 'deck 3.2 s25',
    check: 'round(0.649, 1)',
  },
  {
    id: 'm3.2-23',
    unit: '3.2',
    level: 3,
    kind: 'words',
    q: '"Correct to 2 d.p." and "as far as 2 d.p." Same job, or different jobs?',
    qVn: '"Correct to 2 d.p." và "as far as 2 d.p." Cùng một việc, hay hai việc khác nhau?',
    a: 'Different jobs',
    aVn: 'Hai việc khác nhau',
    why: '"Correct to" means round. "As far as" means keep going, do not round yet.',
    whyVn: '"Correct to" nghĩa là làm tròn. "As far as" nghĩa là cứ tính tiếp, chưa làm tròn.',
    source: 'jeopardy maths-u2 · Place Value & Rounding 400',
  },
  {
    id: 'm3.2-24',
    unit: '3.2',
    level: 3,
    kind: 'calc',
    q: 'Work out 23 ÷ 9, correct to 2 d.p.',
    qVn: 'Tính 23 ÷ 9, chính xác đến 2 d.p.',
    a: '2.56',
    aVn: '2.56',
    why: '2.555… to 3 places, then round once. 2.55 stopped too early.',
    whyVn: '2.555… đến 3 cột, rồi làm tròn một lần. 2.55 là dừng quá sớm.',
    source: 'deck 3.2 s32',
    check: 'round(23 / 9, 2)',
  },
  {
    id: 'm3.2-25',
    unit: '3.2',
    level: 3,
    kind: 'calc',
    q: 'Work out 22 ÷ 7, correct to 3 decimal places.',
    qVn: 'Tính 22 ÷ 7, chính xác đến 3 chữ số thập phân.',
    a: '3.143',
    aVn: '3.143',
    why: 'Work to 4 places first: 3.1428. Then round once. 3.142 stopped too early.',
    whyVn: 'Tính đến 4 chữ số thập phân trước: 3.1428. Rồi làm tròn một lần. 3.142 là dừng quá sớm.',
    source: 'jeopardy maths-u2 · Place Value & Rounding 500 (adapted)',
    check: 'round(22 / 7, 3)',
  },
  {
    id: 'm3.2-26',
    unit: '3.2',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen rounds 2.7449 to 2 d.p. He gets 2.75 and gives himself a tick. What is the right answer?',
    qVn: 'Thầy Bowen làm tròn 2.7449 đến 2 d.p. Thầy được 2.75 và tự chấm đúng. Đáp án đúng là gì?',
    a: '2.74',
    aVn: '2.74',
    why: 'He rounded twice. Round once, from the number you were given.',
    whyVn: 'Thầy đã làm tròn hai lần. Chỉ làm tròn một lần, từ số đề bài cho.',
    source: 'deck 3.2 s34',
    check: 'round(2.7449, 2)',
  },
  {
    id: 'm3.2-27',
    unit: '3.2',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen writes: 2.996 to 2 d.p. = 2.99. What should he have written?',
    qVn: 'Thầy Bowen viết: 2.996 đến 2 d.p. = 2.99. Lẽ ra thầy phải viết gì?',
    a: '3.00',
    aVn: '3.00',
    why: 'The 6 rounds the 9 up, and it carries all the way: 3.00, not 3.',
    whyVn: 'Số 6 làm tròn số 9 lên, và nhớ sang tận đầu: 3.00, không phải 3.',
    source: 'hw08 E4c',
    check: 'round(2.996, 2)',
  },
  {
    id: 'm3.2-28',
    unit: '3.2',
    level: 3,
    kind: 'words',
    q: 'Mr Bowen weighs his cat. It is exactly 4.5 kg. The cat then eats 0.0283 kg of fish. What is the cat now, correct to 1 decimal place?',
    qVn: 'Thầy Bowen cân con mèo. Nó nặng đúng 4.5 kg. Sau đó con mèo ăn 0.0283 kg cá. Bây giờ con mèo nặng bao nhiêu, chính xác đến 1 chữ số thập phân?',
    a: '4.5 kg',
    aVn: '4.5 kg',
    why: '4.5283 kg. To 1 decimal place, the cat has not changed.',
    whyVn: '4.5283 kg. Đến 1 chữ số thập phân, con mèo không đổi.',
    source: 'deck 3.2 s37',
    check: 'round(4.5 + 0.0283, 1)',
  },
  {
    id: 'm3.2-29',
    unit: '3.2',
    level: 3,
    kind: 'words',
    q: 'A red blood cell is 0.0065982 mm long. Write this correct to 5 decimal places.',
    qVn: 'Một hồng cầu dài 0.0065982 mm. Viết số này chính xác đến 5 chữ số thập phân.',
    a: '0.00660 mm',
    aVn: '0.00660 mm',
    why: 'The 8 rounds the 9 up. Write 0.00660, not 0.0066.',
    whyVn: 'Số 8 làm tròn số 9 lên. Viết 0.00660, không phải 0.0066.',
    source: 'deck 3.2 s35',
    check: 'round(0.0065982, 5)',
  },
  {
    id: 'm3.2-30',
    unit: '3.2',
    level: 3,
    kind: 'words',
    q: 'A number is rounded to 1 decimal place. The answer is 5.4. What is the smallest the number could be?',
    qVn: 'Một số được làm tròn đến 1 chữ số thập phân và được 5.4. Số đó nhỏ nhất có thể là bao nhiêu?',
    a: '5.35',
    aVn: '5.35',
    why: '5.35 rounds up to 5.4. 5.349 would round to 5.3.',
    whyVn: '5.35 được làm tròn lên 5.4. 5.349 sẽ được làm tròn thành 5.3.',
    source: 'q1rev C6c (adapted)',
    check: '5.4 - 0.05',
  },
]
